### ISSUE TITLE
ADD: UX improvements

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#1015]
# ~Refresh button on add Liquidity~ done #1050 

when adding liquidity, need refresh button top right to let user refresh to see liquidity update

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/41812729/109614030-ee10ad00-7b81-11eb-9e61-7df4ea19fa8f.png">

# ~SELF tag for owned addresses~ done #1080

For any addresses that are owned by user - replace the address with `SELF` instead of address

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/41812729/109614095-11d3f300-7b82-11eb-908d-0a99b09980a4.png">

# ~CHAIN tag for pools~ done #1062 

Show pools as `CHAIN.ASSET` instead of just `ASSET`, for ETH/BNB assets, strip out the `-ID` at the end

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/41812729/109614309-624b5080-7b82-11eb-845e-d32b64fa9a10.png">

# ~NIGHT MODE ICON~ done #1058

use:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/41812729/109618245-39798a00-7b87-11eb-8967-640eee020af2.png">

https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=3521%3A25751

# ~Pool Filtering~ done #1079 

Pill buttons below heading, 

* `BASE` -> all the base assets, eg BTC.BTC, ETH.ETH etc
* `BEP2` -> all BNB assets
* `ERC20` -> all ETH tokens
* clear button -> if filter on, then show this button, which removes filter

<img width="638" alt="image" src="https://user-images.githubusercontent.com/41812729/109619335-96297480-7b88-11eb-886d-e4fbf851c4b3.png">

**Comment by thatStrangeGuyThorchain** [comment]
all issues are resolved. see appropriate PRs
