### ISSUE TITLE
ADD: MOBILE HEADER

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#104]
A hamburger menu with a pane that pops up.

The pane has a "table" with rows of `<icon? - title - action?>`  Each row is one of the header actions.
Can extend this to be suitable with whatever we need

https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=0%3A1

<img width="726" alt="image" src="https://user-images.githubusercontent.com/41812729/82786110-51f59f00-9ea7-11ea-9c9f-959773790744.png">
<img width="805" alt="image" src="https://user-images.githubusercontent.com/41812729/82786114-59b54380-9ea7-11ea-995e-b6fb0c11d3a9.png">

**Comment by veado** [comment]
@nomadnic As an addition to layouts above: 

The mobile view will include 
- (1) a dropdown to select a language (similar to "currency") 

and
 
- (2) another network status for Binance websocket connection

(1) + (2) have been already implemented in "desktop" view.
