### ISSUE TITLE
Translation improvement

### ISSUE THREAD

**Issue by Weyland2093** [thorchain/asgardex-electron#1041]
The texts "Click to sort descending" "Click to sort ascending" "Click to cancel sorting" are not availables in the translation files. I couldn't translate them in french...
![01](https://user-images.githubusercontent.com/79262935/110024679-b09d5280-7d2e-11eb-8f2b-9dcf294202ad.png)

**Comment by veado** [comment]
@Weyland2093 These texts are part of `antd` table (you can check antd's [i18n definition for table here](https://github.com/ant-design/ant-design/blob/4ad1ccac277782d7ed14f7e5d02d6346aae0db67/components/locale/default.tsx#L19-L33)). I think these definitions be overridden by using imported `antdData` you will find in each `src/renderer/i18n/{lang}/index.ts` (antData for FR [here](https://github.com/thorchain/asgardex-electron/blob/ad23f9502886df81592e5fd9ebba4f81cc546d10/src/renderer/i18n/fr/index.ts#L1))

**Comment by Weyland2093** [comment]
I see the french here : https://github.com/ant-design/ant-design/blob/4ad1ccac277782d7ed14f7e5d02d6346aae0db67/components/locale/fr_FR.tsx

but doesn't seem to work with FR or with my french windows 10.

**Comment by Weyland2093** [comment]
It's the same problem with DE and RU i see. 

---

import antdData from 'antd/lib/locale-provider/en_GB'

should be change by

import antdData from 'antd/lib/locale-provider/fr_FR'

for french in https://github.com/thorchain/asgardex-electron/blob/ad23f9502886df81592e5fd9ebba4f81cc546d10/src/renderer/i18n/fr/index.ts#L1 ??
