### ISSUE TITLE
[ETH] Pool shares

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1072]
Make sure ETH/ERC20 are listed in pool shares

**Comment by sarawut11** [comment]
they are listed but it has a few data mismatch issues.

**Comment by sarawut11** [comment]
![image](https://user-images.githubusercontent.com/35497333/111347735-12a47300-86b2-11eb-94ba-4ca14d41c94a.png)
![image](https://user-images.githubusercontent.com/35497333/111347765-19cb8100-86b2-11eb-8a2f-d5425605fc83.png)

some values are a bit different
