### ISSUE TITLE
[POOLS] Add common filters

### ISSUE THREAD

**Issue by kaiansaari** [thorchain/asgardex-electron#1076]
**Context:**
THORChain is designed for the economically significant assets on the economically significant chains ie. the short tail. We can therefore estimate the number of assets based on current altcoin mcap to be roughly 500-1000.

This presents a challenge for the pool list, and will require several filters (not sorting) to help users find what they need.

**Feature Request**
Add a filter component where several common filters can be added to rapidly filter out pools & aid discovery of relevant pools.

Examples:
`chain` - Filtering by `eth` for example will rapidly narrow the results so that I can search for relevent `ERC20` tokens.
`asset` - Filter by asset name eg. `btc` will yield `renbtc`, `wbtc`, `tbtc`, `btc` etc; `eth` = `eth`, `weth` etc.
`depth` - Relevant for searching for economically significant assets/deep pools.
`favorite` - Related to https://github.com/thorchain/asgardex-electron/issues/1075

**Comment by veado** [comment]
> `chain` - Filtering by `eth` for example will rapidly narrow the results so that I can search for relevent `ERC20` tokens. 
> `asset` - Filter by asset name eg. `btc` will yield `renbtc`, `wbtc`, `tbtc`, `btc` etc; `eth` = `eth`, `weth` etc.

^ DONE by #2275

> `depth` - Relevant for searching for economically significant assets/deep pools. 

 ^ Not sure how such search will look like - feel free to re-open this issue with more details

 > `favorite` - Related to #1075
 
 ^ Will be another PR
