### ISSUE TITLE
BTC Decimals are wrong 

### ISSUE THREAD

**Issue by boxofscraps** [thorchain/asgardex-electron#1078]
Swap quantities and fees displayed in ASGARDEX-0.0.7-win are missing.  Numbers are currently given in satoshi instead of BTC.  UI error highlighted in red. 
![777](https://user-images.githubusercontent.com/15699137/110451229-d69d5c80-8078-11eb-9bc0-bffc1909c36e.PNG)
![999](https://user-images.githubusercontent.com/15699137/110451231-d735f300-8078-11eb-8eb4-40d2ecc99cb1.png)

**Comment by veado** [comment]
It's a feature, not a bug. We do show amounts in `satoshi` whenever an amount is less than `₿ 0.01`. If you are interested, check code of `xchain-util` [here](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-util/src/asset.ts#L343-L346)
