### ISSUE TITLE
[Swap] Slip limit exceeded check

### ISSUE THREAD

**Issue by chaindbkey** [thorchain/asgardex-electron#1105]
Right now, we don't have slip limit exceeded check in swap page.
If the user send tokens to swap even though the slip limit is exceeded, then It is refunded so user lose the fees.
So in this case, the drag button needs to be disabled and show proper msg.

![image](https://user-images.githubusercontent.com/35497333/111187731-dbb55b00-85e6-11eb-8273-f592e0d490c1.png)

**Comment by veado** [comment]
Similar to `asgardex-web` we will add a slippage tolerance to the `Settings`.

`3%` `5%` `10%`  `__%` (custom)

![Screenshot from 2021-07-13 17-08-57](https://user-images.githubusercontent.com/61792675/125476967-7e979b5c-de1c-49c4-ad2c-8c1c07153069.png)
