### ISSUE TITLE
Fix expanded language dropdown on mobile

### ISSUE THREAD

**Issue by nomadnic** [thorchain/asgardex-electron#118]
The alignment is off when the language dropdown is expanded.

<img width="378" alt="mobile-language-dropdown" src="https://user-images.githubusercontent.com/5379790/83284499-fdbb2980-a1dc-11ea-9b8a-ae88d8e5f81e.png">

Suggestion is to have it appear full-width. The same component is used for desktop.

**Comment by veado** [comment]
Closed by https://github.com/thorchain/asgardex-electron/pull/142
