### ISSUE TITLE
Thorchain Transaction Explorer Link Broken

### ISSUE THREAD

**Issue by boxofscraps** [thorchain/asgardex-electron#1180]
When swapping RUNE to BTC, the view transaction link does not work. All thorchain transactions links are broken 

View Transaction current links to: 
https://testnet.thorchain.net/txs/2F85486530AE21D11EE7D386AE163E7A83115996F4F8585E99571B11228EC857/

The correct url is:
https://testnet.thorchain.net/#/txs/2F85486530AE21D11EE7D386AE163E7A83115996F4F8585E99571B11228EC857

Windows Version .0.07
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by veado** [comment]
Thanks for reporting this ^, @boxofscraps. It has been already fixed in latest `develop` and will be available with next release 0.8.0
