### ISSUE TITLE
[Deposit] Improve data handling for balances

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1185]
Currently we load all balances for deposit (which might take some time). ~~Use cached balances~~ (done by #1188) and improve `reloadBalances` by loading balances for selected assets only.

https://user-images.githubusercontent.com/61792675/112472704-bbfffe80-8d6d-11eb-882f-20936ddb29e3.mp4

**Comment by thatStrangeGuyThorchain** [comment]
resolved at #1262
