### ISSUE TITLE
Same token is shown twice in Asset overview

### ISSUE THREAD

**Issue by mikepocket** [thorchain/asgardex-electron#1200]
![image](https://user-images.githubusercontent.com/23121083/112610501-0f7d5580-8e1d-11eb-8b32-7e0101845601.png)

Issue for me is that BUSD is shown twice 

ASGARDEX VERSION v0.0.7

**Comment by veado** [comment]
That's correct. For testnet we have introduced another `BUSD` asset (`BNB.BUSD-74E`). If you open asset detail view (by clicking the row of any `BNB.BUSD`) and then jump to Binance explorer for one of its tx, you will see a different asset name. It's for `testnet` only, it wont be there for upcoming `multichain chaosnet` (MCCN).


https://user-images.githubusercontent.com/61792675/112715638-b7f4ed80-8ee1-11eb-9c66-e09dfebc3b09.mp4
