### ISSUE TITLE
[Wallet] AssetDetail: Reload balances

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1209]
By clicking "reload" button, load data for tx history AND balances.

https://user-images.githubusercontent.com/61792675/112717272-d5c75000-8eeb-11eb-88d1-1831a6533653.mp4

**Comment by GrassRootsCrypto** [comment]
Have the same issue - I noticed that fees are updated, can the there be an asset update at the same time or is there a cost to do this.
