### ISSUE TITLE
[SWAP] Input: Decimal handling is clumsy

### ISSUE THREAD

**Issue by kaiansaari** [thorchain/asgardex-electron#1213]
Entering decimals for any input amount is clumsy. The input auto corrects to remove the decimal sometimes, on tabbing out changes the input value and other times respects the decimal.

Handle decimals like any other input amount. Allow decimals, trim to 1e8 but do not prevent the user from entering a decimal or change the amount on tab key.

**Comment by veado** [comment]
Resolved by #1238
