### ISSUE TITLE
cannot estimate gas - display issue

### ISSUE THREAD

**Issue by busjockey** [thorchain/asgardex-electron#1215]
ETH RUNE LP'ing 

OR={"REASON":"CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT","CODE":"UNPREDICTABLE_GAS_LIMIT","METHOD":"ESTIMATEGAS","TRANSACTION":{"FROM":"0XB078B4E8FA411B784E04A9DCC0E97D62F6A0759A","GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X14419AA600"},"TO":"0X9D496DE78837F5A2BA64CB40E62C19FBCB67F55A","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0DD610D89A7CE400"},"DATA":"0X1FECE7B4000000000000000000000000C5E3BC6DA47DCBFEAE8ADAA3BF6803857A1068E200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72313674676A713433307061787278393370637068336D656C7236676A6B716C373374657270706E0000000000000000"}}, TX={"DATA":"0X1FECE7B4000000000000000000000000C5E3BC6DA47DCBFEAE8ADAA3BF6803857A1068E200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72313674676A713433307061787278393370637068336D656C7236676A6B716C373374657270706E0000000000000000","TO":{},"GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X14419AA600"},"FROM":"0XB078B4E8FA411B784E04A9DCC0E97D62F6A0759A","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0DD610D89A7CE400"},"NONCE":{},"GASLIMIT":{},"CHAINID":{}}, CODE=UNPREDICTABLE_GAS_LIMIT, VERSION=ABSTRACT-SIGNER/5.0.10)

![Screenshot 2021-03-29 at 12 23 30](https://user-images.githubusercontent.com/81547566/112787132-781d3a00-908a-11eb-8c7b-6db15bf5b8c7.jpg)

## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

 testnet LP of ETH and RUNE

## Current Behavior

 Deposit Error

## Possible Solution

 perhaps a reminder note to leave ETH in wallet to provide for the ETH gas fees

## Steps to Reproduce (for bugs)

1. Deposit 100% testnet ETH and 100% testnet RUNE

2. slide to deposit

3. error message received

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version : macos
- Link to your project :

**Comment by veado** [comment]
> Using an up-to-date master branch

Have you run ASGDX (1) by building it from latest `master` ^ or (2) by downloading it from [0.0.8 release page](https://github.com/thorchain/asgardex-electron/releases/tag/v0.0.8)?

For (1): Try to use latest `develop` branch (master has not been updated yet) and make sure you have added all needed ENV to your `.env` as you can see in [.env.sample](https://github.com/thorchain/asgardex-electron/blob/develop/.env.sample) (e.g. API key for Etherscan etc.)
