### ISSUE TITLE
French menu

### ISSUE THREAD

**Issue by Weyland2093** [thorchain/asgardex-electron#1221]
With DE or RU, the menu "Edit View Help" change when we switch the language. Not in french... it stays "Edit View Help".

**Comment by veado** [comment]
@ Weyland2093 Could you [translate these texts](https://github.com/thorchain/asgardex-electron/pull/1227/files#diff-9bba1c001ad300a562d7c89e75fc1cdce3e5f25f03aaad832878c93994cbb5b6R1-R34) needed for FR menu, pls? It's part of #1227. Thank you!
