### ISSUE TITLE
[UI] Make node address input wide enough to see it ALL

### ISSUE THREAD

**Issue by mcadam** [thorchain/asgardex-electron#1247]
It would be nice to have all the inputs where we enter a node address to be wide enough so it shows the full address.
We do have some extra space in those views so easy to add to avoid this, where we dont see the last characters of the address and could even think the last characters are those displayed:

<img width="1354" alt="Screenshot 2021-04-01 at 09 14 18" src="https://user-images.githubusercontent.com/3319629/113246854-e5b7a900-92ca-11eb-87d4-179a593a4cc6.png">

**Comment by veado** [comment]
Fixed by #1556
