### ISSUE TITLE
Swap DAI to RUNE does not work

### ISSUE THREAD

**Issue by boxofscraps** [thorchain/asgardex-electron#1276]
I am unable to swap DAI for RUNE, only RUNE For DAI.  The switch base asset button does not work. 

![image](https://user-images.githubusercontent.com/15699137/113830337-5f242100-973b-11eb-98d0-a12c3cdc20d0.png)

However, it does work with other ERC20 assets like USDT. 

Windows v0.0.8

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by veado** [comment]
@boxofscraps Do you have already some amounts of `ETH.DAI` in your wallet? If not, switch is disabled, because you can't swap from `DAI` to `RUNE` in this case.

**Comment by boxofscraps** [comment]
@veado yes, I do have ETH.DIA in my wallet. However I just noticed there is no DIA token recognized in the wallet section. 

![image](https://user-images.githubusercontent.com/15699137/113964172-cb586080-97df-11eb-8eb5-0c4984192803.png)

https://ropsten.etherscan.io/address/0x9f6456e8eff565bc55c77d46dcaade8baac498ad#tokentxns

**Comment by veado** [comment]
@boxofscraps Good catch! For `testnet` we currently add supported ERC20 tokens hard-coded [here](https://github.com/thorchain/asgardex-electron/blob/develop/src/renderer/const.ts#L92-L99) in ASGDX and it needs to be updated. _Will be fixed soon ..._
