### ISSUE TITLE
Support Request: Utility Reference for Checking latest.yml sha512 values

### ISSUE THREAD

**Issue by roleerob** [thorchain/asgardex-electron#1319]
Environment: Windows 10 Professional, 64-bit

As the recommended safety precaution, in attempting to confirm the sha512 value in your latest.yml file, for the Asgardex wallet file downloaded, I am unable to reproduce it. 

Why?

Up until this morning, I have always used the Windows certutil utility to generate the needed checksum values on this end.  The result of that, however, does not match what I see in your latest.yml file.

What Windows utility do we use to confirm our download is safe?  If you have a reference link to the answer, that would be greatly appreciated!

**Comment by veado** [comment]
@roleerob With latest releases you will a `msg` file with `sha` check sum for each binary included. This `msg` file can be verified with a signature. More details on latest release page https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.5
