### ISSUE TITLE
Deposit to pool failed. BUSD gone. RUNE stayed

### ISSUE THREAD

**Issue by nikolasete** [thorchain/asgardex-electron#1324]
BUSD disappeared when a deposit to the BUSD-RUNE pool was done. No pool created and the RUNE still there. Webpage: https://app.asgard.exchange/pool
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

It should be created a position in the BUSD-RUNE pool with 499 BUSD and 40 RUNE

## Current Behavior

No pool was created. The BUSD have gone. Txid (BNB transaction) https://explorer.binance.org/tx/88F54728FA1D7CA1874135EB9677E10DB96D4C93FEC61FF4963823D385C330DF

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by veado** [comment]
@nikolasete Have you used ASGARDEX desktop or https://app.asgard.exchange for you swap? For the latter, pls open an issue at https://github.com/asgardex/asgard-exchange/issues, thx!

**Comment by philoko2** [comment]
Same problem here (also via https://app.asgard.exchange/pool), except with LTC-RUNE: No pool created, RUNE is in wallet, LTC is gone.

Transaction link: https://ltc.bitaps.com/d072c2b10f95bce5d645778eb7c2a7428e1c46113fecae2fb91e57b2fcc00f5f/input/0

Hopefully, this can be corrected (pool share in LTC-RUNE should have 5 LTC and 110 RUNE - initially).

**Comment by veado** [comment]
> No pool created
@philoko2  What do you mean by this ^? You can't create a pool with ASGARDEX desktop.

**Comment by philoko2** [comment]
As stated, I have not used ASGARDEX desktop, but ASGARDEX Web.
