### ISSUE TITLE
UI, Trivial:  Passphrase request to unlock wallet says "Enter your your passphrase"

### ISSUE THREAD

**Issue by eode** [thorchain/asgardex-electron#1332]
"Your" is there twice.

Note:  How does one file a bug for the latest release?  Is general bugreporting only allowed if you're willing to invest the time to set up a development environment?  

## Prerequisites
- [x] Using release version, v0.1.0.
- [ ] Using yarn
- [x] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior
"Your" is present only once, as in "Enter your passphrase".

**Comment by veado** [comment]
> How does one file a bug for the latest release? Is general bugreporting only allowed if you're willing to invest the time to set up a development environment?

@eode Thanks for your report. You can file issues for releases, too. Just share release version in your bug description - no need to build / run ASGARDEX locally.

**Comment by veado** [comment]
@eode Sure, or just create a PR to change the template ;)
