### ISSUE TITLE
Stuck/lost funds when adding liquidity

### ISSUE THREAD

**Issue by eode** [thorchain/asgardex-electron#1334]
I added about $15 in BCH, $15 in RUNE to a LP as a test transaction. This left ~$5 in RUNE for fees, listed as 0.1 RUNE.

The BCH were immediately removed, the RUNE were not, and after a decent delay, I had approximately $1.30 in both BCH and RUNE (totally $2.60) in the pool.  Again, the RUNE were untouched, but where did the remaining 90% of the funds go?  Aside from that, it seems this shouldn't be possible, and will upset users.

## Prerequisites

- [x] Using release 0.1.0

## Expected Behavior
- Depositing funds to a liquidity pool reports accurate fees.
- If a transaction fails in any way shape or form (excessive unstated fees would result, transfer problems, etc) the transaction is aborted and the balance is left as-is.
- Only the specified transaction should occur -- a two-part add was specified, only one currency was used

## Current Behavior
- Incorrect RUNE fees are stated
- RUNE added to the pool wasn't taken or used for the transaction
- External currency (BCH) was reduced by 90% and split between pools.

## Possible Solution
This seems like it *may* be a protocol issue.  This *may* be the kind of error that shouldn't even be possible.

Possibly related:
https://github.com/thorswap/thorswap-finance-app/issues/60

## Steps to Reproduce (for bugs)
I don't have the cash to invest in trying this a lot.  But what I did was:

1.  Split currencies in half, roughly 50/50 rune/x (BCH).

2.  Add as much as I can using the pool UI (Note, 100% isn't doable due to fee estimation)

3.  Transaction succeeds according to the UI, but actually, failures and partial transactions are occurring.

## Context
I was attempting to build a small liquidity pool with my remaining BCH/RUNE.  I lost nearly half of the funds involved, though it was, overall, a small amount.
No changes were made to the app -- this is the 0.1.0 release version.

## Your Environment
- Node version : Unknown
- Version or Branch used : 0.1.0 release
- Operating System and version : Ubuntu Linux 20.04
- Link to your project :  n/a

**Comment by veado** [comment]
@eode Could your share transaction id's, pls?

**Comment by Dequadin93** [comment]
hi, i face the same problem as well. I did swap 100% of my rune to 50% rune and BNB , managed to only stake 50% of the rune + bnb, in which i should have 25% rune and 25% bnb left, however i only have the rune and not bnb. 

This is my main transaction ID E4FC016567222CC9740C496FF19BD2E5A414154A679B500B9E00F99918998C2E

![rune 1](https://user-images.githubusercontent.com/82533499/114756133-02ed7c80-9d8d-11eb-979a-62a50bb7efff.png)
this is what I'm left after staking.

![rune 2](https://user-images.githubusercontent.com/82533499/114756147-054fd680-9d8d-11eb-80ce-0107ca1b8ae5.PNG)
This is the value i staked.

As you can see there are bnb missing, let me know what you need to solve the problem. thank you

**Comment by cbarraford** [comment]
@Dequadin93 that transaction hash you referenced is a swap from rune --> bnb. You put in about 449 rune to get back about 12 BNB. Which, per your memo, was sent to a bnb address ending in `p9x` (see [txn](https://explorer.binance.org/tx/841205E69C158D1B2F43F60CBD2A4CBF1AFC083E257CE2A3E9ADE79B0D0413A7)).

If you've done a staking as well, can you share those transaction hashes?

**Comment by Dequadin93** [comment]
> @Dequadin93 that transaction hash you referenced is a swap from rune --> bnb. You put in about 449 rune to get back about 12 BNB. Which, per your memo, was sent to a bnb address ending in `p9x` (see [txn](https://explorer.binance.org/tx/841205E69C158D1B2F43F60CBD2A4CBF1AFC083E257CE2A3E9ADE79B0D0413A7)).
> 
> If you've done a staking as well, can you share those transaction hashes?

ECB4875520DC90B035F107331EDDC24ECF47B76C919456E568694FDBA777BA08. this is the stake, which resulted in my second picture. Doesnt seem to add up

**Comment by cbarraford** [comment]
@Dequadin93 looks like you sent in 16 rune, and 11.7 BNB into your stake. Thats ~$250 rune and ~$6300 BNB. Then looking at your current staking, it looks like you have $6,643.63 in LP units
https://app.runeyield.info/dashboard?thor=thor1n7peds0s7egwm5da0na52ngxt0zuy62rkune86

Looks ok to me, unless I'm missing something

**Comment by Dequadin93** [comment]
> @Dequadin93 looks like you sent in 16 rune, and 11.7 BNB into your stake. Thats ~$250 rune and ~$6300 BNB. Then looking at your current staking, it looks like you have $6,643.63 in LP units
> https://app.runeyield.info/dashboard?thor=thor1n7peds0s7egwm5da0na52ngxt0zuy62rkune86
> 
> Looks ok to me, unless I'm missing something

okay i might not have explained it propeerly, i had 881 runes at first. This picture shows the transactions 
![image](https://user-images.githubusercontent.com/82533499/114761170-bc028580-9d92-11eb-992c-af5db7d1f392.png)

I should be having more bnb or rune in my pool at least? The wallet transaction is right, the pool isnt. 

this is the remaining in my thor wallet

![image](https://user-images.githubusercontent.com/82533499/114761411-02f07b00-9d93-11eb-9e4c-b8e14c2babb4.png)

**Comment by eode** [comment]
My Thor Address: thor1dnk52rsl2e0vla0ja9f8zltgyjc4t448xylaf6
Thor Txn pool-in RUNE: 
  * 9F37EBA1657F1D0EC700E60800327685F739BB2BE85929AC56A07A62CEF908A3
  * shows up as 0.0442 Rune, about $0.50)
  * Shows in wallet as happening at 09:07:53, on thorchain as happening at 9:14

Thor Txn pool-in BCH:
  * 229FFFF7D150230EFD41FAEC130DE9AF795D776AB4D34F499A1AA59F9F136B15
  * shows up as 0.0024 BCH, about $2.00

My BCH Address: bitcoincash:qpuvjn0ua89nucjpulc89y6a08gmy385hsfff5ue4x
Relevant BCH Txn 1:
  * This is the amount (or right around the amount) I was pooling, although i'm uncertain if that is the one.  There aren't many on there, and it is at the right time.
  * bitcoincash:53c594619fcd7672818972a802b9cb651cad5de56c4ad93c758464dae5488a00
Relevant BCH Txn 2:
  * This looks like the amount that ended up getting pooled.
  * bitcoincash: 229ffff7d150230efd41faec130de9af795d776ab4d34f499a1aa59f9f136b15

I had about 1.47 rune, ~ $17.00, and about $15 in BCH.  Afterwards, in case it was stuck by fees, I swapped some BNB -> 3.55616779 RUNE.  After waiting for an un-sticking (none happened), I transferred 2 rune to a friend who is having similar issues with LTC in case *his* issue was that it was stuck by missing fees (although he can't see his LTC at all, and the pool never gained *any* value).

In case it's relevant, his Thor address is thor14fzhkzp6zjkve8pfj3dy4tv2sexjtanl9ju032.

**Comment by eode** [comment]
@veado updated, but forgot to mention you.

**Comment by cbarraford** [comment]
@Dequadin93 looks ok to me.

1. switched 881 rune
2. swapped half to BNB, leaving you with ~432 rune
3. deposited 16, leaving you with ~416 rune
4. swapped half to BNB, leaving you with 209 rune.

**Comment by Dequadin93** [comment]
> @Dequadin93 looks ok to me.
> 
> 1. switched 881 rune
> 2. swapped half to BNB, leaving you with ~432 rune
> 3. deposited 16, leaving you with ~416 rune
> 4. swapped half to BNB, leaving you with 209 rune.

If you referred to my first post you would realize that there might be a lack of rune or bnb in the pool, i am sure i am lacking bnb, but for further clarification this is my bnb transactions, hope this helps. 

![image](https://user-images.githubusercontent.com/82533499/114766056-806aba00-9d98-11eb-88d0-461ab8eaed35.png)

**Comment by cbarraford** [comment]
@eode the first add to the BCH pool looks fine. The second one hasn't been added to the pool because its "pending", waiting for the rune to be sent in. As soon as you send an equal amount of rune (in dollar value) to the BCH pool, you should find your `0.01812347` BCH added to the pool for you

**Comment by cbarraford** [comment]
@Dequadin93 similar to @eode , you send BNB into the BNB pool (https://explorer.binance.org/tx/F1DA194EEBC85318E8D45A3DDA9327A2E8D70E55529093AC48D3C67B02AA9E3D), but never sent in the rune. So your BNB is pending in the pool, until you add rune into the BNB pool. Do that and you'll find your BNB LP units will increase.

**Comment by Dequadin93** [comment]
> @Dequadin93 similar to @eode , you send BNB into the BNB pool (https://explorer.binance.org/tx/F1DA194EEBC85318E8D45A3DDA9327A2E8D70E55529093AC48D3C67B02AA9E3D), but never sent in the rune. So your BNB is pending in the pool, until you add rune into the BNB pool. Do that and you'll find your BNB LP units will increase.

Then this is a bigger problem, how could i cancel that transaction to add into the LP with the correct amounts again? or how do i add only RUNE to the bnb pool in order to match my pending bnb?

**Comment by cbarraford** [comment]
@veado both of the individuals tried to add liquidity, but the rune side failed for them. My best guesses on why that may be...

1. a random fluke
2. when calculating the amount of rune to send in, the gas is not taken into account, and there isn't enough rune to pay for gas
3. They signed the rune side with a sequence number that had already been used.

**Comment by rrobinson2000** [comment]
Same happened to me (with LTC). How does one just add Rune to the pool?

**Comment by dagurval** [comment]
I have the same issue (BCH), transactions `af80b75fd149a610b49a3e497b67861c906602c35d42763a42954745363379a0` and `bf9983d85c4a17920eb8f9dc3e560519530d4bd7210a77a42c039a637bca2a5b` went through, but not the RUNE side.

**Comment by cbarraford** [comment]
Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

**Comment by felvhage** [comment]
I have the same issue with BNB. 
**Error-Message: "RUNE Deposit failed"**
I got a Window to try resubmitting RUNE but it did not work.

What i did:
- Transfered BNB to Asgarddex (WEB)
- Swapped ~50% to rune
- Tried to supply liquidity
TX:
1FEA921B8AAC1E98C4C4246CA7DFF25B55CDB49DE275D80CDCE188ED16433DBA
The Transaction was supposed to add 0.035 BNB and ~1,19.... Rune
But **only the BNB was transfered**.

**Comment by Dequadin93** [comment]
Problem solved, brilliant, thank you so much

**Comment by dagurval** [comment]
> Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

I tried to deposit 0.5 RUNE this way, however I got 'insufficient funds' error. I have 0.65 rune in the wallet, so there should be 0.1 for fee still.

I added a breakpoint at the exception and it looks like its failing because it wants 1 RUNE for gas:

<img width="608" alt="Screenshot 2021-04-14 at 22 48 27" src="https://user-images.githubusercontent.com/92707/114777425-f6a8f580-9d73-11eb-9504-d8f0db49a7c5.png">

**Comment by eode** [comment]
> @eode the first add to the BCH pool looks fine. The second one hasn't been added to the pool because its "pending", waiting for the rune to be sent in. As soon as you send an equal amount of rune (in dollar value) to the BCH pool, you should find your `0.01812347` BCH added to the pool for you

So the main issues now are:

* This is a bug that affects quite a few people
* The creation of incomplete pools in the UI needs to be fixed
* How does a typical (non-technical) user detect and fix situations where pool creation is only half complete?
* How should a typical user determine that their coins are in this state?  What about those who aren't as deeply familiar, or don't realize they have lost/held funds awaiting for a second transfer that Asgardex didn't complete?  Perhaps they just think the funds were lost due to transaction fees.
   * Perhaps a means of displaying stuck funds, with an option to put in a matching contract?

In general, this seems like the kind of thing that should be handled at the protocol level, or at least have a standard way of error catching and repair.

**Comment by felvhage** [comment]
> Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

I also did this to fix my issue. It did kind of work, and my RuneYield status contains about the amount of my two LP Add Transactions. 

Strangely, it seems that my two "liquidity-ADD"s are mixed up:
- When i first tried to add BNB:Thor the thor part of the transaction failed
- Then i tried it again (from Desktop-APP instead of Web) and it assigned the Thor from the new transaction to the previous BNB
- Then i tried the Custom-Deposit trick and it assigned the new thor tokens to the BNB still pending from the second transaction.

A bit unsettling, but good to know this can be fixed.

**Comment by rrobinson2000** [comment]
> Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

I have the same issue with LTC. Just to double check what "asset address" should I use? The LTC public key from my asgardex wallet? or something else?

**Comment by eode** [comment]
> Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo ADD:<pool>:<asset address (example, ADD:BNB.BNB:bnb1XXXXXXX). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

Wow, don't make any typos there.  Manually entering the contract data?

**Comment by rrobinson2000** [comment]
> I have the same issue with BNB.
> **Error-Message: "RUNE Deposit failed"**
> I got a Window to try resubmitting RUNE but it did not work.
> 
> What i did:
> 
> * Transfered BNB to Asgarddex (WEB)
> * Swapped ~50% to rune
> * Tried to supply liquidity
>   TX:
>   1FEA921B8AAC1E98C4C4246CA7DFF25B55CDB49DE275D80CDCE188ED16433DBA
>   The Transaction was supposed to add 0.035 BNB and ~1,19.... Rune
>   But **only the BNB was transfered**.
> 
> ![image](https://user-images.githubusercontent.com/3090088/114773392-4e912d80-9d6f-11eb-86f3-5de6d1cd64d8.png)
> 
> Update:
> I did the same on Asgarddex (Desktop) and it was successful
> 
> Update 2:
> Fixed the missing rune in the pool via custom deposit trick from cbarraford. Thank you!

What was the "asset address" that you used? Was it the BNB public key from your asgardex wallet?- thanks!

**Comment by rrobinson2000** [comment]
> Problem solved, brilliant, thank you so much

What was the "asset address" that you used? Was it the BNB public key from your asgardex wallet?- thanks!

**Comment by eode** [comment]
@veado , @cbarraford 

> @veado both of the individuals tried to add liquidity, but the rune side failed for them. My best guesses on why that may be...
> 
>     1. a random fluke
> 
>     2. when calculating the amount of rune to send in, the gas is not taken into account, and there isn't enough rune to pay for gas
> 
>     3. They signed the rune side with a sequence number that had already been used.

If that's a fluke, it's a lot of people having the exact same fluke.

And, in Telegram, Architect01 (or similar) said that the asgardex site has the same issue.  And that is currently down for bug fixes.  And it has to do with erroneous fee calculation.

But regardless, in *any* failure case, if there's an imbalanced pool, the user should be informed and presented a way to fix it.

**Comment by eode** [comment]
@rrobinson2000 There's no way I'm going to manually type in transaction code.  I'm going to wait for their fix.

**Comment by rrobinson2000** [comment]
> > Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"
> 
> I tried to deposit 0.5 RUNE this way, however I got 'insufficient funds' error. I have 0.65 rune in the wallet, so there should be 0.1 for fee still.
> 
> I added a breakpoint at the exception and it looks like its failing because it wants 1 RUNE for gas:
> 
> <img alt="Screenshot 2021-04-14 at 22 48 27" width="608" src="https://user-images.githubusercontent.com/92707/114777425-f6a8f580-9d73-11eb-9504-d8f0db49a7c5.png">

@dagurval did you get this working? What address did you use the for "asset address"? Was it the public key of your BTC in your asgardex wallet?

**Comment by rrobinson2000** [comment]
> Goto the "wallet" tab, click "RUNE", click "Deposit", click "custom", enter the memo `ADD:<pool>:<asset address` (example, `ADD:BNB.BNB:bnb1XXXXXXX`). For amount, put an equal amount (in dollar value) to the pending asset. Click "send"

@cbarraford can you clarify what is the "asset address"? Is it the public key of the other asset? In my case LTC was taken fine but RUNE side failed so I'd like to try your method. Would I then use ADD:LTC:LTC:ltc1XXXXX ?

**Comment by eode** [comment]
@cbarraford @veado 
Can we set this bug on fire right now?  Because this is the number one thing in the telegram channel, all day.  It's affecting Asgardex Desktop, Asgardex website, and ThorSwap.

**Comment by veado** [comment]
We have identified two issues in ASGARDEX desktop:

1. Mismatch for RUNE tx fees (it's currently based on obsolete fees of 0.01 ᚱ provided by xchain-thorchain library). Fees should be > 0.02 as defined in Mimir
2. Missing status of "pending" assets or Rune for an user - it needs to be double checked before sending a deposit in ASGDARDEX desktop.  

We already started our work to fix both issues ^. Sorry for all the trouble + thanks for being patient!

**Comment by eode** [comment]
@veado 
Not a problem, and thanks for your work.  We all bought in hoping we could help out, find bugs, etc -- well, I did, anyways, and you guys were clear that there would likely be bugs.

**Comment by eode** [comment]
FYI, on the $15/15 BCH/RUNE LP Add, I was recommended on Telegram to use the Asgardex (site) `deposit-sym-recovery` tool to withdraw that liquidity.  It appears that I may have been affected by another bug, and that the pending asset was lost(!).  While this isn't a major issue for $15 or so, it's a major issue for anyone who has more in there and loses it.  I may be running into an issue mentioned [here](https://github.com/asgardex/asgard-exchange/issues/349).

**Comment by veado** [comment]
With latest ASGARDEX `0.2.0` fee handling has been improved. Also UI makes sure, users put a min. amount to cover all fees. _Closing issue for now ..._

**Comment by eode** [comment]
Is there a means of recovering liquidity lost in Asgardex Desktop?

**Comment by veado** [comment]
> Is there a means of recovering liquidity lost in Asgardex Desktop?

It's not supported (yet). At the meantime you can find such a tool in `asgard.exchange` or `THORSwap`:
- https://app.asgard.exchange/deposit-sym-recovery
- https://app.thorswap.finance/pending

**Comment by eode** [comment]
Note to whoever comes after -- Use THORSwap, not Asgardex.  Thorswap's interface and code are in better condition, and I ran into an issue with incorrect withdrawal amount on Asgardex leading to lost value (which is currently being looked into by them).
