### ISSUE TITLE
Keep consistent view for coins on View Wallet window

### ISSUE THREAD

**Issue by kolya182** [thorchain/asgardex-electron#1340]
When new wallet created and entered View Wallet screen, some coins displaying balance some don't.
<img width="330" alt="Screen Shot 2021-04-14 at 1 50 59 PM" src="https://user-images.githubusercontent.com/3277207/114777486-98a2f080-9d28-11eb-87e4-ae12a6cded47.png">

**Comment by veado** [comment]
@kolya182 Just realized your issue might be related to [THORSwap](https://app.thorswap.finance/), pls open an issue in [their repository](https://github.com/thorswap/thorswap-finance-app).
