### ISSUE TITLE
ETH Balance in ASGARDEX Wallet

### ISSUE THREAD

**Issue by brettkimura** [thorchain/asgardex-electron#1341]
## Prerequisites

- [] Using yarn
- [X] Using node 12.x
- [X] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

When I swap rune for ETH the eth balance should show up in my wallet.

## Current Behavior

I swap rune for eth and the balance doesnt show in my wallet (over 12 hours) yet the confirmation happened within minutes and eth address shows a different balance.

thor wallet: thor1nn4czmh9qrz3xptnjqnj40fmd0g40yvj4pxe3w
eth wallet: 0x80adb2f06cdf4699bafaeede2699797e9d808aa5

## Possible Solution

ETH balance should update and be useable in thor wallet.

## Steps to Reproduce (for bugs)

1. Select swap rune for eth

2. Make swap

3. wait for it to complete

4.

## Context

I have ETH that I cant use to process eth transactions (like upgrade to native rune) because it appears I dont have enough eth in my wallet, when I do.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version : MacOS
- Link to your project :

MIDGARD
https://midgard.thorchain.info
VERSION
v0.1.0

**Comment by veado** [comment]
@brettkimura Have you tried to re-load balances in `Wallet` -> `Assets` -> click `Refresh` button? Etherscan shows me a [successful IN tx](https://etherscan.io/tx/0x7cd41ad522e78d1e57644a04230a9c5037d58641b2bfe07cd9bbf9cae812c911) for your account. Could you verify it again?

**Comment by veado** [comment]
Similar to https://github.com/thorchain/asgardex-electron/issues/1389. _Closing it here for now to follow it up at one place only._
