### ISSUE TITLE
STUCK/MISSING FUNDS AFTER TRYING TO ADD LIQUIDITY

### ISSUE THREAD

**Issue by mastosis** [thorchain/asgardex-electron#1343]
I tried adding 1.98 of BNB to the BNB.RUNE pool.. going 50/50 with Rune. The transaction didn't go through however half of my BNB per the dex explorer has been sent to an unknown address.. and the other half is still in my wallet. Are my funds missing? i also cannot tell if the Rune side of the transaction went through.
It is worth to note that i tried withdrawing the other half in my wallet but that didn't go through 
Tx hash--D5F057D28863849DB6EA3ECA74E3D144931D740B3B6E4EA243A616223155AEF6

address my bnb was sent to--bnb1ksxqxurvejkndenuv0alqawpr3e4vtqk855aal

**Comment by skyorion427** [comment]
Your funds are SAFE.

https://thornode.thorchain.info/thorchain/tx/D5F057D28863849DB6EA3ECA74E3D144931D740B3B6E4EA243A616223155AEF6

Team will get back to you with the resolution. Thanks.

**Comment by veado** [comment]
> has been sent to an unknown address
It has been send to a pool address.

> Are my funds missing?
No, your funds are still safe, but set as "pending". You can check it [here](https://thornode.thorchain.info/thorchain/pool/BNB.BNB/liquidity_providers) by looking for your address and state of "pending_asset".

Your issue is similar to #1334, where you will find [a workaround to fix it manual](https://github.com/thorchain/asgardex-electron/issues/1334#issuecomment-819803854). We've already started with the team to fix it in ASGARDEX desktop - sorry for the trouble!

**Comment by skyorion427** [comment]
https://thornode.thorchain.info/thorchain/tx/D5F057D28863849DB6EA3ECA74E3D144931D740B3B6E4EA243A616223155AEF6

THOR: https://viewblock.io/thorchain/address/thor1g489e8n3894paumdfntr06r3lzucln8srdfwjv

BNB txn: https://explorer.binance.org/tx/D5F057D28863849DB6EA3ECA74E3D144931D740B3B6E4EA243A616223155AEF6

According to tx history, You tried symm deposit for BNB pool but rune tx didn’t go out.
According to the memo ADD:BNB BNB:thor1g489e8n3894paumdfntr06r3lzucln8srdfwjv, Add tx is still in pending until RUNE is added symmetrically.
Potential Resolutions:
1. You should deposit rune with proper memo - ADD:BNB BNB:bnb1gzvnmk8auvmxj9fjz93qvqgf6w4q0swqksqvlq.
2. You should send withdraw tx.

Help wanted? Join discord (https://discord.gg/ZJHtzGJB)

**Comment by mastosis** [comment]
for clarity when you say I should deposit rune symmetrically  does that
mean i should add just Rune usd equivalent of what is pending in the BNB
pool??
Thus adding liquidity to the BNB pool but just adding Rune equivalent of
what is already in the pool i.e BNB??

Thanks for the asistance i know you guys are busy thanks for the support

Kind Regards

**Comment by veado** [comment]
> Thus adding liquidity to the BNB pool but just adding Rune equivalent of
what is already in the pool i.e BNB??

@mastosis Yes, but you do need to do it by adding RUNE asymmetrical to the BNB pool. An asymmetrical deposit is currently not supported in ASGARDEX desktop. However, there is [a workaround](https://github.com/thorchain/asgardex-electron/issues/1334#issuecomment-819803854) for doing it (similar to a asymmetrical deposit). Or just jump to https://discord.gg/ZJHtzGJB to get some support for doing that.

**Comment by mastosis** [comment]
Thanks Man
I have been able to sort it out

Cheers
