### ISSUE TITLE
missing BTC after ETH > BTC SWAP 

### ISSUE THREAD

**Issue by tzarebczan** [thorchain/asgardex-electron#1345]
I don't have the thorchain tx since I didn't take it down and it doesn't show in my history, but I have the ETH tx and ETH was moved. No BTC in my wallet. 

I would rather not share the ETH TX here, so please reach out to me on telegram: tzarebczan

**Comment by cbarraford** [comment]
@tzarebczan i saw your eth tx hash, and looked up your swap. Looks like you did a swap from ETH --> RUNE, NOT BTC. The following is your memo. The rune was sent to the thor address 

"SWAP:THOR.RUNE:thor1********************:"

**Comment by tzarebczan** [comment]
I sent the wrong tx, correct one was sent. Sorry about that!

**Comment by cbarraford** [comment]
@tzarebczan The swap failed due to `error	"fail swap, not enough fee"`. Try a larger trade, enough to pay for gas a couple times over.

**Comment by tzarebczan** [comment]
Thanks for the follow up! The UX should definitely be improved here now to allow smaller transactions that would cause tx issues on the outbound side. My inbound ETH transaction had costs fully covered, but I'll never know what the outbound costs are. It's probably a good idea to set this at some safe USD limit for each coin. 

Wish you all the best while you continue to work out the kinks, I'll be here in support!

**Comment by cbarraford** [comment]
Yup, this is def something to fix on the UI side, and something that is being worked on. Its only day 2 here, will need some time to iron out rough edges

**Comment by veado** [comment]
Fixed by #1367 + #1370
