### ISSUE TITLE
ADD: Swap screen

### ISSUE THREAD

**Issue by nomadnic** [thorchain/asgardex-electron#135]
### Design
https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=1285%3A149

### Components
![image](https://user-images.githubusercontent.com/41812729/88872127-dd4f3000-d25c-11ea-9e98-24df9494674e.png)

### Dark Mode

![image](https://user-images.githubusercontent.com/41812729/88872161-ed670f80-d25c-11ea-9f73-2aa26e05e31f.png)

Dependent on 
- [ ] #92 
- [ ] #126 
- [ ] #129 
- [ ] #130 
- [ ] #133

**Comment by thatStrangeGuyThorchain** [comment]
are we sure that such slider button is a good idea for desktop view ? its a good approach for mobiles but is it good for desktop?

**Comment by thorchain-admin** [comment]
I think it's fine and unique. User needs a definite action rather than Button + Confirm modal
