### ISSUE TITLE
SWAPED: RUNE-ETH, ETH transaction has 500+ confirms but doesn't show in Asgardex wallet

### ISSUE THREAD

**Issue by mimstephen** [thorchain/asgardex-electron#1350]
Hi, I Swapped RUNE for ETH earlier today, the transaction has 500+ confirms and etherscan shows the correct balance for my address. However asgardex does not see the transaction. For some reason this shows as an "Internal Txn" which Ive never seen when swapping.

https://etherscan.io/tx/0x834c4b8beb2138e03cb36a43dad2e027f124ecaa13fcb83b62e10c8f21703141

Thanks

**Comment by mimstephen** [comment]
If it helps I can be contacted on telegram @stephenmass

**Comment by veado** [comment]
> However asgardex does not see the transaction. For some reason this shows as an "Internal Txn" which Ive never seen when swapping.

What do you mean by this ^? Can't you see the transaction `Wallet` -> `History`?  Which version of ASGARDEX desktop are you using?

**Comment by mimstephen** [comment]
@veado I sent all the details to Kai over Telegram, ideally you guys pass it on internally for privacy reasons.

Thank you

**Comment by veado** [comment]
Team has identified that the issue seems to be on Ethplorer side (ASGARDEX desktop / web / THORSwap are all connected to Ethplorer using [xchain-ethereum](https://github.com/xchainjs/xchainjs-lib/tree/master/packages/xchain-ethereum) library). Ethplorer seems to ignore ETH received via internal transactions. The team has reported that issue to Ethplorer team to decide next steps.

**Comment by mimstephen** [comment]
Thank you for the help. I believe the issue can be resolved by sending another transaction through the non contract address, as I was able to use this to resolve my issue.

**Comment by Feedurhead-1** [comment]
I had Similar issues, but for me it was a swap(double-swap) from BUSD to Ether. The asgardex wallet doesnt update ether, bnb shows new balance ether remains the same.  

https://thorchain.net/#/txs/6DFED28FE4F2D03C118C41A8FE85D46A35BA7A70F6D4DB9D05690729B67CEABB

I even see balance on ether scan
https://etherscan.io/address/0xf2c51f7e784176f2ca0a982ea1d29c064a736aa2

Thinks, thought it would be better to add here than create a new bug. 

Cheers,

**Comment by kaiansaari** [comment]
The issue was raised with ethplorer directly but i've also submitted an issue: https://github.com/EverexIO/Ethplorer/issues/209

**Comment by mimstephen** [comment]
I actually just ran into the issue again. I was again able to resolve it by sending another 'normal' ETH transfer (which cost me way too much in fees at that time).

Anyway I'm glad this is a user fixable issue, hopefully it does get properly resolved soon though, the delays are the worst part.
