### ISSUE TITLE
Brute Forcing my Keystore.json

### ISSUE THREAD

**Issue by brettkimura** [thorchain/asgardex-electron#1351]
Im trying to use hashcat to brute force the keystore I lost due to an automatic windows upgrade right before i was able to save my seed and password (had it temp logged in notepad). Unfortunately, I wasnt able to recover notepad and had .82 BTC worth of RUNE and BTC.

Im trying to convert the keystore.json hash and salt into a format that I can pass into hashcat and need help with this.

## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

Looking for a format to pass into hashcat similar to this: https://hashcat.net/wiki/doku.php?id=example_hashes

## Current Behavior

every itteration i try has an exception and not a "fit"

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Context

Trying to brute force my password.

no

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by thorchain-admin** [comment]
Hi, ASGARDEX uses `xchain-crypto` https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-crypto

The passphrase is encrypted with a salted password. During decryption of the `keystore.cryptoStruct.cypherText` it is checked against the `keystore.cryptoStruct.mac`. The salt is stored in `keystore.cryptoStruct.kdfParams.salt`

You will need to reverse engineer this.

https://github.com/xchainjs/xchainjs-lib/blob/e96b0b3906fc3483fb8d846f1e4307f647e11237/packages/xchain-crypto/src/crypto.ts#L106

**Comment by brettkimura** [comment]
No idea how to do this, but think I have someone the can help. Any experience with Hashcat?

Thank you. Thorchain team is classy as always. 100% love this project.

**Comment by thorchain-admin** [comment]
From https://hashcat.net/wiki/doku.php?id=example_hashes

The ETH wallet option might work, it was lifted from that. 

```
15600 | Ethereum Wallet, PBKDF2-HMAC-SHA256
```

**Comment by brettkimura** [comment]
ahh i tried that, a hashcat dev is helping and said "Looks like the ciphertext is longer than the format we have, may incur some speed penalty in cracking but it should be possible. I need to modify the kernel to accept the new length and test it. Might be a bit more work than i had initially guessed but nothing ins"

**Comment by Chick3nman** [comment]
> 
> 
> From https://hashcat.net/wiki/doku.php?id=example_hashes
> 
> The ETH wallet option might work, it was lifted from that.
> 
> ```
> 15600 | Ethereum Wallet, PBKDF2-HMAC-SHA256
> ```

This is correct, the ethereum format modes we support work with xchain keystore files like the one used here, but the ciphertext for the ethereum format is always 32 bytes(64 hex characters) and in the thorchain test wallet i have CT is 78 bytes(156 hex characters) long. Should be just a matter of putting things in bigger buffers and making sure they are handled correctly if there's no other algorithmic differences.

**Comment by cT4493** [comment]
Hi @brettkimura have you been successful? I have the same problem and wanted to ask you for your learnings.
It is not possible to run hashcat on a mac? If not, can I take the keystore file on a othert machine where it is running?Many thanks!

**Comment by cT4493** [comment]
Hey Chick3nman, have you been successful? I am also trying to recover a Asgardex passphrase.
Many thanks for your answer :-)


> > From https://hashcat.net/wiki/doku.php?id=example_hashes
> > The ETH wallet option might work, it was lifted from that.
> > ```
> > 15600 | Ethereum Wallet, PBKDF2-HMAC-SHA256
> > ```
> 
> This is correct, the ethereum format modes we support work with xchain keystore files like the one used here, but the ciphertext for the ethereum format is always 32 bytes(64 hex characters) and in the thorchain test wallet i have CT is 78 bytes(156 hex characters) long. Should be just a matter of putting things in bigger buffers and making sure they are handled correctly if there's no other algorithmic differences.
