### ISSUE TITLE
Wrong 'ANALYTICS' link

### ISSUE THREAD

**Issue by SonyaDolmatova** [thorchain/asgardex-electron#1352]
![photo_2021-04-20_00-36-16](https://user-images.githubusercontent.com/74976410/115309319-c4810480-a174-11eb-928a-703d302551f4.jpg)

Change this link to runeyield.info please, because it opens link to bnb analytics

**Comment by veado** [comment]
@SonyaDolmatova Pls share urls for MCTN and MCCN we can use to link an user address. _I could not find anything for MCTN at runeyield.info or do I miss something ..._

**Comment by SonyaDolmatova** [comment]
> @SonyaDolmatova Pls share urls for MCTN and MCCN we can use to link an user address. _I could not find anything for MCTN at runeyield.info or do I miss something ..._

Not sure if MCTN is needed. What i meant was: This 'ANALYTICS' link opens analytics for Bepswap, for tracking Binance blockchain, but this is Asgardex, so it should open RUNEYIELD.INFO for tracking MCCN LPing.
