### ISSUE TITLE
Swap never passed pending

### ISSUE THREAD

**Issue by mimstephen** [thorchain/asgardex-electron#1357]
https://thorchain.net/#/txs/3FF22526CC63FC31A141F233797EC8B3837171F61F9B5DF0B174ACD94C71319E

**Comment by veado** [comment]
@mimstephen Pls share some more information:
(1) What's the asset you wanted to swap (RUNE -> ???)
(2) Did you use ASGARDEX desktop? If yes, which version?

**Comment by mimstephen** [comment]
Sorry, I figured that info would be available to you using the transaction ID. As the swap has now completed you can use the link I sent to check it out fully.

It was RUNE to USDT on t v0.1.0 of the desktop appimg.

Thank you,

**Comment by veado** [comment]
> As the swap has now completed ...

Nice to hear your tx has been completed! There were some issues by stucking ETH txs, which have been fixed now - see announcement at Telegram: [Stuck ETH Vault Post-mortem](https://t.me/thorchain_dev/31672)
