### ISSUE TITLE
Add Unlock wallet button everywhere, where it is necessary

### ISSUE THREAD

**Issue by TreefeedXavier** [thorchain/asgardex-electron#1359]
![image](https://user-images.githubusercontent.com/6923053/115712475-7d199480-a37d-11eb-8421-bec381653622.png)
Compare this two screens - on top one isn`t possible to step out to unlocking settings. Just minor change that brings a lot of comfort.

**Comment by veado** [comment]
#1361 will add buttons to import or unlock wallets in SwapView

## Unlock wallet

![Screenshot from 2021-04-22 18-39-41](https://user-images.githubusercontent.com/61792675/115752373-4e5de700-a39a-11eb-9795-44c453142ec1.png)

## Import wallet

![Screenshot from 2021-04-22 18-40-04](https://user-images.githubusercontent.com/61792675/115752432-60d82080-a39a-11eb-8902-84cc37ca19b5.png)
