### ISSUE TITLE
Prevent users from adding to liquidity pools and consequently paying high gas fees until caps are raised

### ISSUE THREAD

**Issue by keithagroves** [thorchain/asgardex-electron#1362]
Using the Asgardex electron app Version 0.1.0 (0.1.0), I was able to add liquidity. Thinking the caps were raised, as they are expected to, I first clicked the refresh button and then I added funds. This resulted in paying very high gas fees and losing funds. I was directed to this issue board by the thorswap support: https://www.blockchain.com/btc/address/bc1qlx35yyp379xawgjm6utk3k8nf8y2vtyrqkyvcw

## Prerequisites

These don't apply as I'm using the latest release and not building the project
- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

Users should be prevented from adding funds to pools until caps are raised to prevent lost funds. 

## Current Behavior

User is allowed to add liquidity to the pool and pays a very high fee for expecting the feature to work. 

## Possible Solution

An alternative solution might be to warn the user to proceed at their own risk. 

I'm not sure what endpoints are available to check the status of the caps, but that might be good place to start. 

## Steps to Reproduce (for bugs)

I am unable to reproduce. I don't understand why I was allowed to add funds this morning. I saw that the option was available and I refreshed several times in the event that it was a temporary glitch. 

## Your Environment

- Node version : 
- Version or Branch used :
- Operating System and version : Maxos
- Link to your project :

**Comment by veado** [comment]
Yesterday a changed was made for a value we used to calculate funds cap using https://thornode.thorchain.info/thorchain/mimir.
MAXLIQUIDITYRUNE -> MAXIMUMLIQUIDITYRUNE. With that, ASGARDEX desktop is showing `NO FUNDS CAP`, which is wrong and a bug. It will be fixed very soon with next release.

Pls note: An user will never lost funds by trying to add liquidity in this case, it will be always refundend by the system. BUT: Gas cost will be always wasted.

**Comment by keithagroves** [comment]
Please note: from my perspective, I indeed lost funds(~$300) due to this bug and I'm sure I'm not the only one.
