### ISSUE TITLE
BTCB Missing after adding to BTCB/RUNE pool

### ISSUE THREAD

**Issue by YVRTrader** [thorchain/asgardex-electron#1363]
Greetings...today I attempted to add .42 BTCB and the equivalanet RUNE into the BTCB/RUNE Pool.  The transaction went through but then the RUNE was refunded.  The BTCB of .42  has gone missing.   The wallet used was bnb1dcmwh8yxe3kdnlqxj99u5prmakpvw7nszvqwnv.  Attached are screenshots of the deposits from my BEPSWAP account into ASGARDEX.   Please help!!
![Screen Shot 2021-04-22 at 1 19 59 PM](https://user-images.githubusercontent.com/75958868/115813556-3b521380-a3a8-11eb-995a-0f04f2028b3b.png)
![Screen Shot 2021-04-22 at 1 24 32 PM](https://user-images.githubusercontent.com/75958868/115813578-43aa4e80-a3a8-11eb-84e8-0cdbf6e48e56.png)

**Comment by YVRTrader** [comment]
TX hash of missing BTCB  D1428DCF6127B7E6063D4E433C380879F5C5AAE1D736DAEE483A530668128F87

**Comment by veado** [comment]
FYI: _Your information has been forwarded to the team..._

**Comment by YVRTrader** [comment]
https://app.asgard.exchange/deposit-sym-recovery used this link provided by Jatin.....was able to recover BTCB

**Comment by YVRTrader** [comment]
Funds have been returned....issue is now closed.
