### ISSUE TITLE
"Address is invalid" in Asgardex desktop when sending BTC

### ISSUE THREAD

**Issue by leitaoalvaro** [thorchain/asgardex-electron#1368]
## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

 BTC addresses should be accepted
 Valid addresses should work fine

## Current Behavior

 Sending addresses to exchanges like Bittrex, Kraken, Binance, Coinex, Hotbit are read as invalid addresses by the interface. Funds are locked
 accepting valid addresses
![Invalid_Address _Asgardex](https://user-images.githubusercontent.com/50169503/115936664-7d885d00-a45b-11eb-8d28-de249b2b4814.jpeg)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by kaiansaari** [comment]
Please paste your address in text format for sanity check...

**Comment by kaiansaari** [comment]
This appears to be a result of mutating all addresses to lower case on `addressValidation()` which invalidates p2pkh & p2sh addresses which are Base58Check encoded & therefore case sensitive. (segwit addresses are not case sensitive).

https://github.com/thorchain/asgardex-electron/blob/94e21532b48787d9ee7d465d67c53e9e4c6245a5/src/renderer/components/wallet/txs/send/SendFormBTC.tsx#L217

**Comment by leitaoalvaro** [comment]
Hi Kai,

Thanks for checking the issue. The address I was using
is 3GtgD1HRdvwyygV6ChVvBifobSmUHkiUx6. But it does not work with any
address from Hotbit, Coinex, Binance, Kraken, and others...

**Comment by veado** [comment]
@kaiansaari Nice catch, thanks for checking it :+1: Fix is here #1371

@leitaoalvaro Fix #1371 will be published soon with next release. I've just tested it with addresses of Kraken and Binance, but It should work with addresses of any other exchanges as well.

**Comment by leitaoalvaro** [comment]
Thanks, guys! Appreciate your quick action!
