### ISSUE TITLE
Handling multiple wallets

### ISSUE THREAD

**Issue by D5Sammy** [thorchain/asgardex-electron#1383]
It could be interresting to add functionality in ASGARDEX to be able to handle multiple wallets.

Let's say I would like to have completely distinct wallet, 1 to manage my own daily transaction, 1 to manage a node, etc.

I could use two different computer, or probably go in Settings, Wallet management, and REMOVE the Wallet, and re-add the other one each time, but it would be tedious. 

I'm imagining a toggle/dropdown similar to Testnet/Charonet, but to switch between different distinct wallet.

Thanks :)

**Comment by veado** [comment]
@D5Sammy We have recently discussed in the team about a "multi-wallet" feature you have suggested here and we will think about how to implement it.

**Comment by veado** [comment]
Planned in #1571
