### ISSUE TITLE
Stuck Pending TX (LP)

### ISSUE THREAD

**Issue by AndyDufresneGitHub** [thorchain/asgardex-electron#1384]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
I sent 2 Symmetrical LP deposits (4 TX's total- 2 RUNE, 2 BTC) into the BTC:RUNE pool yesterday before the increased caps were reached. One of the transactions appears to be stuck in Pending.  This has led the deposits to be Asymmetrical.  Is there a way to either push this last TX through or, if not, what do I need to do to get it refunded? Does it matter that the deposit that did go through is now Asymmetrical and led to a rebalancing of the funds that did confirm? The TXID's in question are listed below.  Please let me know if you need any additional information.  Thank you very much for looking into this!

https://thornode.thorchain.info/thorchain/tx/88ABEC8908D2386F695F01F266EB8E79BBFC230FAB95C03B9FF023D7B9EA5C8A

https://thornode.thorchain.info/thorchain/tx/C94AFA3CDB6BCF2153DB2C0D8B9607F15F5BF89A46D65C8456430A04274B0BB6

https://thornode.thorchain.info/thorchain/tx/ba2e4745fb6e7d84eb898b318790dd11980c6c1e327197e66ad2f40cee24a05c

https://thornode.thorchain.info/thorchain/tx/D1C40B61FBF09196CEC7116F2E999EFB0B0676EFDE911372E9DBA2FE00F1B052 

This last one is pending if you look at my address on the list of LP's: https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers
"bc1qhagpvqptyx3t4e7kdq2cqcvtxatt99j38ury2d"

**Comment by cbarraford** [comment]
There is a known bug with this, where withdrawing your liquidity could cause you to lose your pending asset. So don't do that until the network upgrades to `0.49.0` (which will be soon). 

The best way to handle this at this time, is wait for that and withdraw all liquidity. Or wait until the caps are raised and send some more of the non-pending side in, which will commit the current pending

**Comment by AndyDufresneGitHub** [comment]
Thank you @cbarraford!  I will wait until the caps are raised again.  When this happens do I need to send an equal amount of Rune (non-pending asset) as the stuck BTC or will any amount of Rune push it through?  Thanks again!

**Comment by cbarraford** [comment]
any amount of rune will do, but I would recommend an equal amount of rune (dollar value) to the pending asset

**Comment by AndyDufresneGitHub** [comment]
Got it, thanks! One more question if you don't mind- Looking at my address history (https://thorchain.net/#/address/thor1r88y70cxrm4940kj7jzjggzc2nyvh4zacj707q) it looks like my two TX's got crisscrossed, as in the BTC from my smaller deposit got paired with the RUNE from my larger deposit (https://thorchain.net/#/txs/C94AFA3CDB6BCF2153DB2C0D8B9607F15F5BF89A46D65C8456430A04274B0BB6). As mentioned the BTC from my larger deposit is still pending, but I don't see the RUNE from my smaller deposit either. So once the caps are raised should I be depositing BTC and RUNE again?  Hope that makes sense- Thanks!

**Comment by cbarraford** [comment]
Im guessing that you attempt to add liquidity a second time before the first one was finished. Therefore, the rune from both adds got pushed into the same event, as the first btc add.

Once the caps are raised, add just the non-pending asset (sounds like rune in this case)

**Comment by AndyDufresneGitHub** [comment]
That makes perfect sense!  Thanks again!

**Comment by AndyDufresneGitHub** [comment]
Hi, again @cbarraford- Do you know is there any way to see the slippage that occurred with this deposit? Since I intended to do a symmetrical deposit my wallet showed me no slippage but since both my RUNE deposits were added to the same event as the one BTC deposit some slippage definitely occurred. I also imagine I will suffer some additional slippage once the pending funds clear. I understand why it happened, but am just looking to see exactly how much I lost due to the slippage and what my entry point is for the IL protection?  Any info is appreciated.  Thanks as always!

**Comment by AndyDufresneGitHub** [comment]
I don't want to just bother @cbarraford...Does anyone else know if it's possible to retroactively see the slip-based fee that was incurred for a asymmetrical deposit?  And also, how to determine the IL entry basis for an asymmetrical deposit? Thank you!

**Comment by AndyDufresneGitHub** [comment]
Based on this tweet- https://twitter.com/THORChain/status/1387230290976772098, I was hoping that after 7 days this was going to refund or be pushed through.  Am I misunderstanding this tweet? I'll still plan on depositing more RUNE once the caps are raised.  I was just hoping to get some clarification and closure for these funds stuck in limbo!  Since all my RUNE went through but not my BTC I was hoping I wouldn't have to get wrecked again in slippage fees.  Any info is appreciated as always!  Thank you!

**Comment by veado** [comment]
@AndyDufresneGitHub It seems you [don't have any pending assets in BTC pool](https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_provider/thor1r88y70cxrm4940kj7jzjggzc2nyvh4zacj707q), right?
