### ISSUE TITLE
Remove/Import different wallet shows old balance

### ISSUE THREAD

**Issue by airfrank** [thorchain/asgardex-electron#1386]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [x] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

After importing the other wallet, it should show the actual one. I need to refresh balance to see it.

## Current Behavior

After importing the other wallet, balance of previous is shown.

## Possible Solution

Auto refresh after import.

## Steps to Reproduce (for bugs)

1. Import wallet with seed

2. Remove wallet

3. Import other wallet with seed

4. Show balance

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version : Win 7 v0.1.0
- Link to your project :

**Comment by veado** [comment]
Duplicated by #1358
