### ISSUE TITLE
ETH transaction complete on Etherscan but not in wallet (v0.1.0)

### ISSUE THREAD

**Issue by simon852** [thorchain/asgardex-electron#1389]
Using v0.1.0 on Ubuntu and have made multiple successful deposits. In particular 4 ETH deposits that all show on Etherscan but only three in the wallet. The missing transaction is ~4 hours old and has more than 1000 confirmations, its listed in Etherscan as "Internal Txns" whereas the other 3 (that show in asgardex) are listed simply as "Transactions".

**Comment by simon852** [comment]
The transaction now appears in the asgardex wallet. Edited the original issue to remove the wallet address.

**Comment by veado** [comment]
Ethplorer has still some issues, see **BUG: Ethplorer API reports incorrect eth balance #209** https://github.com/EverexIO/Ethplorer/issues/209

**Comment by veado** [comment]
History for ETH balances will be fixed by #1465

_Closing this issue here for now... If you have still issues / questions, feel free to re-open it again or create another issue. Thx!_
