### ISSUE TITLE
How to join a liquidity pool?

### ISSUE THREAD

**Issue by SovereignKaizen** [thorchain/asgardex-electron#1395]
I transferred some ETH into my wallet on Asgardex.  It's there.  Is it now part of the liquidity pool?  Do I have to do something else?

**Comment by veado** [comment]
First of all you need to understand what [being a Liquidity Provider means](https://docs.thorchain.org/roles/liquidity-providers). With that in mind, go to `Pools` -> `ETH pool` -> `Manage` to deposit ETH. 

If you want to use ASGARDEX desktop, please wait for next release, which will be available within next days. Current release still has some know issues to add liquidity. If you don't want to wait, you can use web based applications such as https://app.asgard.exchange or https://app.asgard.exchange.
