### ISSUE TITLE
Can't convert ERC200 Rune to Native Rune

### ISSUE THREAD

**Issue by LaelLeeH** [thorchain/asgardex-electron#1397]
Hi,
My wallet shows I have 5 ERC20 Rune that need converting to Native Rune
![image](https://user-images.githubusercontent.com/81672712/117118813-877e5a00-ad91-11eb-8caf-55d7a2653e99.png)

I don't think this next pic is correct. It shows my 5 Rune twice in my Eth account, and  I'm sure it should only show once, but I might be wrong???
![image](https://user-images.githubusercontent.com/81672712/117118918-a7ae1900-ad91-11eb-8ee9-673d071ef3bb.png)

Then when I select either of them and click next to convert, I get this following message and it just hangs. 
Message : "This RUNE is currently a ETH token. By clicking the button below, you will be upgrading it off of the ETH chain to native RUNE. Your native RUNE will show up in your RUNE wallet in user settings."
The blue circle just rotates - I never get any button to select.

![image](https://user-images.githubusercontent.com/81672712/117118991-c1e7f700-ad91-11eb-9ae8-9482e72c84e8.png)

Not sure if these screenshots are uploading - I hope so. Please help?

**Comment by veado** [comment]
@ LaelLeeH This issue is related to https://github.com/asgardex/asgard-exchange, pls open an issue there, thx!
