### ISSUE TITLE
Insufficient funds when adding to ETH pool and now ETH lost

### ISSUE THREAD

**Issue by arnigudj** [thorchain/asgardex-electron#1398]
## Prerequisites

Using [Asgardex v0.1.0](https://github.com/thorchain/asgardex-electron/releases/tag/v0.1.0)  on macOS Catalina version 10.15.7.

## Expected Behavior

I've deposited ETH to my wallet that Asgardex generated for me (worked)
I swapped some Ether for RUNE (worked)
I then wanted to add ETH and RUNE to the pool and what should have happened is that I should get my shares.

## Current Behavior

![image](https://user-images.githubusercontent.com/3431883/117141762-72f48e80-ad9e-11eb-9aa4-97afbf22a442.png)

I dragged the slider to 100% and "drag to deposit"

A popup appeared and it started the ETH transaction but then I got an Insufficient Funds error. 

Now my ETH is gone from my wallet (see transaction https://etherscan.io/tx/0xb2011ecb5d088b6953d5f400b3d7f08fcffb9879f351e1b25433e6d3f00f2a97) and I got no shares! 

How do I get the ETH back or shares?

## Possible Solution

Return ETH or shares.

## Steps to Reproduce (for bugs)

1. deposit ETH
2. Swap part for RUNE
3. go to "manage" in the ETH pool
4. in ADD tab move the slider to 100%
5. Drag to deposit

Get the insufficient funds error and panic

## Context

I've lost money and I don't know if I trust the protocol any more. 

I've made no changes to the Asgardex, I used the binary install of macOS

## Your Environment

Using [Asgardex v0.1.0](https://github.com/thorchain/asgardex-electron/releases/tag/v0.1.0)  on macOS Catalina version 10.15.7.

**Comment by arnigudj** [comment]
Hi @kaiansaari , can you help me out?

**Comment by kaiansaari** [comment]
https://thornode.thorchain.info/thorchain/pool/ETH.ETH/liquidity_provider/thor1fzrgv2ck4f0fkxw86cery8hr3vtpvce9wg69ue

I can see the RUNE side is pending, you can use thorswap.finance to complete this. Discussing on telegram.

No funds are lost.

**Comment by arnigudj** [comment]
Yes no funds where lost, this was completely my fault not understanding what I was doing. I got the ETH back.  🤪
