### ISSUE TITLE
30% less Total Value than was transferred to wallet and swapped

### ISSUE THREAD

**Issue by janirthorndike** [thorchain/asgardex-electron#1405]
I Transferred .213 BTC to Asgardex wallet on Asgardex desktop app, and swapped for Rune, then added liquidity to BTC pool, but only 70% of the transferred BTC showed up as Total Value, 0.16 BTC. there are nominal funds still in the wallet, but nothing close to 30%. Can this much value be lost immediately to slippage and transactions? I'm confused by the transaction history created, so I've attached  screenshots of that screen that shows addresses, SELF transactions, etc., as well as screenshots of current pool value.

BTC Wallet: bc1qngtsx79hx5n5znug2p95x9h54pn95xet8249y5
Rune Wallet: thor16ul92altkaa8j4hyzegv99ywurgttgxhe4rp6x

https://www.blockchain.com/btc/address/bc1qngtsx79hx5n5znug2p95x9h54pn95xet8249y5

![Screen Shot 2021-05-06 at 5 19 20 PM](https://user-images.githubusercontent.com/32255149/117393328-9a775400-ae8f-11eb-8c04-4c363f288c98.png)
![Screen Shot 2021-05-06 at 5 19 37 PM](https://user-images.githubusercontent.com/32255149/117393332-9f3c0800-ae8f-11eb-9615-ba5345576f4e.png)
![Screen Shot 2021-05-06 at 5 20 32 PM](https://user-images.githubusercontent.com/32255149/117393344-a2cf8f00-ae8f-11eb-8ebd-da8040de10f9.png)
![Screen Shot 2021-05-06 at 5 20 52 PM](https://user-images.githubusercontent.com/32255149/117393354-a6fbac80-ae8f-11eb-8034-30018966f143.png)

**Comment by kaiansaari** [comment]
https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_provider/thor16ul92altkaa8j4hyzegv99ywurgttgxhe4rp6x

`{
	"asset": "BTC.BTC",
	"rune_address": "thor16ul92altkaa8j4hyzegv99ywurgttgxhe4rp6x",
	"asset_address": "bc1qngtsx79hx5n5znug2p95x9h54pn95xet8249y5",
	"last_add_height": 401652,
	"units": "29755765569",
	"pending_rune": "0",
	"pending_asset": "4691438",
	"pending_tx_Id": "81BD5F2F7D568D808F7C240326A0B75027979386653EC1F634431E9D05A09757",
	"rune_deposit_value": "23909573236",
	"asset_deposit_value": "7630178"
}`

You have pending liquidity and need to send the RUNE for this symmetrical deposit; or withdraw the btc and start again. It's likely the RUNE tx failed.

Export your wallet keystore and import it into https://thorswap.finance. Follow these instructions:
![image](https://user-images.githubusercontent.com/26814804/117457605-b9a7db80-af8c-11eb-9727-2922702c98b4.png)

For more support join this discord: https://discord.gg/kcf7bAKF

**Comment by janirthorndike** [comment]
Where do I see my pending asset, and how do I withdraw it? I don't see it in my wallet or elsewhere. 
I did have a pending asset deposit of ETH, so I hope that's not what you're referring to. That showed up today. Is it pending BTC you're talking about? Do you still see it as pending? It's 0.053 BTC that I'm trying to account for (before slip & transaction cost)
By the way, I originally submitted a ticket on that discord, but was referred here since I did all this on Asgardex desktop app. It was Ticket 40 on Thorswap discord

**Comment by janirthorndike** [comment]
ok, on thorswap.finance, I withdrew from pending asset (i think) here is the transaction, cost 0.02 Rune
https://blockstream.info/tx/86E38F16A4C9EEB952C9D7D97866FFF8BFF6E62370FC42E08F020811AD535351
But it still says pending? 8 confirmations as I write this.

So I'm still confused. I now see 0.082 BTC and 252.7 Rune in my wallet, No liquidity in pool anymore, and still a Pending deposit of 0.0469 BTC: https://blockstream.info/tx/81BD5F2F7D568D808F7C240326A0B75027979386653EC1F634431E9D05A09757
Can you explain further?
