### ISSUE TITLE
Added 2BNB into liquidity and only get 1.29BNB and 0.7 BNB got lost

### ISSUE THREAD

**Issue by Michaglio** [thorchain/asgardex-electron#1410]
Hello MASTER THOR!
added 1BNB & 1BNB (total 2) into bnb1tqas9l4r6f9n4vx9rm86aev7kfvv4wczefcuu2

however only 1.29 BNB got added into Liquidity 
this is runyield addresss
https://app.runeyield.info/dashboard?thor=thor1tp43l33zzsp6cu5gunar7588p3tuyzyksl7d22

the 0.7 BNB got missing and was sent to the same address for liquidity but does not show *(waited around 5 days)* 
https://binance.mintscan.io/account/bnb1tqas9l4r6f9n4vx9rm86aev7kfvv4wczefcuu2

Not sure if that is a big or funds went missing
Love your project guys. Lots of love

**Comment by veado** [comment]
@Michaglio If you go to https://thorchain.tools/ to enter your THORChain address `thor1tp43l33zzsp6cu5gunar7588p3tuyzyksl7d22`, you will see your pending BNB amounts. Same result by checking [pool/BNB.BNB/liquidity_provider](https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_provider/thor1r88y70cxrm4940kj7jzjggzc2nyvh4zacj707q) endpoint. 

One way to get it back: Go to https://app.thorswap.finance/pending and import your wallet. Then add some RUNE to trigger a deposit again OR withdraw the value of your pending assets (BNB in this case). For more questions about recovering your asset there, go to Discord channel of THORSwap.
