### ISSUE TITLE
Bepwap chaosnet down for maintenance?

### ISSUE THREAD

**Issue by CryptoJoe69** [thorchain/asgardex-electron#1416]
How long is Bepswap going to be down for maintenance? I use Trust wallet to access Bepswap and have no access to my account except through the Bepswap website so curious how long site will be down and when we will be able to trade again.
Lastly, I provided liquidity to an Injective protocol LP and it was showing up in the total on my wallet summary but never showed up on the Bepswap website summary even 48 hours later.

**Comment by veado** [comment]
@CryptoJoe69 There is no ETA, but you can expect it will be fixed soon. The team is working hard to fix issues they have discovered yesterday. You can get more information about it at the dev Telegram channel https://t.me/thorchain_dev

**Comment by veado** [comment]
chaosnet.bepswap.com just came back to "normal" (no maintenance anymore)
