### ISSUE TITLE
eth locked in a pool after failed transaction

### ISSUE THREAD

**Issue by brunojanvier77** [thorchain/asgardex-electron#1421]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
Please help, I have a bit of ETH locked.
Tx: https://etherscan.io/tx/0x14f95f9593118b47c70ea5d36dd8c490bb6572f37fc3e3ccd174f500cac32d45

Thanks in advance.

**Comment by veado** [comment]
@brunojanvier77 It looks like you have tried to  If you got to https://thorchain.tools/ to enter your THORChain address `thor162r62wymneyycvkqjvq9u7z2y4dj2exzl4szqg`, you will see pending your pending ETH asset. Same result by checking [pool/ETH.ETH/liquidity_provider](https://thornode.thorchain.info/thorchain/pool/ETH.ETH/liquidity_provider/thor162r62wymneyycvkqjvq9u7z2y4dj2exzl4szqg) endpoint. 

One way to get it back: Go to https://app.thorswap.finance/pending and import your wallet. Then you add some RUNE to trigger deposit again OR withdraw your pending value. For more questions about to recover your asset there, go to Discord channel of Thorswap.
