### ISSUE TITLE
BUSD -> ETH swap incorrect output (after tx fee's)

### ISSUE THREAD

**Issue by 0xLuc** [thorchain/asgardex-electron#1431]
User recently swapped 172$ BUSD to ~0.00168 ETH (~6$) while paying 66$ in ETH gas fee (280 gwei). 

**Transaction**: https://swapalyzer.ofthor.com/swap/D893F9017F51F4D1AD5135551BE1E6EFD81ECC4CDA5E264E1E95C0458015CFDC

After paying the transaction fee's the user should have gotten around 100$ worth of eth, but instead only got 6$.

Application: Asgardex desktop
Platform:  MAC

**Comment by veado** [comment]
@0xLuc Thanks for this bug report, it sounds very similar to #1432. I've just reached out to the (backend) team to get more information why are such differences.

**Comment by veado** [comment]
@0xLuc Which version on ASGARDEX desktop dis you use for your swap BUSD -> ETH ^?

**Comment by 0xLuc** [comment]
Alee used V 0.1.0 to make the swap

**Comment by veado** [comment]
Ok. Pls make sure to use[ latest `0.2.0`](https://github.com/thorchain/asgardex-electron/releases/tag/v0.2.0), which have already an update for fee handling included.
