### ISSUE TITLE
Incorrect Fees

### ISSUE THREAD

**Issue by CryptoGlutton** [thorchain/asgardex-electron#1432]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
I went to swap RUNE for ETH last night (051321) and I ended up with MUCH less ETH than I was told I was going to get for my RUNE. The first swap was 34 RUNE for ETH at 19:39 MST. Was shown I should expect to receive ~0.16ETH with an Eth fee of ~0.011 and RUNE fee of 0.1. When the transaction was processed, the history said I had swapped 34 RUNE for just 0.1188 ETH. 

I checked the Etherscan Transaction Hash (0x2d092c9a7af1df0c7cb5f78feba01be98d25cf03db72dca6a86fec34ec3786d4) and it showed a transaction fee of only 0.00854876 ETH (~$32). 

So I did another transaction to make sure I wasn’t missing anything as far as the fees that I should expect. Second transaction was selling 20 RUNE for ETH. The swap page told me I’d get a little over 0.09ETH and the fees at the bottom were 0.1 RUNE and again, 0.011ETH. When the transaction went through I was given only 0.055ETH. 

Again I checked the Etherscan Transaction Hash (0xde02001d2ac04718ab77552bea8e50d386ffdd7c71aff3a12bfe82fe308450af) and it only showed a transaction fee of 0.00854612 ETH (~$32). 

At the time of these trades RUNE was ~$17.63 and ETH was ~$3880 on CoinGecko, but your oracle price was almost $100 lower than that. I don't know what's up, but I just lost 33% of the value of my asset and can't find any transaction data to validate that. 

My ETH wallet is: 0xc660b7592e12d4785c89c8f34beeadd8ca830c71
My RUNE wallet is: thor16wk5xwrzljr7r6e6xc3a3cmjp3mfentnu8upf8

I understand this just may be a case of me not looking in the right place for total fees, and I also understand gas fees are extraordinarily high around Ethereum, but it seems like I got taken for a ride. The options you provide me in the transaction history for reviewing what I've done only show me total fees of $65 worth of ETH, NOT $300. Where is the documentation showing me where the rest of my ETH went? Hoping you all can help.

**Comment by veado** [comment]
@CryptoGlutton Thanks for you detailed report! 

Which version o ASGARDEX desktop have you used?

Currently calculation of fees to swap RUNE -> ETH are calculated as follow: 

1. Inbound fee to send RUNE IN: 0.02 RUNE
2. Outbound fee to bring ETH OUT: 3 * gasRate (in GWEI, we got from [inbound_addresses](https://thornode.thorchain.info/thorchain/inbound_addresses)) * 35000 (units == tx size) (for now it would be `0,01365 ETH`)

For your swap:
1. Inbound fee: 0.02 RUNE (no change)
2. Outbound fee: Based on formula above and current `gas_rage: 130` provided in [inbound_addresses](https://thornode.thorchain.info/thorchain/inbound_addresses)) it would be `0,01365 ETH`, which is very similar what you got before.

The fees are deducted from your output are not based on fees you see at Etherscan, but as you can see in ASGARDEX ui. 

The only source we currently have for this calculation is https://github.com/thorchain/asgardex-electron/issues/1381

Based on your data (just to double check):
1. First swap: 34 RUNE IN -> 0.1188 ETH OUT= 599.42$ IN -> 460.94$ OUT = 138.48$ fees)
   - Fees in UI: 0.02 RUNE + 0.011 ETH = $0.3526 + $42.68 = 43.0326
   - Difference: $138.48 - $43.0326 = $95.44

2. First swap: 20 RUNE IN -> 0.055 ETH OUT (similar to $352.6 IN -> $213.4 OUT = $139.2 fees)
   - Fees in UI: 0.02 RUNE + 0.011 ETH = $0.3526  + $42.68 = $43.03
   - Difference: $139.2 - $43.03 = $96.16

> Where is the documentation showing me where the rest of my ETH went? 

We don't have an official documentation for that right now. For developers https://github.com/thorchain/asgardex-electron/issues/1381 is a source to follow. 

Let me reach out to the team to check why these differences between calculated in UI and "real" fees after swap.

**Comment by CryptoGlutton** [comment]
Using v0.1.0. 

REALLY appreciate you finally picking this up and running with it. Please let me know if there is any other information I can provide which would help you all figure this out. - CG

**Comment by veado** [comment]
_Still waiting for a feedback from backend team..._ At the meantime, pls make sure to [use latest ASGDARDEX 0.2.0](thor1tp43l33zzsp6cu5gunar7588p3tuyzyksl7d22)

**Comment by CryptoGlutton** [comment]
Wasn't even aware there was a new version. I'll get right on it. Thanks. - CG

**Comment by CryptoGlutton** [comment]
Veado, any feedback from the backend team?!? I received a message from the ThorChain Twitter account that basically told me, "you pay three times what the node pays. So if you see $65 was spent then you were charged $195." Now, this may be true, but to be clear, there is NOTHING on Asdardex, or at least not when I went to make the two transactions described earlier, that in any way, shape or form makes it clear, or even SUGGESTS, that the ETH fee being shown at the bottom of the swap page is just 1/3 of the REAL fee that will be charged. I think you'll agree with me on that.

Additionally, if this IS true about 3x fees, then again, I want to see the transaction record. No tax man in the world is going to accept me just telling them that Thorchain has other fees that you can't see and that's why I only received $600 worth of ETH for $900 worth of RUNE and the Etherscan transactions are just wrong. That's just not going to fly. Again, I think/hope you understand that. 

Hoping you continue to work on this and we can get this issue resolved. Again, let me know if there is anything else you need from me. Thanks. - CG

**Comment by veado** [comment]
> Veado, any feedback from the backend team?!?

It still an going discussion. You can follow it on Discord (it's public):

- Message in #mccn channel:  https://discord.com/channels/838986635756044328/839002619481554955/843852866149679105
- Message in #asgardex-desktop channel: https://discord.com/channels/838986635756044328/839002220942721024/844904929423654952

**Comment by CryptoGlutton** [comment]
Not real familiar with Discord. I'm on there, but when I clicked those links I just end up on a blank page that tells me there is either no channels there or I'm not allowed on them. I'll try and figure it out later. In the meantime, if anything MAJOR comes out of the discussion I'd appreciate you letting me know here. Thanks again for your help. - CG

**Comment by veado** [comment]
@CryptoGlutton The team has just realized, my previous calculation example by using your data was wrong. It includes a wrong `gas_rate: 130`, which was `330` on the day of your trade (see [`gas_rate` of ETH here](https://thornode.thorchain.info/thorchain/inbound_addresses?height=518314)). With that, result of calculation example is about `$142`, which is very similar to what you have paid. 

By using latest [`0.2.0` of ASGARDEX](https://github.com/thorchain/asgardex-electron/issues/thor1tp43l33zzsp6cu5gunar7588p3tuyzyksl7d22) fees should be fine.

_Closing issue now ..._

**Comment by CryptoGlutton** [comment]
This issue is NOT closed. Telling me that there were some hidden gas fees that I didn't know about and that ultimately led to me losing 1/3 of my investment is not a "solution" to my problem. If there were gas fees that high AND I was charged higher fees than Asgardex told me I'd be paying, then I WANT TO SEE A RECORD OF THESE TRANSACTIONS. Just send me the hash. Give me something I can show my tax man. If I don't see the evidence from you all in regard to where my money went then I expect some RUNE or ETH to end up in my Asgardex wallet(s). If I don't, I'm going to be a PR nightmare for you folks. I'm tired of getting the run-around on this, and being treated like it was MY FAULT. Your site provided faulty data and you should be accountable for that.

**Comment by veado** [comment]
@CryptoGlutton Closing an issue does not mean it's your fault and I'm very sorry to hear, there is a lost for you. Unfortunately I can't do anything for you from now, we have checked the issue and noticed, it was already been fixed by latest version `0.2.0`. However, I will forward your last message ^ to the team again. Also you can reach out to the THORChain Telegram channel to get more support on this https://t.me/thorchain_org

**Comment by kaiansaari** [comment]
> This issue is NOT closed. Telling me that there were some hidden gas fees that I didn't know about and that ultimately led to me losing 1/3 of my investment is not a "solution" to my problem. If there were gas fees that high AND I was charged higher fees than Asgardex told me I'd be paying, then I WANT TO SEE A RECORD OF THESE TRANSACTIONS. Just send me the hash. Give me something I can show my tax man. If I don't see the evidence from you all in regard to where my money went then I expect some RUNE or ETH to end up in my Asgardex wallet(s). If I don't, I'm going to be a PR nightmare for you folks. I'm tired of getting the run-around on this, and being treated like it was MY FAULT. Your site provided faulty data and you should be accountable for that.

Hi CG, 

THORChain is a permissionless network operated by anonymous node operators. None of the contributors to the protocol or interfaces operate the network. The interfaces are entry points to the system and are in different states of development - users have choice on which interface they use.

You will not be refunded for this transaction for the following reasons:

1. THORChain is designated #chaosnet - expect chaos. There are multiple warnings to users that THORChain is embryonic technology and subject to risk. When you interact with the network you accept the risks, which have been outlined here: https://medium.com/thorchain/thorchain-chaosnet-risk-outline-c16db4b78df7

2. No significant defect has occurred - the fee estimate was incorrect, but it could still be incorrect with the fix veado has applied because fees can fluctuate wildly on ethereum. This could have simply changed while your transaction was being processed. It is *ONLY* an estimate. There was no "faulty data" as you put it. You should educate yourself on how fees work on THORChain and act accordingly.

3. Your threats to veado to create trouble for the network is unacceptable. This is now how you negotiate and will not be tolerated.

The data you seek is here:

https://etherscan.io/tx/0x2d092c9a7af1df0c7cb5f78feba01be98d25cf03db72dca6a86fec34ec3786d4

https://midgard.thorchain.info/v2/actions?txid=2d092c9a7af1df0c7cb5f78feba01be98d25cf03db72dca6a86fec34ec3786d4&offset=0&limit=50

https://thornode.thorchain.info/thorchain/tx/2d092c9a7af1df0c7cb5f78feba01be98d25cf03db72dca6a86fec34ec3786d4


If you wish to discuss further I offer my telegram ID for your convenience. Github is not the place. @kkkilo

**Comment by CryptoGlutton** [comment]
Yeah, I'm gonna hit you up on Telegram, because that's going to make a difference?!? Pretty clear where you all stand. 

I'm just going to chalk it up as another $250 mistake, walk away, and do my best to warn people about wildly fluctuating gas fees that skyrocket 3-4 times in mere minutes (behind the scenes) and also all the chaos and risk associated with your site that you yourself just mentioned. That's not a threat, it's a necessary task one much carry out, if they care about the well being of other people, and want to protect the crypto space from bad actors. People have a right to know when there is a high likelihood that they're likely to get taken to the cleaners on a given site or by a given project. See you all on Twitter.
