### ISSUE TITLE
Cant change ERC20 Rune to Native Rune

### ISSUE THREAD

**Issue by onurocalan** [thorchain/asgardex-electron#1434]
Hi Everyone,

Today when i tried to change erc20 to native, i received an error and tried many times. 

I have enough ETH in my wallet too and here is the address : 0x9fe00cf0856ad3f08e8b88c0a8f3397478b4a71a

What i realized that, if you use floating number like 6.3 Rune to change it to native rune, it will give an issue. But if you use direct number like 6 , transcation is getting complete.

Can you please have a look at the issue? Thanks in advance

**Comment by onurocalan** [comment]
one update:  if you write down the number manually , it is fine but the bar you swipe it to right to choose %100 , it gives an error.

**Comment by veado** [comment]
@onurocalan Could you share some more details, pls? 

(1) Which version of ASGARDEX are you using?
(2) Where did you tried to switch Rune ERC20 -> Rune Native? ASGARDEX desktop does not support it.

**Comment by veado** [comment]
@onurocalan As [mentioned before](https://github.com/thorchain/asgardex-electron/issues/1434#issuecomment-842265033), ASGARDEX desktop currently does not support switch Rune ERC20 -> Rune Native. _And still waiting for your feedback... Closing this issue for now._
