### ISSUE TITLE
How do I get my BTC private key from my keystore file?

### ISSUE THREAD

**Issue by patoshii** [thorchain/asgardex-electron#1441]
When sending BTC from my mobile wallet to asgardex, I'm assuming it gets sent to the asgardex btc wallet which I control before making any trades on thorchain. How do I get my BTC private key?

**Comment by veado** [comment]
One way is to use a tool such as https://iancoleman.io/bip39, where you can enter your phrase (make sure you have `Coin` `BTC`selected) to get your private key. **Don't** use it online, it's recommended to download its originally source code https://github.com/iancoleman/bip39/releases/latest/ to run it offline in your browser.
