### ISSUE TITLE
Release signatures

### ISSUE THREAD

**Issue by j3ko** [thorchain/asgardex-electron#1442]
Is there some place I can find a SHA hash or PGP signature of the latest release?  I'm getting warnings from my browser and it would be nice to be able to verify before I install anything.

**Comment by veado** [comment]
Done https://github.com/thorchain/asgardex-electron/releases/tag/v0.2.0

How to verify release hashes: https://github.com/thorchain/Resources/blob/master/admin-GPG-keys.md

**Comment by j3ko** [comment]
Nice!  It might be useful to publish those pgp keys to some keyservers for people to lookup in the future.

**Comment by Mansarde** [comment]
Where actually are the keys? I searched here on Github, on multiple pgp key servers and Google. Didn't find anything. :\

**Comment by veado** [comment]
> Where actually are the keys? I searched here on Github, on multiple pgp key servers and Google. Didn't find anything. :\

https://github.com/thorchain/Resources/blob/master/admin-GPG-keys.md#trusted-keys

**Comment by veado** [comment]
> Nice! It might be useful to publish those pgp keys to some keyservers for people to lookup in the future.

I've just uploaded one key we have published in https://github.com/thorchain/Resources/blob/master/admin-GPG-keys.md#trusted-keys to  keys.openpgp.org (another key will be uploaded soon)
```
gpg --keyserver hkps://keys.openpgp.org/ --search-keys 0F1342110E1A10DCAFA7194DABB32D7C24F80F1D   2 ↵
gpg: data source: https://keys.openpgp.org:443
(1)	  4096 bit RSA key ABB32D7C24F80F1D, created: 2020-04-21
Keys 1-1 of 1 for "0F1342110E1A10DCAFA7194DABB32D7C24F80F1D". 
```

**Comment by Mansarde** [comment]
@veado The link you posted (right after my initial comment) only contains the fingerprints, but not the actual keys themselves.
But thanks for uploading them to keys.openpgp.org in the meantime, was able to get them from there.
Thx! 👍

**Comment by Mansarde** [comment]
@veado I spoke to soon.
Although I was able to download the .asc files, I can't get them imported.
If I issue `gpg --import 9A6461A8CAAAA0AEB8EFDDA8C5334FE4FD04D709.asc` it responds with:
```
gpg: key C5334FE4FD04D709: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

If I try to issue `gpg --recv-keys --keyserver hkps://keys.openpgp.org/ C5334FE4FD04D709` it says the same.
Same goes for the other key (`ABB32D7C24F80F1D`).

Am I doing something monumentally wrong? 🤔
I have imported keys like this in the past and it always worked.

**Comment by Mansarde** [comment]
@veado Did you have a chance to look over my latest post yet?
If it doesn't work with the key servers, then could you maybe add the keys to Github?
That'd be super nice! 😁

**Comment by veado** [comment]
@Mansarde Sorry about the late answer, just uploaded my key to https://keys.openpgp.org again, it should be available from now there.

![Screenshot from 2021-06-15 15-59-24](https://user-images.githubusercontent.com/61792675/122066748-4b5c0180-cdf3-11eb-9f70-39cc7738c3f8.png)

**Comment by Mansarde** [comment]
@veado No worries, mate. :)
Just tried to import the key and and it worked this time!
The other one (9A6461A8CAAAA0AEB8EFDDA8C5334FE4FD04D709) still doesn't work as it's missing the user id.
But it seems we only need the new one you uploaded to verify the releases.

Thx a lot, much appreciated! 😁

**Comment by Mansarde** [comment]
@veado Ok, so GPG can now recognize that the release signature was created by you, but it reports the signature as invalid.
Excluding manipulation by a third party, I assume that might be because some character in the signature might've been escaped due to posting it as text directly in the release page.

If I may offer a suggestion to solve this:
Maybe you could add the signature as an .asc file together with the other files instead.
This would prevent any inadvertent changes of the signature (due to Github escaping certain characters etc.) and would also declutter the release page.

**Comment by veado** [comment]
> Maybe you could add the signature as an .asc file together with the other files instead.

@Mansarde Done (see https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.4)

**Comment by Mansarde** [comment]
@veado Signature check works without any problem for me now. 👍
Thank you very much!
And sorry for all the hassle, can't be too careful. ^^

**Comment by veado** [comment]
@Mansarde / @j3ko  Thanks for all your feedback! It helps us to make ASGARDEX better and better. Such kind of feedback is always appreciated!

**Comment by toffoo** [comment]
@veado please publish your public keys more prominently.  it took me over an hour of searching to find this obscure closed thread to find somewhere to locate your public key.

**Comment by veado** [comment]
@toffoo Each releases notes have a message `msg` includes, which includes a link to https://github.com/thorchain/Resources/blob/master/admin-GPG-keys.md where you can find public keys. However, I will highlight this link within next release notes.

**Comment by veado** [comment]
@toffoo Just noticed you have already updated ` https://github.com/thorchain/Resources` with more helpful information https://github.com/thorchain/Resources/pull/19 - thx!
