### ISSUE TITLE
On Initial Setup, ASGARDEX Public Key for BCH - ERROR. Invalid. How can this be fixed?

### ISSUE THREAD

**Issue by timajor67** [thorchain/asgardex-electron#1443]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>

**Comment by veado** [comment]
@timajor67 Could you some more details, pls? Which ASGARDEX desktop version, which OS, what's the error in detail, share screen shot if possible...

**Comment by thatStrangeGuyThorchain** [comment]
hey @timajor67. really strange issue and we need more details...
actually i've tried to run an application from a scratch with virtual box with win10 image installed and have not faced any issues there

**Comment by veado** [comment]
@timajor67 Pls let us know about if you still have any issues. _Closing this issue for now ..._
