### ISSUE TITLE
USDC showing incorrect value in wallet

### ISSUE THREAD

**Issue by nickokgo** [thorchain/asgardex-electron#1451]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

See the image below. I only have 1 USDC in my wallet yet it shows its value as $100.
![image](https://user-images.githubusercontent.com/18488428/119536712-6341e780-bd57-11eb-8510-5316cb913781.png)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by veado** [comment]
@nickokgo What's the version of ASGARDEX desktop are you using?

**Comment by nickokgo** [comment]
Hey, it was pre-version 2. I'll let you know if I see something similar in v2.

**Comment by veado** [comment]
Just FYI: Issue has been fixed in #1458 and will be available with next release `0.2.2`
