### ISSUE TITLE
Pending transaction to pool

### ISSUE THREAD

**Issue by plato50** [thorchain/asgardex-electron#1453]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by plato50** [comment]
I tried to add liquidity to bnb/rune pool. My BNB transaction is still stuck/pending? 

 mMy rune never went into LP but is blocked?!

This is Asgardex wallet adress:

bnb1fhz76xdwh775gks40e74w853tvn4g80zhgpsvp

**Comment by veado** [comment]
@plato50 It seems while adding liquidity to BNB pool, your RUNE tx was failed and your BNB is still pending. You can check your pending assets at https://thorchain.tools

![Screenshot from 2021-05-26 10-47-42](https://user-images.githubusercontent.com/61792675/119631825-8a102480-be10-11eb-8bf1-9d4c2587fb8c.png)

To finish your deposit or to withdraw it go to https://app.asgard.exchange/deposit-sym-recovery and import your ASGARDEX desktop wallet there (you need to have your ASGARDEX desktop keystore exported before: Settings -> Export keystore). At `deposit-sym-recovery` search the `BNB` pool and you'll have the option to withdraw and recover funds. Keep in mind, this will withdraw 100% of what you have deposited into the BNB pool (including previously successful deposits).

**Comment by plato50** [comment]
Thank you so much!!! It worked! Why is this "pending transaction" button not in the desktop wallet, like in the web based wallets? And some FAQ would cause less questions, Q: Like my transaction is stuck/pending A: The steps to take are ....
Again thx for your hard work!

**Comment by veado** [comment]
Glad it worked for you.

> Why is this "pending transaction" button not in the desktop wallet, like in the web based wallets? 
We are always working hard to bring different features into ASGARDEX, but unfortunately we can't bring everything at once into it. However, we will try to improve UX in case of (possible) failing deposits very soon.

> And some FAQ would cause less questions, Q: Like my transaction is stuck/pending A: The steps to take are ....
Good suggestion, we will think about that ^
