### ISSUE TITLE
Did swap of BTC to RUNE but RUNE not showing up in THORCHAIN Assets nor is transaction showing up in my wallet 'HISTORY'

### ISSUE THREAD

**Issue by Tonacious** [thorchain/asgardex-electron#1454]
Expecting swapped BTW for RUNE to show up in THORCHAIN Assets

No RUNE showing up after 45+ minutes and counting...

I don't know what to suggest, but I could use some feedback in regards to what my expectations should be in regards to the amount of time it takes for a BTC to RUNE swap to take place.  Everything appeared to be running fine when it came to seeing the swap interface operating.

I am seeing no history in my wallet of the swap even having taken place... which isn't exactly confidence inspiring if you've put $1K of BTC in the wallet and made a swap for 85.8 RUNE and it's not showing up anywhere in my wallet...

I'm trying to get access to the RUNE I swapped my BTC for and I'm not even seeing any details of the transaction in the 'HISTORY' section of my wallet.

My THORCHAIN wallet address is:

thor10fu2f8u5sjvk9hg4hz39w2gxw2gxdzq66hgf5t

## Your Environment

I'm running Asgardex Version 0.2.1 (0.2.1)
on Mac OSX 11.2

**Comment by Tonacious** [comment]
My RUNE just showed up!

However, as a matter of inspiring confidence in the process (especially for newbies like myself) I'd suggest you add some sort of on-going, staged update of the transaction once initiated (under 'HISTORY' or elsewhere...?).

That said, I am excited by the possibilities of this platform and I look forward to using Thorchain in the future!

**Comment by veado** [comment]
@Tonacious BTC has a long blocktime, that's why it take some time to get final result of a swap BTC -> RUNE. We will think about how we can improve the UI to give users such information. Thanks for your feedback / suggestion.
