### ISSUE TITLE
Didn't receive RUNE when swapped with LTC

### ISSUE THREAD

**Issue by brck711** [thorchain/asgardex-electron#1455]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior
I've never done this before so I'm not sure what data to add.  

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by veado** [comment]
@brck711 Could you share some more details (transaction hashes, ASGARDEX wallet addresses for RUNE / LTC), pls?

**Comment by veado** [comment]
@brck711 Ping ^

**Comment by brck711** [comment]
Close issue.  Sorted out.
