### ISSUE TITLE
I used Asgardex desktop app to add liquidity to MCCN. Started with $320K, ended up with $270K

### ISSUE THREAD

**Issue by goldenNyan** [thorchain/asgardex-electron#1456]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

I deeply apologise to the devs for polluting this place but I think there might be a bug in memo function in asgardex desktop app (0.2.1) (described in https://github.com/asgardex/asgard-exchange/issues/390 but I'll describe it again here as well).

## Current Behavior

1. I moved my bep2.rune and bep2.eth to bnb187ag8gxc3773lahj48k28h45zpc2ya9pwutvuu (Asgardex)

2. upgraded to native rune to thor12e8dn0dtuuk9mpmj9hqf4tvzw42zxeanu2p40c (Asgardex)

3. added liquidity to bep2.eth pool (Asgardex)

4. only rune went through ASYMMETRICALLY with a massive slippage (Asgardex)
<img width="793" alt="Screen Shot 2021-05-26 at 06 49 03" src="https://user-images.githubusercontent.com/84806162/119552203-8ec3e100-bdee-11eb-95e9-f9f038abfc7f.png">

5. bep2.ETH got stuck as below (Asgardex)
<img width="1577" alt="Screen Shot 2021-05-26 at 04 14 49" src="https://user-images.githubusercontent.com/84806162/119549904-d432df00-bdeb-11eb-9466-a26354f16c36.png">

6. received help from THORSwap community and managed to withdraw the pending funds (THORSwap)

7. funds returned as 50% rune and 50% bep2.eth (THORSwap)

8. now the first half of the liquidity I added got stuck as below (Asgardex & THORSwap)
<img width="1644" alt="Screen Shot 2021-05-26 at 05 55 27" src="https://user-images.githubusercontent.com/84806162/119550436-85d21000-bdec-11eb-8a9d-0e11cb627234.png">

9. received help from THORSwap and completed the LP (THORSwap)

10. but now native rune recovered from step 7 was withdrawn (instead from the initial fund that was swapped ASYMMETRICALLY against my wish)

11. I lost my funds (unintended asymmetrical swap & around 25% of the funds that I started with)

UPDATE:

it looks like step 9 went through, but as another asymmetrical swap with a massive slippage. So I now have that amount minus the massive slippage. Now this particular process completely drained my rune and I am now again stuck in the network.

<img width="793" alt="Screen Shot 2021-05-26 at 08 17 58" src="https://user-images.githubusercontent.com/84806162/119563394-96d64d80-bdfb-11eb-8cac-38093f0c44fd.png">

UPDATE 2:
I gave another go at adding liquidity (using THORSwap), and it went smoothly this time. After doing some calculations, I don't think there should be an issue with regards to solvency. It looks like I've just lost a bunch of money due to a bug that led me to add liquidity asymmetrically several times.

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by veado** [comment]
@goldenNyan Could you share some more information about your deposit txs, pls? I've just found this [831B5072CAE02EC41DDD2D899457B53CDC0D339EF9CA0D6DC03E50BAB59BBB4F ](https://explorer.binance.org/tx/831B5072CAE02EC41DDD2D899457B53CDC0D339EF9CA0D6DC03E50BAB59BBB4F), which seems to include ~11 ETH, but not all the amount you mentioned before (maybe I've missed something).

> I think there might be a bug in memo function in asgardex desktop app (0.2.1)
Memo of previous ADD liquidity tx ^ looks fine (no issue there).

Regarding slippage: Since you have added a high amount while trying to add liquidity symmetrical tinto `BNB ETH-1C`, slippage was increased that high. 

_I'm going forward your issue to the team to investigate more into it  ..._

**Comment by goldenNyan** [comment]
Thank you for paying attention to my issue.
Please note that I wanted to add liquidity symmetrically, and I signed for a symmetrical addition on the Asgardex app but then only the rune went through, as an asymmetrical addition, hence the unintended slippage.

I've gathered below what I could find about the incident:

1. I transferred 14765 bep2.rune (https://explorer.binance.org/tx/AC0721DEF98AC11FD5F1B5A60202EACA0B30B8165617F77D44CC131E97CB6633) and 61.5 (https://explorer.binance.org/tx/9DBFCFBD651B3EF202A821187A3CAA7115CB68C2F6C5D027EC778BD6CDA3DBF7) from SCCN to MCCN 

2. Signed for a symmetrical LP on Asgardex app but only Thor.rune went through as an asymmetrical addition, hence the unwanted slippage (https://thorchain.net/#/txs/642AD6C8589495E16BFFAD02A4F110833622F9D696B81F0747DD8EC2EDEE92C9). Also see below:

<img width="793" alt="Screen Shot 2021-05-26 at 06 49 03" src="https://user-images.githubusercontent.com/84806162/119622997-d9c80d80-be5b-11eb-8de3-ceaaebe6517e.png">

3. The price discrepancy was arbed away immediately + the bep2.eth got stuck as below:

<img width="1577" alt="Screen Shot 2021-05-26 at 04 14 49" src="https://user-images.githubusercontent.com/84806162/119623060-e9dfed00-be5b-11eb-96fd-53f9421cee95.png">

4. I received help from the kind folks from THORSwap and managed to withdrew the pending bep2.eth, but the fund came back as 50:50 with thor.rune and bep2.eth (https://thorchain.net/#/txs/3D3361FCA7825B9DE25ADA6182F3F4AD832A1619629C039E06C68C035259B1CB)

Along these transactions I lost a lot of money.

5. then I realised the initlal LP was stuck and unable to access through Asgardex app (unclickable). Again, the kind folks from THORSwap suggested that if I complete LP on THORSwap (see below for the *complete* button) then I should be able to finalize the initial LP and then be able to access it.

<img width="1644" alt="Screen Shot 2021-05-26 at 05 55 27" src="https://user-images.githubusercontent.com/84806162/119623705-902bf280-be5c-11eb-87fd-1feec961e769.png">

6. but when I did that, something I don't understand happened and another asymmetrical swap occurred (see below)

https://thorchain.net/#/txs/5FF9D44BA736DCDB66A381776AD333D0B70FCD46BE2687750972CB03E24E1756

also:

<img width="793" alt="Screen Shot 2021-05-26 at 08 17 58" src="https://user-images.githubusercontent.com/84806162/119623982-cf5a4380-be5c-11eb-8ca7-0954157ca09f.png">

Again, I believe I lost some more money here. I never wanted to add liquidity asymmetrically.

7. I tried to add liquidity, this time using THORSwap rather than Asgardex app (https://thorchain.net/#/txs/179848664E3BADF1040C0D98C41A24186C3C7E709272BC316F3F915427B9279F), which went through with no issue. No slippage, no money lost. This is the transaction that you are referring to. The purpose of this transaction was to experiment how THORSwap would handle symmetrical liquidity provision.

I've been an LP on SCCN for more than 5 months and I think I lost more than 100 days worth of accrued fee and then some.

Please help..

**Comment by veado** [comment]
@goldenNyan The team has tried to follow your steps with following result:

> The scenario happened in the following order:
> 
> Issue: https://github.com/thorchain/asgardex-electron/issues/1456
> 
> User binance account:
> https://explorer.binance.org/address/bnb187ag8gxc3773lahj48k28h45zpc2ya9pwutvuu
> 
> User thor account:
> https://viewblock.io/thorchain/address/thor12e8dn0dtuuk9mpmj9hqf4tvzw42zxeanu2p40c
> 
> Note: there's no option for asymm deposit in asgardex so user tried only symm deposit.
> 
> 1. User upgraded small amount of rune and tested deposit:
> http://midgard.thorchain.info/v2/actions?limit=10&offset=0&txid=3553D7F58D00F9F91E53E5DA1AF1FC23D223666F6B3844D3044BAB1ED7361F0E
> 
> 2. I suspect User tried another deposit with small amount but only small amount of BNB.ETH deposited, hense User has pending deposit waiting for THOR.RUNE.
> 
> Binance tx: https://explorer.binance.org/tx/6F6A848AD4641E240EF1A3752265A50697BF98586EF3E949D1492A90CE162B3A
> 
> 3. User didn't notice there's a pending deposit, and he/she moved large funds to wallet and tried to deposit with 14,764 THOR.RUNE and 61 BNB.ETH
> 
> Since user already had a pending deposit, 14,764 THOR.RUNE was matched to a previous BNB.ETH deposit (0.00204349), hense User got a huge slippage after tx.
> 
> But the completion of previous pending deposit lead to another pending deposit for 61 BNB.ETH.
> 
> 4. User tried withdraw from symm LP but only withdraw from completed deposit, hense there's still a pending deposit of 61 BNB.ETH.
> 
> withdraw tx: https://viewblock.io/thorchain/tx/3D3361FCA7825B9DE25ADA6182F3F4AD832A1619629C039E06C68C035259B1CB
> 
> 5. User noticed there's a still pending deposit and completed by depositing THOR.RUNE on Thorswap.

Would you agree you have tried these steps ^? It seems you tried different steps / actions in a short period of time and the system processed in such a manner by default. That's not a bug.

**Comment by goldenNyan** [comment]
Yes I tested out a small amount of deposit before making a larger deposit as below

<img width="1126" alt="Screen Shot 2021-05-27 at 01 02 27" src="https://user-images.githubusercontent.com/84806162/119664424-6b00a980-be87-11eb-9250-418e41f0b433.png">

The transaction went through as a symmetrical addition, I confirmed that it went through on both runeyield and asgardex app. After 15 minutes from the initial test I added the larger amount.

I think the description above is loosely consistent with what may have happened, but on my end

> I suspect User tried another deposit with small amount but only small amount of BNB.ETH deposited, hense User has pending deposit waiting for THOR.RUNE.

was not indicated to be pending. I started with BEPSwap and Asgardex app and at no point was I notified of the possibility that the next transaction will be matched with the previous test run.

After the initial  14.7K and 0.002 ETH match, yes I moved to using THORSwap and tried withdrawals, as I panicked and sought help from the community.

So I guess this would be more of an UX/UI issue rather than a bug..

**Comment by goldenNyan** [comment]
Is this issue (https://github.com/thorchain/asgardex-electron/issues/1287) related to the lagged matching of funds?

**Comment by veado** [comment]
> Is this issue (#1287) related to the lagged matching of funds?

Yes, #1287 is to improve the UI to handle failing sym. deposit in a better way (from UX perspective only - we can't avoid such failings at the end) and to give users an option to re-send failing tx (similar to recovering tools). However, there is more to do for the UI to handle (possible) pending assets of previous txs as well.

**Comment by goldenNyan** [comment]
I guess my case would be something similar to Alpha Finance UI issue (https://twitter.com/mgnr_io/status/1393712212791894017?s=20). Would you consider my issue has came to an end? One could say this was an unfortunate byproduct of test in prod approach. I was hoping that this case would be considered a candidate of partial compensation (really sorry the rune I lost keeps me up at night)

**Comment by kaiansaari** [comment]
Thanks for raising your concerns here. First let's make some distinctions:

- THORChain project: An opensource software project managed by the community. Anyone can represent the project and contribute.

- THORChain protocol: A permissionless liquidity protocol operated by anonymous nodes. Running the thornode binary is the only way to signal support for a feature or design decision.

- THORChain team: Ideologically aligned contributors to the project applying mindshare to thorchain. The team includes individuals and groups who don't necessarily have access to the treasury nor have the ability to influence key decisions. It's very much a collaboration.

In this situation the protocol acted as designed without fault. While there was a usability concern with the interface, the data is open & available to anyone to inspect in order to determine whether your tx needs to be re-tried. There are also multiple interfaces which provides optionality for users. Accoridingly there will not be any compensation provided in this case.

The salient point here is that you have (for the lack of a better word) _aped_ into multichain #chaosnet knowing the risks and due to a series of decisions have experienced erosion of your capital due to arbitrage. AMM's and liquidity pools are designed for experienced DeFi users. It's important on chaosnet to never ape in with large size and to ensure you have a solid understanding of the protocol before making any swaps or providing liquidity.

The treasury cannot be used as insurance in these situations, and i'm not aware of anyone with access to the treasury who would make an exception. Apologies if this is not the answer you're looking for. I would encourage you to continue to participate, particularly given the current yield / APY.

Feel free to reach out on telegram or discord.
