### ISSUE TITLE
Possibility to export private keys in a wallet. 

### ISSUE THREAD

**Issue by robiwano** [thorchain/asgardex-electron#1457]
Today it is possible to export 12-word phrase or the keystore info, but not possible to export the private keys (f.i. for BTC). This would be good.

**Comment by HildisviniOttar** [comment]
Why not just export phrase and use https://iancoleman.io/bip39/ 

This tool can also be used offline by cloning from GitHub.

**Comment by robiwano** [comment]
Whoa, cool. I was just wondering if there might be such a thing. Thanks!

**Comment by waokdalf** [comment]
With export feature it will be much easier for users. Not all understand that there is such software like bip39 Mnemonic code converter. Not all understand how to use it offline, etc...
This feature gives people more control and flexibility
