### ISSUE TITLE
Wallet Creation-When "Finish" is selected nothing happens?

### ISSUE THREAD

**Issue by goodtimes** [thorchain/asgardex-electron#1460]
## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by goodtimes** [comment]
Any suggestions for a fix?

**Comment by thatStrangeGuyThorchain** [comment]
hey @goodtimes! ! thnx for the issue
could you pls provide more details such version/OS/etc ?
also would be really helpful to have a video of an issue.

I've just tested v0.2.1 on macOS (10.14.1 Mojave) and clean win10. everything works for fine me

https://user-images.githubusercontent.com/67793194/119787188-a2984180-bed9-11eb-90a1-ae8ef3eadae0.mov

**Comment by bigbellyho** [comment]
I posted the same bug under issue 1463 which was closed since this was a duplicate issue.  I am running Windows 8.1 Pro 64 bit version.  I downloaded the win.exe install program.  Here is the vidoe showing nothing happening once Finish is clicked.

https://photos.app.goo.gl/sHPxQCRAd2J1Vp2n6

**Comment by bigbellyho** [comment]
Here is a better video

https://vimeo.com/555910215/7bfdefe238

**Comment by bigbellyho** [comment]
So I realized I was doing this all wrong.  Apparently failed the smart test.  I wasn't putting the phrase in the right order.  Now that I've done this it works now.

**Comment by thatStrangeGuyThorchain** [comment]
thnx for replies @bigbellyho. Actually this is not a smart test but "security" check you have saved your phrase somewhere for 100% to keep it always in a save place to have a possibility to use it everywhere (everytime) else.
actually there is missed UI error displaying (will be fixed soon). thnx for reporting an issue again
