### ISSUE TITLE
Swapped BTC for ETH, BTC went but ETH didn't appear.

### ISSUE THREAD

**Issue by 23bcw** [thorchain/asgardex-electron#1461]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ x] I have no idea what this means !

## Expected Behavior

I swap BTC for ETH and it works smoothly; my BTC balance goes down and my ETH balance increases.

## Current Behavior

I tried to swap BTC for ETH, still waiting for the ETH to show an hour later.
https://blockstream.info/tx/e4fb9c8653b2fe8254ae27b66a1fa0d8a827d6d18534e00a7283dacf4ec11346

I just made the wallet about three hours ago, I deposited some ETH to test it with:
https://etherscan.io/tx/0x0b2854fc52399b42da1afca7cd9498c43536d539355f87d7c99f3ff2c3cf2454
but this turned out to be insufficient in quantity to swap for RUNE so I deposited some BTC as well:
https://blockstream.info/tx/2f304b889107698de464f7b2487de620e2d0be309e29d7f7b49e71829c3028af
with this I swapped some for RUNE,[all good and working fine so far]:
https://blockstream.info/tx/bdecc1f9e6a48f45f21069a6cc31f40ec37be96c8146cb09d6b4fa782feb77e6
intending to add the remaining balance to the ETH to top it up enough to swap for more RUNE.
Then I went to swap the BTC for ETH and the BTC balance went down but the ETH has not yet arrived.

Side note. I got to this from the video by Max Wright [https://www.youtube.com/watch?v=c_KEMFsVOiM] and I note that when he swapped his ETH for RUNE the ETH balance did not reflect his action either.

Is this a bug ? Can I expect to see my balance arrive at some point in the future ?

## Possible Solution

I find out what to do [please explain at 'moron' level] to get my funds back from the in-between.

## Steps to Reproduce (for bugs)

1. Go to 'pools'.

2. Select 'swap' in BTC row.

3. Swap for ETH.
[After fine tuning it to swap as much of the BTC as possible to try and leave none at all behind. Is it possible for there to be a '100% less fee' option, I'm a bit OCD and hate to have niggly little bits of coin/token floating around that can't be used ?]

4. Go to 'wallet' and check new balances, breathe deeply and find out where to go for help.

## Context

I have lost 0.00454322 BTC, around £125 at time of typing, to the Aether, still got enough SOH to pun tho :)

## Your Environment

- Node version : ?
- Version or Branch used : ?
- Operating System and version :Host: Kernel: 4.15.0-142-generic x86_64 bits: 64 gcc: 7.5.0
           Desktop: Cinnamon 3.8.9 (Gtk 3.22.30-1ubuntu4) dm: lightdm Distro: Linux Mint 19 Tara
- Link to your project : ?

**Comment by 23bcw** [comment]
ETH wallet address: 0xf1e7230c7578c0328669022b966ba9f4a10074dd
BTC ditto: bc1qzx3sr9fp6dm8nk08nugkx7y5keda72n8eshnlm

**Comment by 23bcw** [comment]
I have tried the refresh button exhaustively [I have been reading other bugs similar to mine and am attempting to give you all the info you might need to help with this.]

**Comment by veado** [comment]
@23bcw Your outgoing swap tx was successful, you can check it at Etherscan https://etherscan.io/tx/0xc3b817fdb301aa13926bb3675e589c4e1190696b7afc59ccee2010e8d6759757

At Etherscan it's only visible in your wallet by selecting "Internal tx" (because outgoing swap txs are internal tx for ETH): https://etherscan.io/address/0xf1e7230c7578c0328669022b966ba9f4a10074dd#internaltx


The issue you describes here ^ is very similar to #1462. That's why I copy/paste same background information about here: 

> There is currently a bug in a depending library (`xchain-ethereum`) used by ASGARDEX desktop, which does not return internal txs (a outgoing swap tx is such internal tx). That's why this tx is not visible in txs history of ASGARDEX desktop (similar to #1350, related to https://github.com/EverexIO/Ethplorer/issues/209 (`Ethplorer`) and  https://github.com/xchainjs/xchainjs-lib/pull/314 (`xchain-ethereum`).

**Comment by veado** [comment]
History for ETH balances will be fixed by https://github.com/thorchain/asgardex-electron/issues/1465

_Closing this issue here for now... If you have still issues / questions, feel free to re-open it again or create another issue. Thx!_

**Comment by 23bcw** [comment]
Hi, thanks for the attention, did you miss the 'plz explain at moron' level, I'm ignorant of this part of reality: What is a tx ? I'm guessing it stands for transfer ?
So, please, in 'real' terms does this mean I will never see my ETH again, it will show up after the bug is fixed or I need to do something at my end to fix it ?

**Comment by 23bcw** [comment]
Ok I think I'm starting to see what is going on at the Etherscan; the ETH was sent from the block to my Asg. wallet address. So it is officially there but I just can't see or use it. Is that right ?

"History for ETH balances will be fixed by #1465" I looked at this, is it a 'pending fix' kinda thing ?

**Comment by 23bcw** [comment]
Got it, yipee ty.
