### ISSUE TITLE
Swapped RUNE for ETH, RUNE decrimented but never received ETH

### ISSUE THREAD

**Issue by BoWilly** [thorchain/asgardex-electron#1462]
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

 Transaction should complete correctly for swapped Coins

## Current Behavior

  I swapped 448 RUNE for 1.97463114 ETH.  The 448 RUNE were deducted from my Wallet.  But, the 1.97463114 were never credited to my Wallet.

## Possible Solution

 Unknown

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Context

 I am unable to swap my ETH because I haven't yet received it.
 N/A
 N/A

## Your Environment

- Node version :
- Version or Branch used : 
- Operating System and version : ASGARDEX App, Version 0.2.1
- Link to your project :

**Comment by veado** [comment]
@BoWilly If possible, could you share your wallet addresses for RUNE + ETH, pls?

**Comment by BoWilly** [comment]
ETH: 0x3670f12cf805e8b05c13e2fd22f3a0632706d7c1
RUNE: thor1jqr29uqn9sjmmeue56kwmtnmjgqfa2n4ry4jw8

Transaction: 3FE97CC9EA2A7BF01D345B3B9968804C328C1EB1150CF9AE9D1FF7CE645A5362

![image](https://user-images.githubusercontent.com/84890091/119801411-b036d280-beab-11eb-94aa-2ba50c673730.png)

![image](https://user-images.githubusercontent.com/84890091/119801537-cb094700-beab-11eb-9424-50fd4691e138.png)

**Comment by BoWilly** [comment]
Transaction ID In (RUNE): 3FE97CC9EA2A7BF01D345B3B9968804C328C1EB1150CF9AE9D1FF7CE645A5362
Transaction IF Out (ETH): 69079E5AB7BDF2D86E0B04E8432D4093736744E5F1946CE1813C13D6941947F3

The RUNE was deducted, but the ETH was not credited to my wallet.

**Comment by veado** [comment]
@BoWilly Thanks for providing more data, I'm going to reach out to the team to get more information what might happened here ^

**Comment by veado** [comment]
@BoWilly Your outgoing swap tx was successful https://etherscan.io/tx/0x69079e5ab7bdf2d86e0b04e8432d4093736744e5f1946ce1813c13d6941947f3 and it's in already in your wallet. To see outgoing amount of ETH at Etherscan, check https://etherscan.io/address/0x3670f12cf805e8b05c13e2fd22f3a0632706d7c1#internaltx

There is currently a bug in a depending library (`xchain-js`) used by ASGARDEX desktop, which does not return internal txs (a outgoing swap tx is such internal tx). That's why this tx is not visible in tx history of ASGARDEX desktop (similar to #1350).

**Comment by veado** [comment]
History for ETH balances will be fixed by https://github.com/thorchain/asgardex-electron/issues/1465

_Closing this issue here for now... If you have still issues / questions, feel free to re-open it again or create another issue. Thx!_

**Comment by 23bcw** [comment]
@BoWilly 

"The RUNE was deducted, but the ETH was not credited to my wallet."

Same happened to me but with BTC, not quite sure what is going on ... are we waiting for the ETH people to fix the bug ?
Did you see your ETH yet ?

**Comment by BoWilly** [comment]
I still can't see the ETH in my wallet yet.

Here is a comment on another thread: Currently xchain-ethereum does not support internal txs for balances, it needs to fixed there first to bring it into ASGDX.

But, I'm not sure how long it will take to resolve or who is working on this issue.

Combined thread:
https://github.com/thorchain/asgardex-electron/issues/1465#

**Comment by 23bcw** [comment]
OK ty. Just hodl on then :)

**Comment by BoWilly** [comment]
My issue has now been resolved and I can see the ETH in my wallet. - #1462

Thanks for the help!

**Comment by 23bcw** [comment]
Just got in to find mine there too, hooray for the fixers :)
