### ISSUE TITLE
trying to create a new wallet, but when you get to the 2nd screen to enter the pass phrase in the correct order it won't let you click Finish and move on.  Nothing happens

### ISSUE THREAD

**Issue by bigbellyho** [thorchain/asgardex-electron#1463]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>

**Comment by thatStrangeGuyThorchain** [comment]
hey @bigbellyho ! thnx for the issue
could you pls provide more details such version/OS/etc ?
also would be really helpful to have a video of an issue.

I've just tested v0.2.1 on macOS (10.14.1 Mojave) and it seems it works for me

https://user-images.githubusercontent.com/67793194/119785127-97441680-bed7-11eb-9944-35a15c6d53b8.mov

**Comment by thatStrangeGuyThorchain** [comment]
closing as duplication of #1460

**Comment by bigbellyho** [comment]
I am running windows 8.1 pro 64 bit version.  I downloaded win. exe.  here
is the video of finishing being clicked and nothing happening.

https://photos.app.goo.gl/sHPxQCRAd2J1Vp2n6

also posted. to the issue 1460

bigbellyho
