### ISSUE TITLE
New version won't accept password

### ISSUE THREAD

**Issue by Jastech199** [thorchain/asgardex-electron#1464]
## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

I expect my pass phrase given to me in v0.2.0 to allow me to unlock my wallet in v0.2.1

## Current Behavior

After entering my phrase, I get the following error:
COULD NOT UNLOCK THE WALLET. PLEASE CHECK YOU PASSWORD AND TRY IT AGAIN

## Steps to Reproduce (for bugs)

1. I downloaded a new version of ASGARDEX 0.2.1

2. Started the new version of the app and went to unlock my wallet by entering my phrase

3. Got the error as shown above in "Current behaviour"

4.

## Context

I can't access my wallet as I expect to be able to with the pass phrase I was given the first time I used this windows desktop app.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version : Windows 10 Home
- Link to your project :

**Comment by veado** [comment]
@Jastech199 Could you download previous version `0.2.0` from https://github.com/thorchain/asgardex-electron/releases/tag/v0.2.0 to install it and to see if it still works for you? Maybe it's because of using a wrong password ...

**Comment by Jastech199** [comment]
Hi,

I’ve just tried the previous version 0.2.0 following the link you included. I still get the same problem.
The pass phrase is a series of 12 words separated by a space. Do you include the spaces when entering the 12 words? I have tried both with and without spaces and get the same response. The order of the words I recorded is the order I am entering them in. Should there be a different order? If so, how do you know what that is?

Thanks.

Regards,
Jon.

**Comment by Jastech199** [comment]
Hi again,

Sorry, I have just tried using my original password and not my pass phrase. I have got in!
I apologise for the inconvenience I’ve caused. I am a very new user.

Kind regards,
Jon.

**Comment by Jastech199** [comment]
Sorry for the trouble guys. Hope I didn't waste much of your time.
