### ISSUE TITLE
[Wallet] Include balances of internal txs for ETH

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1465]
Currently `xchain-ethereum` does not support balances of internal txs, it needs to fixed there first to bring it into ASGDX.

Related issues reported by users:
- #1350
- #1389
- #1461
- #1462

**Comment by BoWilly** [comment]
When will this issue get resolved?

**Comment by BoWilly** [comment]
When will I have the ETH available in my wallet?

**Comment by BoWilly** [comment]
@simon852 can you assist with this issue?

**Comment by BoWilly** [comment]
My issue has now been resolved and I can see the ETH in my wallet.  - https://github.com/thorchain/asgardex-electron/issues/1462

Thanks for the help!

**Comment by 23bcw** [comment]
I now see it in my wallet, thank you very much for your help.

**Comment by veado** [comment]
Issue has been fixed in https://github.com/xchainjs/xchainjs-lib/pull/329. ASGARDEX has been updated to use latest `xchain-ethereum`, which includes this fix.
