### ISSUE TITLE
BCH to ETH swap not showing up in my wallet

### ISSUE THREAD

**Issue by mtcandyman** [thorchain/asgardex-electron#1493]
## Prerequisites

- [ x] Using yarn
- [ x] Using node 12.x
- [ x] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ?] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

 the swap shows on my history but is not in my wallet

## Current Behavior

transaction disappeared
should be in wallet

## Steps to Reproduce (for bugs)

this shows it happened but is not in my wallet:https://thorchain.net/#/txs/8BA74CAA130C6CDC57DA2FFC8AF327868E995A8EEB61086A2E1A826C47C5EADD

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by veado** [comment]
Thanks for your report, I've forwarded it to double check it internally by the team.

**Comment by veado** [comment]
@mtcandyman Your swap was successful and is already available in your ETH account (see https://etherscan.io/tx/0x4254c4455c51ec23e956aa7927a5325030d31a0f0ac1d464e10471f811bc321d#eventlog). 

There is currently an issue in ASGARDEX by using an external API of Ethplorer, which does not update balances for internal transactions (a SWAP transaction is such an internal tx) properly. We have already prepared a fix in https://github.com/thorchain/asgardex-electron/issues/1465, which will be available with next release.

Similar to #1350
Related to #1491

_Closing this issue for now - if you have more questions, feel free to re-open it again or raise another issue. Thank you!_
