### ISSUE TITLE
White Screen after password enter

### ISSUE THREAD

**Issue by kyl3kan3** [thorchain/asgardex-electron#1507]
## Steps to Reproduce

1.start application
2.click wallet
3.type password
4.unlock
5.application goes white screen

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 0.2.1

- Operating system and version:

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by veado** [comment]
@kyl3kan3 Could you give us some more details, pls? Which ASGARDEX version, which OS, a short screen shot or screen cast would be helpful as well... Thanks!

**Comment by thatStrangeGuyThorchain** [comment]
@kyl3kan3 thnx for reporting an issue!
could you pls provide any screencast ? i've just tried to reproduce it but everything works as expected 🤔 
also if you still facing an issue could you pls provide more details ? OS version or smth like that ?

**Comment by kyl3kan3** [comment]
0.2.1 and 0.2 did it running Windows 10 https://admiralparkway-my.sharepoint.com/:v:/p/kyle_kane/EZ4Ciw8KefRFgyvE2C8BlaABMvgY63S_1VOFpFy_gCnf9Q?e=KMaSQI   From: veadoSent: Friday, June 4, 2021 1:16 PMTo: thorchain/asgardex-electronCc: kyl3kan3; MentionSubject: Re: [thorchain/asgardex-electron] White Screen after password enter ***@***.*** Could you give us some more details, pls? Which ASGARDEX version, which OS, a short screen shot or screen cast would be helpful as well... Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kyl3kan3** [comment]
0.2.1 and 0.2 did it running Windows 10 https://admiralparkway-my.sharepoint.com/:v:/p/kyle_kane/EZ4Ciw8KefRFgyvE2C8BlaABMvgY63S_1VOFpFy_gCnf9Q?e=KMaSQI   From: thatStrangeGuyThorchainSent: Friday, June 4, 2021 1:16 PMTo: thorchain/asgardex-electronCc: kyl3kan3; MentionSubject: Re: [thorchain/asgardex-electron] White Screen after password enter ***@***.*** thnx for reporting an issue!could you pls provide any screencast ? i've just tried to reproduce it but everything works as expected 🤔also if you still facing an issue could you pls provide more details ? OS version or smth like that ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by thatStrangeGuyThorchain** [comment]
@kyl3kan3 thnx for screencast. for some reason i still can not reproduce this issue on win10... could you pls provide a list of assets you have for all chains ? thnx

**Comment by kyl3kan3** [comment]
Would wallet address be easier? And chains ?

**Comment by thatStrangeGuyThorchain** [comment]
@kyl3kan3 yes. address is easier (we took it from your screencast). We figured out that the problem is about `MethodNFT` asset inside of balances. This is `ERC-721 (NFT)` asset which is not supported by `Asgardex`. Fix is already in a review (we will just filter out such assets from balances)

depends on https://github.com/xchainjs/xchainjs-lib/pull/349

**Comment by kyl3kan3** [comment]
Great thanks
