### ISSUE TITLE
Incorrect 'TO' address displayed in Transaction History

### ISSUE THREAD

**Issue by Obeewon** [thorchain/asgardex-electron#1516]
The 'TO' address field in Testnet 'Transactions For Last 90 Days' (THOR.RUNE) field defaults to a random address unrelated to the transaction.

TXID (example): https://viewblock.io/thorchain/tx/9C175AF7ACE9FCDC930B78909FFF598C18CBEAF9F39D7AA2C4D9A27BB7E55A5C?network=testnet

Incorrect 'TO' address shown: tthor1g98cy3n9mmjrpn0sxmn63lztelera37nrytwp2
Correct 'TO' address: See above viewblock txid.

![image](https://user-images.githubusercontent.com/85541084/121178019-6681bb00-c8a1-11eb-96d5-5f22ccebf168.png)

- ASGARDEX desktop version:
V0.2.1 (Mac)

- Operating system and version:
Mojave 10.14.6

**Comment by veado** [comment]
@Obeewon The data in ASGARDEX seems to be correct based on following API endpoint to get data of this `BOND` transaction: https://testnet.thornode.thorchain.info/thorchain/tx/9C175AF7ACE9FCDC930B78909FFF598C18CBEAF9F39D7AA2C4D9A27BB7E55A5C

However, I've asked `viewblock` team why we might have such differences for `TO` address (if you are interested you can follow it in [THORChains Discord #viewblock channel](https://discord.com/channels/838986635756044328/846612413477945384/852189722704609330))

**Comment by veado** [comment]
Fixed with #1563 (available in `v0.3.5`)
