### ISSUE TITLE
i swapped Rune for BTC usually its fast this time its taking over 30 mins i just want to make sure its still going to appear

### ISSUE THREAD

**Issue by roywh10** [thorchain/asgardex-electron#1518]
## Issue description
Swapped Rune for BTC its taking a while unlike the previous times just wanna make sure there isn't an issue

## Your Environment
not sure what this means

- ASGARDEX desktop version:
ASGARDEX-0.3.0-win.exe

- Operating system and version:
Windows 10 x64

- Transaction hash(es):
3F33969615072D2577D8D72742F628B1216567D7ACBEFA1573069C07148098F5 <Transaction ID (IN)
B37CB0222684434C89F706317128DEF10B95B3AC1BB97D00F379A3627E8668D1 <Transaction ID (OUT)

- Wallet address(es):
bc1q65zdpc0eqrsa79mp2ft7jkhwrnvwteus5hgxxs <BTC Wallet
thor19wxedf386352mpd8lsk49wvny4hackwe903y5g <Rune Wallet

**Comment by veado** [comment]
@roywh10 Thanks your your detailed information. The amount of your swapped `BTC` should be in your `BTC` wallet now:

- THORChain swap `OUT` tx `0.00293978 BTC`  https://viewblock.io/thorchain/tx/B37CB0222684434C89F706317128DEF10B95B3AC1BB97D00F379A3627E8668D1 
- Your wallet `IN` tx `0.00293978 BTC` https://blockstream.info/tx/b37cb0222684434c89f706317128def10b95b3ac1bb97d00f379a3627e8668d1?expand

Pls note: Swap to `BTC` might take up to 45min (or more).

**Comment by roywh10** [comment]
no its still not yet
