### ISSUE TITLE
I went to open up my wallet for the first time on the ASGARDEX App and it is not accepting my phrase.  I am not sure what to do as I wrote the phrase down word for word and I am copying it word for word into the field.  Please help.

### ISSUE THREAD

**Issue by Lilypadprincess** [thorchain/asgardex-electron#1519]
## Your Environment

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):

- Wallet address(es):

**Comment by thatStrangeGuyThorchain** [comment]
@Lilypadprincess thnx for reporting an issue. 
could you please try again and double-check that you dont paste redundant symbols like space or line breakers etc.
if this does not help could test it out with next:
- create a new wallet
- save a phrase
- import this test wallet via phrase
if ^this steps^ work for you that means you enter you saved you phrase incorrectly previously

if no could you pls provide more details (asgardex app version, OS version, etc) and send us a screencast with just created **TEST** wallet?

**Comment by thatStrangeGuyThorchain** [comment]
forgot to mention
just tried it out and everything works fine for me

**Comment by veado** [comment]
@Lilypadprincess Pls let us you know if you still need support. In other case we will close your request tomorrow.

**Comment by Lilypadprincess** [comment]
Hi,
I have typed in the phrase without any space or line breakers.  I do need
to verify, the phrase was given in 2 lines with 6 words on each line - what
order is it to be entered?  Full top line and then the bottom line of words
or is it the first word then the bottom word from the first column?  Or
does it matter?  I've tried many configurations and nothing has worked so
far.

I have not figured out how to create a new wallet on the same window.  It
only gives me an option to unlock or to remove the wallet.  I am too
frightened to remove the wallet so I've not touched that button.  Can you
please advise how I actually create a new wallet without disrupting/losing
my current wallet?

Please see the screenshot
[image: Screen Shot 2021-06-10 at 5.16.18 PM.png]
Thank you

**Comment by veado** [comment]
@Lilypadprincess Enter words of your phrase in order you copied, but with an empty space between.

### Get the phrase via Wallet -> Settings -> View phrase (you already did it before I guess)

Pseudo example:
![Screenshot from 2021-06-11 11-58-53](https://user-images.githubusercontent.com/61792675/121669654-d3b56c00-caac-11eb-88c5-b29a9042945f.png)

### Enter the phrase in Wallet -> Import 

Pseudo example
![Screenshot from 2021-06-11 11-59-48](https://user-images.githubusercontent.com/61792675/121669672-d7e18980-caac-11eb-9dd0-fe2ad9ba4fea.png)

**Comment by veado** [comment]
Closing this issue for now. @Lilypadprincess Feel free to re-open it again if you still need some help to import your wallet.
