### ISSUE TITLE
BTC not showing up in ASGARDEX

### ISSUE THREAD

**Issue by Zackieboy** [thorchain/asgardex-electron#1520]
have 10 confirmations, wallet address is correct.   first time have seen this issue.

## Your Environment

Windows 10 desktop

- ASGARDEX desktop version:
v0.3.0
- Operating system and version:

- Transaction hash(es):
trx id 82e16e50819783bbda7942d24feb8f67b66cceba7825e4740fb0b947ec974f4a
- Wallet address(es):
bc1quy2ahqmjue3rjkmwsqyz80s7zlaq2304j9yz6t

**Comment by veado** [comment]
@Zackieboy Two questions:

> Transaction hash(es):
trx id 82e16e50819783bbda7942d24feb8f67b66cceba7825e4740fb0b947ec974f4a

1. What's the transaction about? Is it a swap, deposit , withdraw (pls share a tx hash for such txs). Or is it "just" a "send" transaction from one account to another?

> Wallet address(es):
bc1quy2ahqmjue3rjkmwsqyz80s7zlaq2304j9yz6t
2. Is your BTC wallet address an address you got from ASGARDEX desktop by creating a new wallet before?

**Comment by Zackieboy** [comment]
1. just a send from another account to ASGARDEX
2. yes, BTC address in ASGARDEX, have used to receive BTC many times before.
Thx

**Comment by Zunthras** [comment]
I have the same issue.. 
On 6/7/21 in the THORswap discord was announced the cap was raised.   Using ASGARDEX-0.2.1 I tried to add to the pool with $120 bitcoin and RUNE.   Gave me code 400, which I've not learned the codes yet.   I tried a second time, got code 400.  Figured my bid was too low..  so cancelled out and shut down the app.
Next morning I was going to transfer some more bitcoin (still 0.2.1) and no value presented..  it shows my RUNE still, but not the BTC.   I thought maybe a glitch. 
I opened the app today, see the update notice.  I've uninstalled 0.2.1 and installed 0.3.0 ..  imported my wallet.
Still shows no BTC.   I've only done (3) transactions.

![ASGARDEX-Trbl](https://user-images.githubusercontent.com/73271425/121307592-c2f6d180-c8c5-11eb-9ec8-8246adc4861b.jpg)

**Comment by Zunthras** [comment]
ok. update to my issue..   in ASGARDEX 0.3.0 I opened the BTC pool window again and now it shows this:
![ASGARDEX-Trbl2](https://user-images.githubusercontent.com/73271425/121308583-d5253f80-c8c6-11eb-8a71-6b6c98319af4.jpg)
However, I'm unable to open the page linked.   getting connection timeout message.

**Comment by Zunthras** [comment]
figured the link issue..  clicking the 'open recovery tool' link takes you to https://asgard.exchange/deposit-sym-recovery/  it's not the testnet.asgard.exchange..  copied that and page opens.

**Comment by Zunthras** [comment]
I'll need some help with the connecting my wallet to HTTPS://TESTNET.ASGARD.EXCHANGE/DEPOSIT-SYM-RECOVERY ..  it gives options to create keystore, or use keystore file.   which I didn't make a file.  I have the phrase words, but no file.   I did try making a text file and using that, but then it doesn't like my secure password.

**Comment by veado** [comment]
> However, I'm unable to open the page linked. getting connection timeout message. I tried to look for that code 400 in the documentation. couldn't find it.

@Zunthras That's a bug you have just recovered. The correct link for the `Recovery Tool` is https://app.asgard.exchange/deposit-sym-recovery (ASGARDEX 0.3.0 is missing `app` that url). We will fix it asap (see #1521) and ship it with next release.

> I tried to look for that code 400 in the documentation. couldn't find it.

@Zunthras `400` code means a [BAD request](https://httpstatuses.com/400). It might happened in case of high traffic while raising the cap (as similar as you have described in https://github.com/thorchain/asgardex-electron/issues/1520#issuecomment-857437588). By using [Recovering Tool](https://app.asgard.exchange/deposit-sym-recovery) you can withdraw pending BTC back to your wallet. Following step are needed:
1. In ASGARDEX desktop export keystore in `Settings` -> `Export keystore`
2. Goto https://app.asgard.exchange/deposit-sym-recovery and import the keystore from step 1
3. Select BTC pool
4. Click `Withdraw All`
_Pls let me know if it works for you - thx!_

**Comment by veado** [comment]
>     1. just a send from another account to ASGARDEX
>     2. yes, BTC address in ASGARDEX, have used to receive BTC many times before.

@Zackieboy It seems underlaying API of `sochain.com` ASGARDEX is using have not caught it up properly, it still returns zero amounts for balances https://sochain.com/api/v2/get_address_balance/BTC/bc1quy2ahqmjue3rjkmwsqyz80s7zlaq2304j9yz6t. However, balances are already in your account by checking https://blockstream.info/address/bc1quy2ahqmjue3rjkmwsqyz80s7zlaq2304j9yz6t Maybe sochain does need more time to catch up everything or has some issues recently - we will have an eye on that.

**Comment by Zunthras** [comment]
Hi Veado,
Thank you very much for stepping through the process. I didn't realize that was a link in the settings since it is different, I just figured it was a label.
I did as explained and received the following success message:
"Submitting the withdraw transaction was a success. Please wait for the transaction to go through."

In gratitude and light.
Scott

P.S.
Have you heard about Cloudcoin? If you'd like to learn more about it click here:
https://cloudcoin.global/
======
If you're interested in video entertainment like TV & Movies:
https://storyteller.americanstoriesentertainment.com/affiliate-r/8kltva92b4

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Zackieboy** [comment]
Thanks everybody, I will check later this evening.

**Comment by Zunthras** [comment]
So there's a little issue now.
On the web version, https://app.asgard.exchange/ , I'm seeing the bitcoin.
[ASGARDEX-Trbl3.jpg]

But the desktop version does not show the BTC.
[ASGARDEX-Trbl4.jpg]
I did check, BTC addresses are the same (desktop vs web page).

I do the see (est) on the web page. Is the transaction still processing?

I'll check later when I wake up. I work nights.

In gratitude and light.
Scott

P.S.
Have you heard about Cloudcoin? If you'd like to learn more about it click here:
https://cloudcoin.global/
======
If you're interested in video entertainment like TV & Movies:
https://storyteller.americanstoriesentertainment.com/affiliate-r/8kltva92b4

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by veado** [comment]
> But the desktop version does not show the BTC

@Zunthras It seems these are issues with underlying API (see previous message to Zackieboy https://github.com/thorchain/asgardex-electron/issues/1520#issuecomment-857504141). _We are still on it ..._

**Comment by jrcriz** [comment]
I have the same issue. BTC is not showing up in the wallet and I definitely have some available. Very disappointing that I missed the $9 Rune.

**Comment by veado** [comment]
We are currently preparing a hotfix release `0.3.2` to fix issue of BTC balances, which will be published within next few hours.
