### ISSUE TITLE
ASGARDEX 0.2.1 forgotten password

### ISSUE THREAD

**Issue by cT4493** [thorchain/asgardex-electron#1528]
## Issue description
On June 5th, i quickly downloaded and installed Asgardex on a second PC because I thought my seedphrase from my first installation got compromised.
I then transferred the balances from the old wallet to the wallet in the newly installed Asgardex. 

Today i wanted to write down the seed phrase from the new Asgardex wallet and was asked for the password, which I do not remember. I am not sure if I had to set a password anyway? Propaply yes.

Can you help me to access my wallet? 
Can the password maybe read our from a file in the Installation on my computer?

Thanks for your help!

I can send you what you need in private messages

## Your Environment
macOS Catalina 10.15.4

- ASGARDEX desktop version:
0.2.1.
- Operating system and version:
macOS Catalina 10.15.4
- Transaction hash(es):

- Wallet address(es):

**Comment by veado** [comment]
@cT4493 If you have forgotten password AND seed phrase, then there is (almost) no way to get your wallet back. Maybe you can try to brute force the keystore file as described in a similar discussion in #1351. You will find your the keystore file on your machine as described in https://github.com/thorchain/asgardex-electron#keystore Please note: DON'T remove your "lost" wallet from ASGARDEX as long as you don't have backup your keystore file. As mentioned before, this file might be the only way to get it back.

Another way is just trying to use any password you have in mind - you can enter it as long as you want in ASGARDEX - there is no limit to try different password.

**Comment by cT4493** [comment]
Thanks for your hint! I will ask the user in the other discussion if he was succesful.

**Comment by veado** [comment]
Closing this issue to continue discussion about possible ways to restore passwords in #1351 only.
