### ISSUE TITLE
ASGARDEX desktop app not showing bitcoin asset

### ISSUE THREAD

**Issue by norepetitivebeats** [thorchain/asgardex-electron#1535]
## Description

I sent some BTC from Binance to my desktop instalment of ASGARDEX and it doesn't show in the app. It just says NO DATA (see attached image). I also sent some RUNE to test further and the RUNE showed up. I checked my ASGARDEX BTC address in the block explorer and the Bitcoin is in there so it just seems that ASGARDEX is just not showing the amount fro some reason. I have installed the very latest version 3.1 and it doesn't fix this problem

## TODO

- TODO 1
- TODO 2
- ...
![ASGARDEX-Wallet01](https://user-images.githubusercontent.com/85672706/121494076-51f01080-c9d0-11eb-85e1-c2a343cf0391.png)

**Comment by veado** [comment]
@norepetitivebeats Yep, that's an known issue of an underlaying API (more information in #1520)  and we will push a hot fix release `0.3.2` very soon (within next hour or so).

**Comment by norepetitivebeats** [comment]
Thanks. The latest update, version 0.3.2 fixes the bug for me.
