### ISSUE TITLE
Too much BTC in my wallet (irony!)

### ISSUE THREAD

**Issue by simon852** [thorchain/asgardex-electron#1536]
My wallet had missing BTC, after updating to 0.3.2 it now shows too much BTC - looks like it shows all BTC ever added instead of balance.

Wallet: [deleted following fix]

Asgardex 0.3.2 running on Ubuntu

**Comment by veado** [comment]
@simon852 Could you share some more details, pls? 
- What's the expected amount of BTC you should have in ASGARDEX?
- Where do you see more amount of BTC? Pls share a screen shot.

**Comment by simon852** [comment]
Screenshot of asgardex
![image](https://user-images.githubusercontent.com/83420430/121520385-c172f980-c9ea-11eb-82e9-61bdb97f2e21.png)
Expected balance: 0.04098820
Displayed balance: 0.555

BTW I would be happy to accept the higher balance if you'd like to make it happen.

**Comment by glenhodler** [comment]
![BTC balance asgardex](https://user-images.githubusercontent.com/85629495/121522423-01d37700-c9ed-11eb-904e-d221f0a47cb5.jpg)
![BTC balance thorswap](https://user-images.githubusercontent.com/85629495/121522449-06982b00-c9ed-11eb-9668-71a6715d9c97.jpg)

Same problem after hotfix:

expected balance: 0.0111463 [shows correct on thorswap with wallet connected]
balance on asgardex desktop app (win 10): 0.052

**Comment by glenhodler** [comment]
also, cannot transfer balance out (even the correct amount) as it says "insufficient balance".

**Comment by veado** [comment]
@simon852 Could you share the BTC address you have used in THORSwap? It looks something different to your address in ASGARDEX (check last 4 characters in  `...tpn`  vs. `88t7`)

**Comment by simon852** [comment]
> @simon852 Could you share the BTC address you have used in THORSwap? It looks something different to your address in ASGARDEX (check last 4 characters in `...tpn` vs. `88t7`)

Sorry but are you referring to the post by @glenhodler . I've never used thorswap other than via asgardex?

**Comment by veado** [comment]
> Sorry but are you referring to the post by @glenhodler . I've never used thorswap other than via asgardex?

@simon852 Sorry, I've missed same issue were already reported by two different users here  ...

**Comment by glenhodler** [comment]
@veado - No it's the same address, just that i used a smudge tool on photoshop!

**Comment by veado** [comment]
We have identified the issue: Latest update of an external libary `xchain-bitcoin` has introduced another issue (see https://github.com/xchainjs/xchainjs-lib/issues/356) - We will provide another hot fix release for ASGARDEX asap. Sorry about that!

**Comment by simon852** [comment]
> We have identified the issue: Latest update of an external libary `xchain-bitcoin` has introduced another issue (see [xchainjs/xchainjs-lib#356](https://github.com/xchainjs/xchainjs-lib/issues/356)) - We will provide another hot fix release for ASGARDEX asap. Sorry about that!

Thank. It happens. Hopefully will be availble in time to capitalise on the current BTC:RUNE rate.

**Comment by veado** [comment]
Binaries for hotfix release `0.3.3` are currently building by CI and will be published very soon. This issue will be closed automatically, feel free to re-open it again or create another one if you still have issues. Thx!
