### ISSUE TITLE
Missing deposit

### ISSUE THREAD

**Issue by julsay** [thorchain/asgardex-electron#1539]
I sent BTC to this wallet and it is not showing up ,
Transaction ID d8f469d96d1f3834becb54112dadf3ec1eef6919140a1043139a472096f7f48b
Wallet address bc1qsscjw6hu70t5x88yws4my0ke28v3ntnygn2wnz
Transaction listed as completed on Binance. Please advise.
## Your Environment

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):

- Wallet address(es):

**Comment by veado** [comment]
@julsay What's your ASGARDEX desktop version /  Operating system and version? _Just in case: Pls try to use latest [v0.3.3](https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.3) of ASGARDEX desktop._

**Comment by julsay** [comment]
I downloaded the newer version and it worked, thanks.
