### ISSUE TITLE
Error: out of gas in location

### ISSUE THREAD

**Issue by bullishtrader** [thorchain/asgardex-electron#1541]
Hello, an user reported an issue opening a ticket in the THORSwap help-desk.
User can't withdraw his funds from the pool.

## Issue description

When trying to withdraw from Asgardex Desktop the tx remains stuck at "STEP 3/3: CHECK RESULT"
In the explorer through the tx hash the error: out of gas in location is given.
Check screenshots below:

![image](https://user-images.githubusercontent.com/82927810/121744334-05f1b880-cb03-11eb-92c8-9f0dbd619975.png)

![image](https://user-images.githubusercontent.com/82927810/121744351-0be79980-cb03-11eb-8c49-48c3837be144.png)

- Transaction hash:

D8736B557F1A9B2A32A3A591E5869C6AEB8A20241DD2B2D2D1226F29CEB42A75

- Wallet address:

thor1dzj4zdvqxsr3yv3q6k9jgx0nd3l88prm7x3vcn

Thanks for your support.

**Comment by bullishtrader** [comment]
Hello, FYI i have still 2 users waiting to withdraw their funds from the LP.
is there anything they can do to withdraw the funds?

Are you guys aware of any solution?

Thanks again for your support.

**Comment by veado** [comment]
@bullishtrader Thanks for letting us know about this issue! We had a similar issue in the past (ask @thorchain-admin to search for such error message in our previous Slack and he will see some discussions about it). We fixed it by increasing max gas in `xchain-thorchain` to `10000000` (see https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L531). Not sure why it does not work anymore and by checking withdraw txs in https://viewblock.io/thorchain/txs?page=1&type=unstake we have it from time to time again now. All these failing txs needed a little bit (not that much) more gas. 

Failing example:
- https://viewblock.io/thorchain/tx/1C7B6E4D5D97FF57E6F492D73373C4AE073571191A20B6D92FDC6A9266209365
- Error: "out of gas in location: ReadPerByte; gasWanted: 10000000, gasUsed: 10006851: out of gas" (see tx details https://thornode.thorchain.info/txs/1C7B6E4D5D97FF57E6F492D73373C4AE073571191A20B6D92FDC6A9266209365)

  _I'm going to reach out to the team to get more information..._

**Comment by veado** [comment]
After talking with the team we have decided to double max. `gas` from `10m` to `20m` (all done in `xchain-thorchain` https://github.com/xchainjs/xchainjs-lib/pull/358)
