### ISSUE TITLE
When sending LTC received invalid address message

### ISSUE THREAD

**Issue by mcbee08** [thorchain/asgardex-electron#1542]
## Expected Behavior

When sending LTC valid address should be recognized.

## Current Behavior

Attempted to send LTC and received message : address is invalid.  
Used web wallet and transaction went through without issue.

## Steps to Reproduce

1. Attempt to send LTC to :  LXhPifw9GmSd8EApLixzrvm8qJNSP9wRAd
2. should see red message saying address invalid
3.
4.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:
0.3.3
- Operating system and version:
windows 8
## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by unchainedio** [comment]
i also saw this when sending LTC in asgardex, had to use thorswap instead to send LTC only then did it work.

**Comment by veado** [comment]
@mcbee08 Thanks for reporting this issue, it will be fixed in #1544 and published with next release `v0.3.3`
