### ISSUE TITLE
LTC lost when trying to swap for RUNE

### ISSUE THREAD

**Issue by fred561** [thorchain/asgardex-electron#1543]
## Issue description

I sent .680836 LTC to asgardex wallet (ltc1qmz0xeqdh3pyhj4fj68relf4sgp6ucruda5qz2t)  on June 13 at 5:19am MST United States (more or less 12 hours ago). Shortly after I attempted to swap for RUNE. I got a message to the effect "insufficient funds to do the swap". When I went back to my wallet, the LTC was gone but no RUNE had been added to my RUNE wallet.

I sent .2979989 LTC to asgardex wallet  (ltc1qmz0xeqdh3pyhj4fj68relf4sgp6ucruda5qz2t) on June 13 at 2: 57pm MST United States (more or less  2 hours ago). The results were the same: error message, LTC gone, no RUNE added.

Here are the transactions from blockchair.com:

https://blockchair.com/litecoin/address/ltc1qmz0xeqdh3pyhj4fj68relf4sgp6ucruda5qz2t

I had successfully swapped BTC for RUNE on June 4. Neither of the attempted LTC swaps show up here:

https://thorchain.net/#/address/thor1ny4d4a20k6v7hfugxetd5k96f82wufnutzsqy7

Is there anyway to recover my coins?

Thanks.

## Your Environment

- ASGARDEX desktop version: Linux Mint 20 

- Operating system and version: Asgardex v0.2.1

- Transaction hash(es):

- Wallet address(es):

**Comment by veado** [comment]
@fred561 What are the steps you have tried to swap in ASGARDEX? 

Both of your "swap" transactions went to `ltc1q3awehhw5ma6vn8unfx8qm2044tfvfp2dac52tc`, which seems not to be a valid vault. This address just received your both txs and still hold the amount if it. Also both "swap" transactions don't include a memo in it's raw data, which is needed for a swap. Another note: You still run an older version `v0.2.1` of ASGARDEX, pls update to latest version [v0.3.3.](https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.3)

**Comment by fred561** [comment]
Thanks for your response!

I took these swap steps: 
Clicked POOLS tab > clicked the LTC SWAP button > set top coin to LTC > set bottom coin to RUNE > clicked SWAP

I am now running v0.3.3

How do I get my LTC back from the invalid wallet (ltc1q3awehhw5ma6vn8unfx8qm2044tfvfp2dac52tc)? Can you provide step by step instructions?

Thanks!

**Comment by veado** [comment]
@fred561 
> Clicked POOLS tab > clicked the LTC SWAP button > set top coin to LTC > set bottom coin to RUNE > clicked SWAP

I've just run a similar SWAP in a same order and the swap went through without any issues.

> How do I get my LTC back from the invalid wallet (ltc1q3awehhw5ma6vn8unfx8qm2044tfvfp2dac52tc)? Can you provide step by step instructions?

The address `ltc1q3awehhw5ma6vn8unfx8qm2044tfvfp2dac52tc` has been double checked by the team, but that's not a vault address of THORChain. Please note: Before sending a swap transaction, ASGARDEX checks always the receiver address (which should be a valid pool address) by comparing it with latest addresses in https://thornode.thorchain.info/thorchain/inbound_addresses. In case of an invalid address (such as `ltc1q3awehhw5ma6vn8unfx8qm2044tfvfp2dac52tc`) it would throw an error, but not sending the transaction. Also all of your transactions are missing a memo such as `SWAP:THOR.RUNE:{thor-address}`, which would be added by ASGARDEX as well.

One reason for this issue might be sending such transaction manually, but in a wrong way and not by using swap interface of ASGARDEX. I'm very sorry, but from my perspective I don't see any way to refund your LTC amounts.

**Comment by fred561** [comment]
Thanks for your speedy responses on this issue. I appreciate it.

As you can imagine, I'm quite disappointed that my LTC is lost. Not to question your perspective (only as a last grasp), is there anyone else, or a group of people that might be able to offer a second opinion? (like I said, last grasp)

What's interesting to me is that I don't even know how to send the transaction manually, and I've only used the swap interface (and only a few times). I'll still want to buy some RUNE, but maybe I'll swap BTC rather than LTC, since that worked for me before. 

Anyway, thanks again!

**Comment by veado** [comment]
> Not to question your perspective (only as a last grasp), is there anyone else, or a group of people that might be able to offer a second opinion? (like I said, last grasp)

DM @kkkilo (THORChain team member) at Telegram - maybe he can give you a second opinion - thx!

**Comment by fred561** [comment]
Hey veado!

I never got a response from @kkkilo. Might be to busy, or not interested. Would it be possible for you to check with him? If not, I understand. Thanks for your assistance.

**Comment by kkkilo** [comment]
> > Not to question your perspective (only as a last grasp), is there anyone else, or a group of people that might be able to offer a second opinion? (like I said, last grasp)
> 
> DM @kkkilo (THORChain team member) at Telegram - maybe he can give you a second opinion - thx!

Hey bro,  I'm sorry I don't know you. Maybe you are confusing me with someone else!

**Comment by fred561** [comment]
Sorry for the bother! No harm intended! Have a good day!

**Comment by veado** [comment]
@fred561 `@kkkilo` is the user name at Telegram - pls ping him there only (not here). _Sorry if the information might be confusing..._

**Comment by fred561** [comment]
Not a problem, veado. I did ping him on Telegram, but didn't hear back from him. I'll go ahead and close the ticket. Thanks!

**Comment by veado** [comment]
> I did ping him on Telegram, but didn't hear back from him

@fred561 Let me ping him as well. _Thank you for your patience_
