### ISSUE TITLE
BTC Pool deposit, shows no shares after.

### ISSUE THREAD

**Issue by Zunthras** [thorchain/asgardex-electron#1550]
Bitcoin / RUNE Pool deposit issue

## Issue description

This morning the cap was raised and I attempted to deposit some bitcoin & RUNE into the pool.  Not my full balance, just 0.00294477 BTC.
The transaction indicated a failure regarding fees.   I didn't capture a screen shot, I figured to just adjust my deposit amount so I closed the window.  But the wallet then shows 0.00094452.  At the time no history showed and I figured with so many trying to deposit I'd wait till after the cap closed.  Now history shows a deposit, but the wallet does not show I have shares in the pool.  I did check the web version and it also shows I have no shares.   

This shows the history screen shot
![ASGARDEX-Trbl](https://user-images.githubusercontent.com/73271425/121908025-3a779700-ccf2-11eb-9fee-56e49d6051f3.jpg)

This shows the wallet balances
![ASGARDEX-Trbl2](https://user-images.githubusercontent.com/73271425/121908165-57ac6580-ccf2-11eb-80de-b2b6474a96f0.jpg)

This shows the transaction
![ASGARDEX-Trbl3](https://user-images.githubusercontent.com/73271425/121908227-68f57200-ccf2-11eb-927b-85a5d9229e4d.jpg)
I realized I cropped the memo field:  Memo(s)
ADD:BTC.BTC:thor1ktzsxh6a8jey0rtzsmj23a9rx7ujtklsqn9xrh

'copy hash' function from transaction page:
A259A698475706E07DFEC77E2A2648ECDA72BB1F4CD3BD6F565F68792BBDCD49

## Your Environment

- ASGARDEX desktop version:
0.3.3
- Operating system and version:
Windows 10
- Transaction hash(es):
A259A698475706E07DFEC77E2A2648ECDA72BB1F4CD3BD6F565F68792BBDCD49
- Wallet address(es):
BTC: bc1qk22cc653tl0wuxk9cfm6tj0w0dpe4zd5a02dqm
THOR:  thor1ktzsxh6a8jey0rtzsmj23a9rx7ujtklsqn9xrh

**Comment by veado** [comment]
By looking into https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers you still have pending assets

```json
	{
		"asset": "BTC.BTC",
		"rune_address": "thor1ktzsxh6a8jey0rtzsmj23a9rx7ujtklsqn9xrh",
		"asset_address": "bc1qk22cc653tl0wuxk9cfm6tj0w0dpe4zd5a02dqm",
		"last_add_height": 1010683,
		"units": "0",
		"pending_rune": "0",
		"pending_asset": "294477",
		"pending_tx_Id": "A259A698475706E07DFEC77E2A2648ECDA72BB1F4CD3BD6F565F68792BBDCD49",
		"rune_deposit_value": "0",
		"asset_deposit_value": "0"
	},
```

It seems your deposit was not successful due a failing tx on RUNE side. To recover your pending assets, pls follow steps as described in a previous message: https://github.com/thorchain/asgardex-electron/issues/1520#issuecomment-857489215

> The transaction indicated a failure regarding fees. I didn't capture a screen shot, 
Maybe it shows the error (failing RUNE tx) mentioned above...?

**Comment by Zunthras** [comment]
Guess I just needed to wait longer.   I had checked before I submitted this ticket via the web exchange page and it was showing no deposits and no pending.   
I checked again just now and it shows the bitcoin and I did get a successful withdraw response.

OK to close this one.
Thank you
