### ISSUE TITLE
Bitcoin deposit not arrived in wallet

### ISSUE THREAD

**Issue by thorstenahlert** [thorchain/asgardex-electron#1551]
I tried to deposit Bitcoin into my Ascardex Bitcoin wallet address 
bc1q5z09mh07ct4q24g26m2g4n7nh2fs0fhjgqussn 
I sent  0.01326387 BTC from Binance Fr., 11. Juni, 13:53. the Withdrawal from Binance was confirmed:
 txid is e5e40d409dc02bd3a78f297b1330c5d4645183b2bf029888272542977edcd11a  
Sadly up to now no asset shows in my bitcoin wallet in Ascardex. What was my mistake? Are the funds lost?
## Your Environment

- ASGARDEX desktop version:  v0.2.1

- Operating system and version: Windows 10

- Transaction hash(es): txid is e5e40d409dc02bd3a78f297b1330c5d4645183b2bf029888272542977edcd11a 

- Wallet address(es): bc1q5z09mh07ct4q24g26m2g4n7nh2fs0fhjgqussn

**Comment by thorstenahlert** [comment]
me again, I updated the Ascardex version to 0.3.3 and strangely enough the Bitcoin are now showing. So no more help needed at the moment. Thanks

**Comment by veado** [comment]
@thorstenahlert Yep, this issue of missing BTC balances has been in [v0.3.3](https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.3)
