### ISSUE TITLE
Error when removing liquidity

### ISSUE THREAD

**Issue by magari7** [thorchain/asgardex-electron#1555]
When trying to remove liquidity from thorchain (BUSD pool) I get an error saying that "Min 3 RUNE in Wallet Required", even though the fees are clearly stated to be 0.02 RUNE. I have less than 3 RUNE in my wallet and ass a result I cannot withdraw. I do have enough for the fee though.

## Prerequisites
Add liquidity to BUSD pool on thorswap.finance.

## Expected Behavior
Can withdraw the liquidity when decide to do so.

## Current Behavior
Cannot withdraw liquidity.

## Steps to Reproduce
Try to remove the liquidity having less than 3 RUNE in your wallet (but more than 0.02 RUNE so the fees can be covered)

1. Add liquidity to BUSD pool
2. Remove liquidity after a few days

## Possible Solution

Check if the user have enough RUNE for the fees. Do not request 3 RUNE without a reason

## Your Environment - Release Version (skip if not using a release version)

https://app.asgard.exchange/pool
xdefi wallet

- ASGARDEX desktop version: web version not desktop

- Operating system and version: Linux Mint 20, Brave browser

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by magari7** [comment]
![Screenshot](https://user-images.githubusercontent.com/85957707/122097258-c501e880-ce0f-11eb-81e8-33f3b4b79e40.png)

**Comment by veado** [comment]
> ASGARDEX desktop version: web version not desktop

@magari7 Could you open same issue at https://github.com/asgardex/asgard-exchange (repo of ASGARDEX web), pls? This repo here is for ASGARDEX desktop only - thank you!

**Comment by magari7** [comment]
all right
