### ISSUE TITLE
[Wallet] History: Add missing explorer link + icon for `UPGRADE` txs

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1574]
**Note:** Midgard needs to be updated before - it does not support `txId` for `switch` txs in `action` endpoints (it's still WIP - see following note in Discord #midgard channel https://discord.com/channels/838986635756044328/839002340354424842/854294552046206996)

![Screen Shot 2021-06-22 at 14 26 18](https://user-images.githubusercontent.com/61792675/123078569-65ad6500-d41b-11eb-9232-d3b770a8ab6b.png)

**Comment by gromxyz** [comment]
Looks like this one has been fixed already

<img width="951" alt="Screenshot 2021-11-01 at 13 05 46" src="https://user-images.githubusercontent.com/87367763/139668839-bb9e7e52-7db6-4ba4-a479-d7ffbf56af66.png">
