### ISSUE TITLE
[Header] Add wallet selector

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1576]
- In `Header`: Add wallet selector at same place as we currently have a network selector
- If a wallet has not been imported: Show "Add wallet" button
- If a wallet has been imported: Show a label with THOR address
- ![Screenshot from 2021-06-23 12-24-52](https://user-images.githubusercontent.com/61792675/123081245-1157b480-d41e-11eb-990b-c2effd2887c8.png)
    ^ Layout: https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=3973%3A0 

Depends on #1566 
Part of #1571

**Comment by daryazata** [comment]
Id like to start working on this issue :)

**Comment by veado** [comment]
> Id like to start working on this issue :)

@daryazata  Feel free to grab this issue ;)

> Do you have a tele-group or so for eventual questions?

A good place to ask questions is Discord (channel #asgardex-desktop) https://discord.gg/qyyN6G7Y
