### ISSUE TITLE
BTC deposit was sent to unknown wallet

### ISSUE THREAD

**Issue by fred561** [thorchain/asgardex-electron#1591]
## Issue description

I was planning to swap BTC for RUNE. Yesterday I transferred .007 Bitcoin from Binance wallet to Asgardex wallet (bc1qhz0ykrtfsuj635r8aw079dpyzuhdhdhl2q7stg). 

Transaction ID https://blockchair.com/bitcoin/transaction/1e81a8841ad9aa9cb832f1fbb92998daca1d65cca7da532514ed75a75a8dc4c0

30 minutes later someone, not me, sent my bitcoin to an unknown wallet (bc1qrfu9d02038pf45rqzg5sv56thnvqdpuq2fk5zv).

Transaction ID: https://blockchair.com/bitcoin/transaction/923bc5247118203a29d94363386afcfb997b47c91c93db36c43f40b727ae2b29

How is this possible? Is there anything to be done?

PS I don't know if it's relevant, but I created ticket #1543 last week.

## Your Environment

- ASGARDEX desktop version:  0.3.3

- Operating system and version: Linux Mint v20

- Transaction hash(es):

- Wallet address(es):

**Comment by veado** [comment]
It sounds someone has access to your phrase, keystore or computer. Make sure you have saved your phrase / keystore at a save place (not on your computer or in a cloud, but on a paper for example) and nobody you don't trust has access to it. 

Please note it's your responsibility not just to keep your computer save, but also to use your wallet in a secure way.

**Comment by fred561** [comment]
Hi veado. Maybe I wasn't meant to own RUNE...

What do you think the chances are that I had the inexplicable problem (#1543), and then the very next transaction was "stolen". Have you explored the possibility of these two issues being related? Have you explored the possibility that this is on your end?

No one has physical access to my desktop computer. I have not shared phrase or keystore with anyone. Though not ideal, my seed key is stored on my password manager (Bitwarden), with a strong Master password. I don't see how anyone could have access to it.

Anyway, there doesn't seem to be anything I can do at this point. If you can, investigate if the two tickets are related. Otherwise I'll be on my way.

**Comment by veado** [comment]
@fred561 As you know we have double checked #1543 and gave you a feedback twice (in #1543 and at Telegram by `@kkkilo`). With latest issue you describe here I can't see any relation to ASGARDEX desktop nor to the network. From my side it sounds more like a malicious actor you might not know who has access to your computer or your (private) wallet data.

**Comment by fred561** [comment]
I get it. Thanks.
