### ISSUE TITLE
converted btc into rune - funds missing

### ISSUE THREAD

**Issue by mrcosmin** [thorchain/asgardex-electron#1596]
##I've added ``220$ into the Asgardex desktop app in BTC. From there I went into the web Asgard Exchange and swapped BTC into Rune. It showed transaction completed but when I go into the desktop app I just see that the money disappeared form the BTC wallet (bc1q7zt2aqtyxe86pmg0dyu2mzh8zu54qrkznxvsya) but the thorchain wallet (thor1n0f6x4fruzxm95a4qny4grs5ypc3tfpvjn5zr3) is empty. the BTC walled shows now only 24.163 (app 1.47 rune) and before was showing 652.xxx (app 40,xx rune). please help!

## Your Environment

Windows 10

- ASGARDEX desktop version:
v0.3.5
- Operating system and version:

- Transaction hash(es):
no transaction hashes shown
- Wallet address(es):
bc1q7zt2aqtyxe86pmg0dyu2mzh8zu54qrkznxvsya
thor1n0f6x4fruzxm95a4qny4grs5ypc3tfpvjn5zr3

**Comment by veado** [comment]
Viewblock shows a successful swap for your RUNE wallet address: `0.00596374 BTC` -> `35.52576 RUNE` https://viewblock.io/thorchain/address/thor1n0f6x4fruzxm95a4qny4grs5ypc3tfpvjn5zr3. Could you double check your RUNE account in ASGARDEX desktop, pls? It might take some time for swapping BTC.
