### ISSUE TITLE
how do I get bonded rune back in asgardex desktop?

### ISSUE THREAD

**Issue by thorstenahlert** [thorchain/asgardex-electron#1597]
## Your Environment

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):
<!---Block #1045362  --
BOND:thor1fwp8z5r9qhshr280yc59lvxmy78tw09mtjymhw>
- Wallet address(es): thor1fwp8z5r9qhshr280yc59lvxmy78tw09mtjymhw

**Comment by veado** [comment]
WALLET -> RUNE -> DEPOSIT -> UNBOND
![Peek 2021-06-30 07-53](https://user-images.githubusercontent.com/61792675/123908762-47de8380-d978-11eb-8202-6a65b0a10837.gif)

Note:

> You can only unbond when your Node is on "standby", ie, just before it is selected to churn in, or after it is churned out. 
> You cannot unbond if you are "ready" or "active" or have any amount of funds on your Yggdrasil address

^ https://docs.thorchain.org/thornodes/leaving#unbonding
