### ISSUE TITLE
Support the lightening network

### ISSUE THREAD

**Issue by paju1986** [thorchain/asgardex-electron#1678]
It would be great if the lightnening network can be supported for receiving/sending bitcoin on the wallet.

Thanks you!

**Comment by veado** [comment]
@paju1986 Pls open an issue for `xchain-bitcoin`, which is the library ASGARDEX (and other front-ends) is using behind the scenes for handling BTC transactions etc. https://github.com/xchainjs/xchainjs-lib/tree/master/packages/xchain-bitcoin
