### ISSUE TITLE
Money Vanished after trying to exchange BTC for rune...

### ISSUE THREAD

**Issue by latao3450** [thorchain/asgardex-electron#1708]
I tried to use the exchage to buy rune and my BTC vanished and I got nothing..
## Your Environment

Asgardex Desktop for Macos. Macbook Pro 13 M1

- ASGARDEX desktop version:
0.1.0
- Operating system and version:
12.0 osx beta Monterey
- Transaction hash(es):
https://blockstream.info/tx/607016cdd5307fbfe0fa43dcdb3be3e4f9fa38f747e0d0002e8be510865d2eb6
- Wallet address(es):
- BTC: bc1qxquq58rpqty6wqfu66lddupk6d08l76d44al74
- Rune: thor1wny0qtj4wfhmcrhy6dnzxhe0cx5d6cqey2zuwa

**Comment by veado** [comment]
Trading has been halted for few weeks and with `v0.1.0` you are using a deprecated version of ASGARDEX (latest version is [v0.3.13](https://github.com/thorchain/asgardex-electron/releases/tag/v0.3.13)). _I will reach out to the team to see if we can do anything ..._

**Comment by veado** [comment]
@latao3450 Unfortunately we can't do anything at the moment, that's what I got from the team :arrow_down:  
> "...he has to wait until btc is re-enabled, in which the trade will go through or get refunded"

Pls never use an outdated software, your ASGARDEX version [0.1.0 was released on April 13th](https://github.com/thorchain/asgardex-electron/releases/tag/v0.1.0). Using one of the latest versions would keep you away from such accident.
