### ISSUE TITLE
[Swap] Incorrect explorer link in swapping dialog

### ISSUE THREAD

**Issue by gromxyz** [thorchain/asgardex-electron#1787]
## Prerequisites
Swap ETH -> BNB on testnet

## Expected Behavior

Show dialog with explorer link

## Current Behavior

Shows dialog with explorer link which points to viewblock.io with address provided as tx
<img width="570" alt="Screenshot 2021-09-23 at 11 46 42" src="https://user-images.githubusercontent.com/87367763/134486877-cdd203aa-fdd1-47c6-9262-f9499f100682.png">

<img width="1013" alt="Screenshot 2021-09-23 at 11 49 25" src="https://user-images.githubusercontent.com/87367763/134487254-a0d4ac6e-ccc5-4d1c-a59f-7eb1f40b69fc.png">

**Comment by veado** [comment]
The hash given to viewblock url is a tx hash (not an address). 

Example ETH -> BNB:

- SwapView in ASGARDEX
![Screenshot from 2021-09-30 14-39-58](https://user-images.githubusercontent.com/61792675/135456648-3923b587-6620-4b7b-b06c-5f5988fcd761.png)
- Etherscan https://ropsten.etherscan.io/tx/0xd52229f8725bac592d1c9f5d6c20e630bbee8e5886afca674adae3ed35641aed
- THORChain Explorer: https://testnet.thorchain.net/#/txs/0xd52229f8725bac592d1c9f5d6c20e630bbee8e5886afca674adae3ed35641aed
- Viewblock (still missing) https://viewblock.io/thorchain/tx/0xd52229f8725bac592d1c9f5d6c20e630bbee8e5886afca674adae3ed35641aed?network=testnet

It might be an issue on `viewblock`.

**Comment by veado** [comment]
Link in Wallet -> History point to final tx, which is accessible at `viewblock`

![Screenshot from 2021-09-30 14-46-04](https://user-images.githubusercontent.com/61792675/135457554-601c4edc-42bb-4881-99cd-019ba9920b2f.png)

**Comment by veado** [comment]
_Asking `viewblock` team_ https://discord.com/channels/838986635756044328/846612413477945384/893125413834997850

**Comment by veado** [comment]
`0x` needs to be remove from tx hash in case of ETH to get valid an URL for `viewblock`. 
^ (see https://discord.com/channels/838986635756044328/893125413834997850/893371319733874728)

Example: https://viewblock.io/thorchain/tx/fc3fe5f9352d03dfbcacd5d47dace2e5d2862c16b986bf900a041166b3e36916?network=testnet
