### ISSUE TITLE
Swaps are duplicated

### ISSUE THREAD

**Issue by bitedgecom** [thorchain/asgardex-electron#1872]
## Prerequisites

Swapping RUNE for BTC

## Expected Behavior

Submit a single swap and have it happen once

## Current Behavior

2 out of the last 3 swaps have submitted have been duplicated and the swap has happened twice. I have 2 recent real life examples but sharing them here would be a privacy leak.

## Steps to Reproduce

1. Submit a single swap, in my case RUNE > BTC
2. Check history
3. Not all swaps are duplicated but some are

## Possible Solution

I do not know of any.

## Your Environment

ASGARDEX desktop version:
Mac v0.4.4

Operating system and version:
Mac OS 10.15.7

**Comment by veado** [comment]
Closing this issue for now. fFel free to re-open it if you still see same issue, thx.
