### ISSUE TITLE
Swap interface outputs "SWAP ERROR REQUEST FAILED WITH STATUS CODE 404" but swap went through fine

### ISSUE THREAD

**Issue by bitedgecom** [thorchain/asgardex-electron#1915]
## Prerequisites

Make a Swap

## Expected Behavior

Swap either works, or if it does not work displays an error

## Current Behavior

Swap works AND displays an error

> SWAP ERROR REQUEST FAILED WITH STATUS CODE 404

<img width="611" alt="Screen Shot 2021-10-31 at 09 43 10" src="https://user-images.githubusercontent.com/7556992/139565634-024ec2ad-29a2-4b84-b2b2-39364c5f9a63.png">

## Steps to Reproduce

1. Make a swap
2. Observe error message saying swap did not work
3. Go to transaction history and see the swap did work

## Possible Solution

I am more of an ideas man ;)

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:

- Operating system and version:

## Your Environment

ASGARDEX desktop version:
Mac v0.4.5

Operating system and version:
Mac OS 10.15.7

**Comment by veado** [comment]
Any swap transaction is sent from ASGARDEX to https://thornode.thorchain.info (mainnet)  or https://testnet.thornode.thorchain.info (testnet). In case of `404` this node seems to be offline or not available for some reason.

**Comment by veado** [comment]
Closing this issue for now. Feel free to re-open it in case of same issue.
