### ISSUE TITLE
Enable Ledger for Add/Withdraw Liquidity to pools

### ISSUE THREAD

**Issue by paju1986** [thorchain/asgardex-electron#1923]
Now we have ledget support for swaps wich is nice but if i want to add liquidity to a pool i have to move funds from my ledger accout to the main keystore account. It will be nice if you can add/withdraw funds directly from the ledger account.

**Comment by gromxyz** [comment]
Makes sense. Added to #1925 backlog for the next milestone. Thanks for suggestion 👍

**Comment by veado** [comment]
Closing in favour of #1925
