### ISSUE TITLE
Unable to send out get Error Code 404 via ether

### ISSUE THREAD

**Issue by pantheons62** [thorchain/asgardex-electron#1924]
Received Error Code 404 when sending out to address below via ether
Second attempt
Receive error code Insufficient funds now !!!! when doing a send  to 
 Your system has a lot of bugs ???
( see attach screen shot )

I have already lost crypto with you guys and it seem you will not let go the rest of my pennies
please try and fix your issues

- ASGARDEX desktop version: 5.0

- Wallet address(es):0x200a34dab5ce21363d0b27c68d2017bb8d8d43ce
![Screenshot 2021-11-01 215914](https://user-images.githubusercontent.com/85649785/139774602-dbe29a46-82c3-4fd9-a8ca-a15a7fa19a36.gif)

**Comment by pantheons62** [comment]
hash # Address 0x9C02679CCA11AD94044083F9b9a161571ACf5468 
Address 0x9C02679CCA11AD94044083F9b9a161571ACf5468
Overview
Balance:
0.605407993943723645 Ether
Value:
$2,613.59 (@ $4,317.07/ETH)

**Comment by veado** [comment]
I can't see all details of the error message, but it says: "Insufficient funds for gas". That means balances of selected account does not have enough value to cover gas cost. However, by checking your account https://etherscan.io/address/0x9C02679CCA11AD94044083F9b9a161571ACf5468 it should not the case. Pls try the following: Re-start ASGARDEX, select `fastest` or `fast` option (see screen shot) in `Wallet` -> `Asstes` -> `ETH` -> `Send` to make sure gas will be covered for ETH transactions. 

![send-fee-option](https://user-images.githubusercontent.com/61792675/139940613-2e96722c-165b-4b3f-9600-8ef28d2007bf.png)

**Comment by pantheons62** [comment]
Thanks for this fast response , Yes I tried it out again and it worked this time..wow really expensive for sending out over 200.00 , plus not able to take out the full amount ??

Thxs
Rob

Sent from ProtonMail for iOS

On Tue, Nov 2, 2021 at 3:48 PM, veado ***@***.***>

**Comment by veado** [comment]
It's not unusual to pay around $15 for ETH transactions as you did with your last transaction. 

For further user support please reach out to THORChain's Discord https://discord.gg/KJnwz6gk (channel #asgardex-desktop), pls. _Closing this issue for now_
