### ISSUE TITLE
BTC ERROR: INSUFFICIENT BALANCE FOR TRANSACTION 

### ISSUE THREAD

**Issue by paju1986** [thorchain/asgardex-electron#1934]
I get the following message when trying to swap or send my BTC from my keystore wallet

ERROR: INSUFFICIENT BALANCE FOR TRANSACTION

**Comment by veado** [comment]
Could you share more details (if possible)? 

- How much is the estimated fee for BTC?
- How much balance do you have in your wallet? 
- What's your BTC wallet address?
- Screen shot?
- ASGARDEX version?
- Mainnet / testnet?

Pls don't remove the content of the bug template add more information. Thx!

**Comment by paju1986** [comment]
Sorry, i needed to withdraw my btc so i imported the seed phrase into electrum and sent my btc that way, i no longer have any btc on asgardex wallet.

**Comment by veado** [comment]
Ok, closing this issue for now. Feel free to re-open it again in case you will run into this issue again. Thx.
