### ISSUE TITLE
Is it possible to use this wallet with ThorChads?

### ISSUE THREAD

**Issue by comanche** [thorchain/asgardex-electron#1945]
Hello,

Is it possible to use this wallet with ThorChads or do I need to transfer my RUNE to something like TrustWallet?

Thanks

**Comment by comanche** [comment]
When you go to https://thorchads.com/, you can connect your wallet.

**Comment by veado** [comment]
Try to connect THORChads with the keystore you are using in ASGARDEX. 

![Screenshot from 2021-11-19 14-15-55](https://user-images.githubusercontent.com/61792675/142629471-31adc51b-698b-4a5f-9cb2-705157d23acc.png)


To export your keystore from ASGARDEX, go to `Wallet` -> `Settings` -> `Export Keystore` 

![Screenshot from 2021-11-19 14-19-40](https://user-images.githubusercontent.com/61792675/142629492-008ef8ed-05af-4303-90b6-25413d015bb1.png)

**Comment by comanche** [comment]
Thanks.  I will try that.  In the mean time...  what's a keystore?  Is that like an account address that can be shared without any security risk?

**Comment by veado** [comment]
A keystore is a JSON file with an encrypted version of the private key of your wallet. This key is encrypted with a password you have defined before (e.g. by creating a wallet in ASGARDEX or anywhere else). Don't share this keystore file with anybody. Even by protecting it with a password it might be possible to brute force private keys. 

For more questions please join THORChain's Discord #general or #asgardex-desktop channel https://discord.gg/e9dBQDFE.

**Comment by comanche** [comment]
> A keystore is a JSON file with an encrypted version of the private key of your wallet. This key is encrypted with a password you have defined before (e.g. by creating a wallet in ASGARDEX or anywhere else). Don't share this keystore file with anybody. Even by protecting it with a password it might be possible to brute force private keys.
> 
> For more questions please join THORChain's Discord #general or #asgardex-desktop channel https://discord.gg/e9dBQDFE.

So then would it be safe to export the Keystore from ASGARDEX and use it to connect on thorchads.com?

**Comment by veado** [comment]
If can trust thorchads.com, then it's save.
