### ISSUE TITLE
ThorStarter and Thorswap issue

### ISSUE THREAD

**Issue by LatinAussie** [thorchain/asgardex-electron#1976]
## Your Environment

Thor Starter and ThorChain

- ASGARDEX desktop version:

- Operating system and version:

- Transaction hash(es):D45174AC77097F6811803F489E0E6851A28B368723AA30A4C9AC7F873673EB21

- Wallet address(es):

**Comment by veado** [comment]
@LatinAussie It seems your tx was sent using THORSwap, right? Pls join THORSwap Discord https://discord.gg/fg6RrdKy to get help from there - thank you!
