### ISSUE TITLE
[Send] Sending max. amount still failing (ETH, BTC)

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#1986]
Reported by users for ETH / BTC. Discord thread https://discord.com/channels/838986635756044328/839002220942721024/921282826417106984

**Comment by veado** [comment]
After double check ETH deeply:

- `gas_rate` is loaded from `inbound_addresses` properly
- Fees are calculated properly from `gas_rate`
- Fees are deducted properly from balances to get `max` value
- Fees are re-calculated properly using different fee types `average`|`fast`|`fastest`. 
- Comparing to MetaMask fees are still higher (even by using `average` fee type). With that, `max` value is less comparing to MetaMask's `max` and txs should go throw with it.

**Comment by bhaktar** [comment]
Give sthe same Error in Version 0.6.0 on Windows 10 Home 64Bit that in older version after trying to send max ETH:
ERROR: INSUFFICIENT FUNDS FOR INTRINSIC TRANSACTION COST (ERROR={"REASON":"PROCESSING RESPONSE ERROR","CODE":"SERVER_ERROR","BODY":"{\"JSONRPC\":\"2.0\",\"ID\":44,\"ERROR\":{\"CODE\":-32000,\"MESSAGE\":\"INSUFFICIENT FUNDS FOR GAS * PRICE + VALUE\"}}","ERROR":{"CODE":-32000},"REQUESTBODY":"{\"METHOD\":\"ETH_SENDRAWTRANSACTION\",\"PARAMS\":[\"##CENSORED by BUG REPORTER##\"],\"ID\":44,\"JSONRPC\":\"2.0\"}","REQUESTMETHOD":"POST","URL":"HTTPS://MAINNET.INFURA.IO/V3/84842078B09946638C03157F83405213"}, METHOD="SENDTRANSACTION", TRANSACTION="##CENSORED by BUG REPORTER##", CODE=INSUFFICIENT_FUNDS, VERSION=PROVIDERS/5.4.5)

**Comment by veado** [comment]
Seems to be fixed by following PRs (all about updates of fee handling): #1978 (ETH), #2326 (all chains), #2140 (BTC).

In case anyone runs into this issue again feel free to re-open this issue.
