### ISSUE TITLE
ADD: Stagenet

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#1987]
- [x] Stagenet wallet variable
- [x] Stagenet Midgard baseURL `stagenet.midgard.ninerealms.capital`
- [x] When stagenet, init `xchain-thorchain` into `stagenet`, load all others into `mainnet`
- [x] Disable THORChain ledger when in stagenet (since does not support)

**Comment by veado** [comment]
Resolved by #2000
