### ISSUE TITLE
Second share not showing

### ISSUE THREAD

**Issue by paju1986** [thorchain/asgardex-electron#1995]
## Expected Behavior

I have 2 shares on 2 pools and they should both be shown on the shares tab, this worked before on version 0.5.0
## Current Behavior

Since version 0.6.0 I have 2 shares on 2 pools but on the shares tab only shows one of the pools

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:
0.6.0
- Operating system and version:
 Manjaro Linux  Appimage

**Comment by veado** [comment]
@paju1986 Is one of your shares an `asym` share? With `0.6.0` `sym` shares are supported in  `wallet` -> `shares` only. Before (< `0.5.0`) `asym.` shares were included as well. If you want, you can DM me via Discord your addresses to do a double check.

**Comment by veado** [comment]
@paju1986 Confirmed, it's a bug in ASGARDEX. In case of more than one LP on a chain, only one LP is shown in `wallet` -> `shares`, but the others are ignored. It will be fixed with next release. Thanks again for reporting this issue!
