### ISSUE TITLE
Ledger displays a 5.0 RUNE depositing fee when using the Custom deposit feature from the wallet screen

### ISSUE THREAD

**Issue by severinwullschleger** [thorchain/asgardex-electron#1996]
Hi

not 100% sure if it is a bug. but I couldn't find anywhere that a fee of 5.0 RUNE was deducted.

When depositing from Asgardex with the Ledger the Ledger desplays a Fee of 5.0 RUNE. but i think 5.0 RUNE are not deducted instead the normal 0.2 RUNE. But I was very confused.

## Prerequisites

Ledger connected to Asgardex

## Expected Behavior

Ledger shows Fee 0.2 RUNE

## Current Behavior

Ledger shows Fee 5.0 RUNE

## Steps to Reproduce

1. go to RUNE wallet
2. choose Deposit and "Custom"
3. add a memo for depositing to a pool
4. click on send

## Possible Solution

Do not pass the wrong fee.

## Your Environment - Release Version (skip if not using a release version)
Ledger Nano S

- ASGARDEX desktop version:
0.60.0
- Operating system and version:
- macOS

**Comment by veado** [comment]
> LedgerHQ advises it will be after xmas "early next year" they will do security review of v2.0.2 (that fixes incorrect Fee display) and push to LedgerLive. There's nothing wrong with the current version - it's just annoying the fee is incorrect and shows Cosmos Gas (which isn't a fee). Next version just hides that field. Otherwise nearly identical. It's safe to keep using current version.

^ https://discord.com/channels/838986635756044328/850210159636512801/921533090055208980
