### ISSUE TITLE
Trouble Sending BTC - getting Insufficient balance

### ISSUE THREAD

**Issue by Davebrkfld** [thorchain/asgardex-electron#2020]
## Your Environment

- ASGARDEX desktop version:
 win.exe
- Operating system and version:
 Win 10  64
- Transaction hash(es):

- Wallet address(es):  BTC  -  bc1qpeqyxmv99aulxgrx86w7c4ypzleu4z4jxmscha

**Comment by veado** [comment]
You can't send anything if the balance of your [bc1qpeqyxmv99aulxgrx86w7c4ypzleu4z4jxmscha](https://live.blockcypher.com/btc/address/bc1qpeqyxmv99aulxgrx86w7c4ypzleu4z4jxmscha/) address is 0 BTC.
