### ISSUE TITLE
Can't  withdraw / Send my Dogecoin

### ISSUE THREAD

**Issue by Leif314** [thorchain/asgardex-electron#2049]
Can not Send Dogecoin back to my other address. Failure either : Value error or out of Range .

Win 10 46 bit 

- ASGARDEX desktop version:
ASGARDEX-0.7.1-win.exe
- Operating system and version:
Win 10 46 bit 

DHA9LHzh72dbVNqiiGdpintWQ9tL416nQw

**Comment by veado** [comment]
Where do you see this kind of error? Can you share a screen shot?

**Comment by Leif314** [comment]
![Screenshot 2022-01-26 140550](https://user-images.githubusercontent.com/86357113/151168417-9956942d-b578-412e-9e07-5e6809ef20e4.png)
![Screenshot 2022-01-26 140652](https://user-images.githubusercontent.com/86357113/151168421-231f021c-5dd6-4602-be2e-ddb2d39e3bf7.png)
![Screenshot 2022-01-26 140728](https://user-images.githubusercontent.com/86357113/151168423-374c9054-681b-40e7-b842-601ae066c11c.png)

**Comment by veado** [comment]
For the first error: "Insuffient for transaction": Did you try to send `max` amount? In this case, try to send 1 or 2 DOGE less to cover fees. In case you've tried to send a very small amount, try more than 2 DOGE. 

For the second "rangeerror" error: Did you try to send 200 DOGE to itself? `DHA9...6nQw` seems to be same address as you mentioned in the description.

If you still have problems, feel free to DM at Discord (#asgardex-desktop channel) https://discord.gg/PXhHHDHs

**Comment by Leif314** [comment]
Thank you.
For the first error: "Insuffient for transaction": Did you try to send max amount? In this case, try to send 1 or 2 DOGE less to cover fees. In case you've tried to send a very small amount, try more than 2 DOGE.
Yes i tried that.

DHA9...6nQw is the adress to where i want to send it. The Asgardex address is

**Comment by Leif314** [comment]
![Screenshot 2022-01-26 142530](https://user-images.githubusercontent.com/86357113/151171103-b8d2de68-db12-46fb-b34c-5dfe7a5b18b2.png)
![Screenshot 2022-01-](https://user-images.githubusercontent.com/86357113/151171109-eacb5ebb-18ab-49b2-ac02-7c0d9d1137d2.png)

**Comment by veado** [comment]
Can you join Discord (#asgardex-desktop channel or DM there) https://discord.gg/PXhHHDHs to continue conversation?

**Comment by veado** [comment]
By working with Leif314 together, we could not figured out what the reason for the "rangeerror" issue is nor to re-produce this issue for other accounts. We will still keep an eye on this and let this issue open. FYI: The user (Leif314) could withdraw his funds using Trustwallet at the end.
