### ISSUE TITLE
Support Connect Throught Tor

### ISSUE THREAD

**Issue by paju1986** [thorchain/asgardex-electron#2093]
For Privacy reasons i think it would be important to be able to connect throught Tor to the backed APIs so your wallet addressed cant be associated to your Ip.

Regards!

**Comment by veado** [comment]
@paju1986 Have you tried to use a VPN provider? For example [ProtonVPN](https://protonvpn.com/secure-vpn/tor-over-vpn) let you re-route traffic through the Tor network.

**Comment by veado** [comment]
Closing due inactivity ...
