### ISSUE TITLE
UST liquidity pool

### ISSUE THREAD

**Issue by YVRTrader** [thorchain/asgardex-electron#2169]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
attempted to add small liquidity to new UST/RUNE pool.   UST tokens left my wallet but RUNE didn't.   UST tokens have disappeared.   Any support to retrieve this would be appreciated

**Comment by YVRTrader** [comment]
> attempted to add small liquidity to new UST/RUNE pool. UST tokens left my wallet but RUNE didn't. UST tokens have disappeared. Any support to retrieve this would be appreciated

https://finder.terra.money/mainnet/tx/DF4546E802854BCE98E12096CFE5D383BAA63F7ECECDC866A25A118BA798ECCB
TX for UST

**Comment by veado** [comment]
ASGARDEX does not support UST (yet).
