### ISSUE TITLE
URL to thoryield.com analytics is incorrect

### ISSUE THREAD

**Issue by mvpratt** [thorchain/asgardex-electron#2182]
## Expected Behavior

After clicking "Analytics", the user should be directed to https://app.thoryield.com/accounts?thor=<account> to see their liquidity positions and gain/loss.

## Current Behavior

The user is instead directed to https://app.thoryield.com/dashboard?thor=<account>  , the account number is ignored and user sees the /dashboard overall network statistics

## Steps to Reproduce

1. Click Wallet
2. Click Shares
3. Click Analytics

## Possible Solution

One-liner fix in PoolShareView.tsx

```
-      O.map(([thorAddress, _]) => `https://app.thoryield.com/dashboard?thor=${thorAddress}`),
+      O.map(([thorAddress, _]) => `https://app.thoryield.com/accounts?thor=${thorAddress}`),
```

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version:
0.11.0

- Operating system and version:
MacOS

**Comment by veado** [comment]
Thanks for reporting and adding a ready-to-use-fix, @mvpratt! Feel free to open a PR in case anything else needs to be fixed by another one-liner :sweat_smile:
