### ISSUE TITLE
BUG: Mac Ledger Index1+ broken

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#2191]
ASGARDEX: V0.12.2
LedgerLive: v2.39.2
Firmware: 2.1.0
THORChain App: 2.0.2 (expert mode disabled)
MacOS: Monterey v12.3.1 (Apple M1)

Index0 works for both Send and Deposit. 
Index1+ broken with timeout error.

**Comment by veado** [comment]
Worked by another check - seems to be a node (rpc) timeout before.
