### ISSUE TITLE
Can i use Asgardex to take custory of BINANCE-chain RUNE ?

### ISSUE THREAD

**Issue by AncientSion** [thorchain/asgardex-electron#2225]
Basically i made the stupid error of buying RUNE on Binance a while back and now i want to withdraw them. I noticed that Binance also allows RUNE withdrawal on their BNB Chain.
Ideally i would want to take hold my RUNE and somehow convert or bridge them into proper, native, RUNE.

I checked for wallets and this is the only desktop wallet i found. I do not want a browser extension nor mobile wallet (say xdefi).

Please advise ?
- thanks

**Comment by veado** [comment]
AncientSion You can use ASGARDEX to switch your BNB.RUNE (that's the RUNE you have paid at Binance) to Native RUNE as follow:

_If you have not used ASGARDEX before:_
- Download + install ASGARDEX from official release page only https://github.com/thorchain/asgardex-electron/releases
- Create a new keystore account: `Wallet` -> `Create`. Don't forget to notice the phrase on a safe place.

_How to switch from BNB.RUNE to Native RUNE:
- Send your BNB.RUNE from Binance to your ASGARDEX' BNB address - you see the address in `Wallet` -> `Settings` -> `Account Management`. Note: You do need also send a small amount (> 0.00011250 BNB) of BNB to this address (needed for switching - see next step)
- To switch to Native RUNE go to `Wallet` -> `Assets` -> `Binance Chain`. At row `RUNE / BNB` click `UPGRADE`. Enter an amount you want to switch and an address you want to receive Native RUNE (it's your ASGARDEX keystore address by default)

**Comment by AncientSion** [comment]
I got it. Thanks a lot. This can be closed.
