### ISSUE TITLE
White screen with Ledger Terra wallet connected

### ISSUE THREAD

**Issue by jeffdgr8** [thorchain/asgardex-electron#2227]
## Expected Behavior

Assets and Swap screens should load normally, using Ledger Terra wallet.

## Current Behavior

A white screen displays.

## Steps to Reproduce

1. Connect Ledger Terra wallet
2. Go to Wallet->Assets or Pools->Swap screen
3. A blank white screen appears

## Your Environment - Release Version

- ASGARDEX desktop version: V0.14.0

- Operating system and version: Windows 10

**Comment by veado** [comment]
@jeffdgr8 Double check: What do you mean by `1. Connect Ledger Terra wallet`? Does it mean you have opened Terra app on Ledger and Terra Ledger account added in `wallet` -> `settings` before?

**Comment by jeffdgr8** [comment]
@veado thanks for looking into this.

(1) Yes, open Terra app on Ledger, Wallet -> Settings -> Terra Add Ledger.
(2) Only one Ledger connected and no other apps in use (just confirmed with browser closed and only ASGARDEX running).
(3) Ledger Nano X
(4) 2.0.2
(5) 1.2.0

Maybe it's something specific to my Terra wallet? Are there logs I could check? Would it help for me to run a development version?

**Comment by veado** [comment]
> Are there logs I could check? Would it help for me to run a development version?

@jeffdgr8 Production release does not provide logs, but by running development version you will see what might be wrong. Are you able to build / run it locally as described in README https://github.com/thorchain/asgardex-electron#install? Feel free to join Discord https://discord.gg/pHcS67yX7Z (#asgardex-desktop channel) to get more help and to continue discussion there.

**Comment by veado** [comment]
Fixed by #2232
