### ISSUE TITLE
Blank screen on MacOS with terra (Ledger)

### ISSUE THREAD

**Issue by crstin** [thorchain/asgardex-electron#2238]
## Prerequisites

Latest software as of this date

## Expected Behavior

LP or swap working

## Current Behavior

You get a blank screen

## Steps to Reproduce

Add ledger wallet for terra, click pools then manage or swap

<img width="1840" alt="Screen Shot 2022-05-02 at 9 18 20 AM" src="https://user-images.githubusercontent.com/24467004/166199118-23d76e0c-87e6-4a72-a293-9b75a9ddebb2.png">

**Comment by veado** [comment]
Duplicated by #2227 + fixed by #2232 (available with next release this week)
