### ISSUE TITLE
issue with Addliquidity (Eth deposit) from ASgardex: transaction pending for 2 days 

### ISSUE THREAD

**Issue by spa-bol** [thorchain/asgardex-electron#2341]
## Issue description
Hello,
I sent 2 days ago (from my ASgardex desktop application) 0,20404949 eth  to the contract adress : 0xd37bbe5744d730a1d98d8dc97c42f0ca46ad7146. My eth adress on ASgardex is: 0xccb54ace71137ef94efee5cb12875ab7ca1c229c. In the application i see my deposit in the pool ETH.ETH is NULL, I don't see my 0,20404949 eth. 
The transaction hash on thorchain mainnet is : 06C95B9F60ECE416F0F58712AAEDDF9E963ADDAD85A1F1851E22F13DB98962E8 see screenshot hereunder.
![image](https://user-images.githubusercontent.com/110551286/182646605-20237217-f5e9-47a3-9afb-0fd856b49fe8.png)

Note that on etherscan, the transaction is shown as completed, the 0.20404949 ETH have been successfully transfered to the contract adress. 

What happened ? thanks for your time and consideration.

## Your Environment
- ASGARDEX desktop version:
MIDGARD
VERSION
v0.1.0
- Operating system and version:
Windows 11 Famille - version 22H2

- Transaction hash(es):
06C95B9F60ECE416F0F58712AAEDDF9E963ADDAD85A1F1851E22F13DB98962E8 
- Wallet address(es):
0xccb54ace71137ef94efee5cb12875ab7ca1c229c

**Comment by veado** [comment]
Can't see any pending transaction or asset.
- Viewblock https://viewblock.io/thorchain/tx/06C95B9F60ECE416F0F58712AAEDDF9E963ADDAD85A1F1851E22F13DB98962E8

```
	{
		"asset": "ETH.ETH",
		"rune_address": "thor1xx429vcgdvjth74j03mkghdq2dydhaz6w8z035",
		"asset_address": "0xccb54ace71137ef94efee5cb12875ab7ca1c229c",
		"last_add_height": 6761280,
		"units": "5617751796",
		"pending_rune": "0",
		"pending_asset": "0",
		"rune_deposit_value": "12408473974",
		"asset_deposit_value": "19671113"
	},
```
^ https://thornode.ninerealms.com/thorchain/pool/ETH.ETH/liquidity_providers

If you do need more help join Discord please https://discord.gg/pHcS67yX7Z (`#asgardex-desktop`)
