### ISSUE TITLE
ASGARDEX shows 404 error for Cosmos wallet using Keystore

### ISSUE THREAD

**Issue by BlockNgine** [thorchain/asgardex-electron#2377]
## Expected Behavior

200 OK

## Current Behavior

404 Not Found

## Steps to Reproduce

1. Open ASGARDEX, 
2. load a Keystore wallet

## Possible Solution

Load balance/healthcheck RPC servers using cosmos.directory

**Comment by BlockNgine** [comment]
https://cosmos.directory/cosmoshub/nodes

**Comment by BlockNgine** [comment]
this URL is a proxy URL that will do healthchecking for us `https://rpc.cosmos.directory/cosmoshub`

**Comment by veado** [comment]
Fixed by https://github.com/thorchain/asgardex-electron/pull/2375

Unfortunately `https://rpc.cosmos.directory/cosmoshub` does not work for `xchain-cosmos`. It does need a single `lcd` url (not a list of different endpoints).
