### ISSUE TITLE
The "name" of the current release (1.18.0) is "v0.18.0" instead of "v1.18.0"

### ISSUE THREAD

**Issue by IeP4nieF** [thorchain/asgardex-electron#2388]
## Expected Behavior

Going to [api](https://api.github.com/repos/thorchain/asgardex-electron/releases) the "name" of the current release (no. "0" in the list of releases) should be "v1.18.0" instead of "v0.18.0".

## Current Behavior

see above: "name" is "v0.18.0" instead of "v1.18.0".

## Steps to Reproduce

Go to [api](https://api.github.com/repos/thorchain/asgardex-electron/releases) and click on "0". Then you can see "name".

## Possible Solution

Change "v0.18.0" to "v1.18.0".

## Your Environment - Release Version (skip if not using a release version)

Firefox

- ASGARDEX desktop version:

1.17.1 (but this has nothing to do with the wrong entry in the api)
- Operating system and version:

**Comment by veado** [comment]
Thx @IeP4nieF , name has been updated.
