### ISSUE TITLE
Please help! Higher fee

### ISSUE THREAD

**Issue by boalexandre15** [thorchain/asgardex-electron#2456]
## Steps to Reproduce

1. Enter Poll and choose BTC
2. Used it to swap for RUNE
3. The fee was 4.50 dollars
4. The gas fee done was 0.04654314 BTC!

## Your Environment - Release Version (skip if not using a release version)

 I lost my BTC on gas fee in a Thorchain error.

- ASGARDEX desktop version:
 1.18.4
- Operating system and version:

## Your Environment - Development Version (skip if not using a development version)

- Node version:
  
- Yarn version:

- Branch:

- Operating system and version:

**Comment by boalexandre15** [comment]
@veado please help to refund this absurd fee

**Comment by veado** [comment]
> It turned out the selected Ledger wallet index the user used in ASGARDEX did not match with the latest index the user has used in LedgerLive. In this case a mismatch of index ended up in a mismatch of outputs. Instead of sending the rest back to the user, it was sent to the miner as part of the fee. 
> 
> How to get the correct index in LedgerLive? Follow description in 
https://support.ledger.com/hc/en-us/articles/360011069619?docs=true 

^ https://discord.com/channels/838986635756044328/1042591349460963349/1042792249160913009
