### ISSUE TITLE
Huge JSON error message after trying to add the the SNX liquidity pool

### ISSUE THREAD

**Issue by erikd** [thorchain/asgardex-electron#2459]
## Prerequisites

Wallet must hold SNX, RUNE and ETH (to pay for the SNX tx fees)

## Expected Behavior

I should successfully add to the LP.

## Current Behavior

Thinks about it for a while and then dumps a huge chunk (15k) of JSON to the electron window. I would paste it, but I am concerned the error message might lead to a compromise of my wallet.

## Steps to Reproduce

1. Have a wallet with SNX, RUNE (more than the equivalent value of SNX) and ETH.
2. Go to pool page
3. Select "manage" for SNX pool.
4. Select the amount of SNX.
5. Click 'Add'
6. Confirm with wallet password,
7. Wait. After about 2 minutes, the above error gets printed.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.18.4 (the AppImage version from the releases page)
- Operating system and version: Debian Testing

**Comment by veado** [comment]
Any chance to check the JSON output for a meaningful error message?

**Comment by erikd** [comment]
Maybe `ERR: MAX FEE PER GAS LESS THAN BLOCK BASE FEE` ?

**Comment by veado** [comment]
Thanks! Fees are based on https://thornode.ninerealms.com/thorchain/inbound_addresses (check for ) and in some cases they aren't cover abrupt price changes. Does it happen all the time? Have you used Ledger or a keystore wallet? Are you able to join Discord (check README or #2462 to get the link) - it's better place to discuss details. Thx!

**Comment by veado** [comment]
Confirmed, just got a similar error message for ETH.

```
 `ON":"PROCESSING RESPONSE ERROR","CODE":"SERVER_ERROR","BODY":"{\"JSONRPC\":\"2.0\",\"ID\":46,\"ERROR\":{\"CODE\":-32000,\"MESSAGE\":\"ERR: MAX FEE PER GAS LESS THAN BLOCK BASE FEE: ADDRESS` 
 ...
```

As mentioned in prev. message, the reason for this is a low value of `outbound_fee` provided by https://thornode.ninerealms.com/thorchain/inbound_addresses, which might be rarely happen. In this case no deposit transaction will be send by ASGARDEX. Wait for few minutes and try it again. Then it should work. Note: As long as ASGARDEX gets its fee data from external sources it can't do anything else.
