### ISSUE TITLE
Please provide detailed instructions for developer onboarding

### ISSUE THREAD

**Issue by erikd** [thorchain/asgardex-electron#2462]
## Description

I am an experienced developer in other languages but have zero experience with `node`, `yarn` and whatever other tools are used to build and develop ASGARDEX. If there was good documentation for someone like me around setting up the build environment, I think I could probably fix for instance #2458 .

I use Debian Linux as my main (actually only) dev environment, so something focused on Debian or a least Linux would be preferable.

**Comment by veado** [comment]
There are already plenty resources out there to get familiar with `Node`, `yarn` etc. and as an experienced dev you know how to get to this information ;) Besides that: Which information do you miss by following install/build instructions in the [README](https://github.com/thorchain/asgardex-electron)? Feel free to join Discord https://discord.gg/pHcS67yX7Z (#asgardex-desktop channel) to get more help. Thanks!
