### ISSUE TITLE
Issues showing balances of UTXO Chains

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#2535]
- Send, swaps, deposit and wallet balances of btc|ltc|bch|doge are broken due latest Sochain issue. They've updated its API and switched from a free to a payable plan.
- How to fix: Use latest xchain-btc|ltc|bch|doge package. Note: An api key for Sochain is needed, which is not free, but needs to be paid by anyone. Or wait for a next update of xchain-*, which will include Blockchair as a provider using a free api key.

**Comment by matso167** [comment]
Fixed in xchain
https://github.com/xchainjs/xchainjs-lib/commit/dc3617e8a69376cbc82239d56c39826ef485dbdf

**Comment by GrassRootsCrypto** [comment]
Fixed in https://github.com/thorchain/asgardex-electron/pull/2536
