### ISSUE TITLE
1.19.1 alpha mac dmg - dwnld error

### ISSUE THREAD

**Issue by chezp** [thorchain/asgardex-electron#2539]
Download error for [ASGARDEX-1.19.1-alpha-mac.dmg](https://github.com/thorchain/asgardex-electron/releases/download/v1.19.1-alpha/ASGARDEX-1.19.1-alpha-mac.dmg)

**Comment by chezp** [comment]
Error trying to download

[ASGARDEX-1.19.1-alpha-mac.dmg](https://github.com/thorchain/asgardex-electron/releases/download/v1.19.1-alpha/ASGARDEX-1.19.1-alpha-mac.dmg)

**Comment by GrassRootsCrypto** [comment]
The download works for me. 

Are you saying you can't download?

**Comment by chezp** [comment]
It is working now, I was getting errors a couple months ago. All good!
