### ISSUE TITLE
Mobile navigation does not close after click on ThemeIcon

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#278]
![Peek 2020-07-14 09-44](https://user-images.githubusercontent.com/61792675/87398726-a0c1da00-c5b6-11ea-8fa4-440b7fa92da4.gif)

**Comment by thatStrangeGuyThorchain** [comment]
why is this a bug ? its not a link but button. same as change lang/currency. IMAO user should has ability to set everything he wants up in terms of a single menu click

**Comment by thorchain-admin** [comment]
It appears the "menu" button is disappearing after being clicked. It should stay there after being clicked.

**Comment by thorchain-admin** [comment]
potentially the button is staying as black, so you can't see it

**Comment by thorchain-admin** [comment]
I think the standard UX is to leave the menu up after tapping something in it

**Comment by veado** [comment]
> why is this a bug ?
Currently we do have different behavior for clicking on menu items implemented: Sometimes it closed the layer, sometimes not. It's kinda confusing and I would suggest to have same behavior for all item clicks.

**Comment by veado** [comment]
We've decided to go with following behavior:

### "action" items -> close menu

- Pools
- Wallet
- Lock/Unlock wallet
- Settings

### "settings" items -> keep menu open

- Currency
- Day/night mode (theme)
- Language

### "info" items -> keep menu open

- Binance Chain
- Midgard API
