### ISSUE TITLE
Fix Hamburger menu icon

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#279]
After closing the mobile menu, the hamburger menu icon disappears.

![Screenshot from 2020-07-14 09-46-26](https://user-images.githubusercontent.com/61792675/87399141-36f60000-c5b7-11ea-91e4-d1938e4d5333.png)

**Comment by thatStrangeGuyThorchain** [comment]
@veado  yeah. thats why we should not merge WIP branches to another ones 😅😅😅
this fixed at https://github.com/thorchain/asgardex-electron/pull/276
