### ISSUE TITLE
AssetsView: Support balances of other chains

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#345]
## DESCRIPTION

Currently we handle balances of `Binance` chain only, but we will have to consider balances of `Ethereum` and / or `Bitcoin` accounts, too. We will use [`asgardex-ethereum`](https://gitlab.com/thorchain/asgardex-common/asgardex-ethereum/) and [`asgardex-bitcoin`](https://gitlab.com/thorchain/asgardex-common/asgardex-bitcoin/) in a similar way as we already have done it by using [`asgardex-binance`](https://gitlab.com/thorchain/asgardex-common/asgardex-binance/). That's we will have a client to ask about balances. 

## TODO

- Prepare `AssetView` and `AssetsTable` to handle balances of other clients

Depends on #348 and #349

**Comment by thatStrangeGuyThorchain** [comment]
closed by #426
