### ISSUE TITLE
ADD: Create Phrase

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#43]
# Create a new phrase

* 12-word BIP39 Mnemonic
* Verify Password

### Create
<img width="700" alt="image" src="https://user-images.githubusercontent.com/41812729/81545313-11345b00-93bc-11ea-998f-1477302ca9bb.png">

### Check
<img width="701" alt="image" src="https://user-images.githubusercontent.com/41812729/81545324-1691a580-93bc-11ea-80c3-84659c13f23e.png">

**Comment by veado** [comment]
Resolved by #273 and duplicated by #272
