### ISSUE TITLE
ADD: THORChain Address

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#469]
Get the THORCHAIN address from keystore and show to user

`thorxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/41812729/93557803-47fc2c80-f9bf-11ea-83a9-7355ce3c9c58.png">

**Comment by veado** [comment]
Already done.
