### ISSUE TITLE
[deposit] Update tx for sending RuneNative

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#655]
As part of #575

**Comment by thatStrangeGuyThorchain** [comment]
Implementation NOTE:
we already use common-approach for chain-based services including [transactions](https://github.com/thorchain/asgardex-electron/blob/master/src/renderer/services/thorchain/transaction.ts#L5). `transactionServiceFactory`  includes `createTransferService`  which already includes [stuff for sending transactions](https://github.com/thorchain/asgardex-electron/blob/master/src/renderer/services/clients/transaction/transfer.ts). seems the only missed thing now is adding appropriate call at the [services/chain/transaction.ts](https://github.com/thorchain/asgardex-electron/blob/master/src/renderer/services/chain/transaction.ts#L45)
