### ISSUE TITLE
[EPIC] Wallet Bugs/Missing Features

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#732]
# Settings

* Export Keystore #740
Pop up to store keystore, default name `asgardex-keystore-thor123_456.json` (first3, last3)

* View Phrase #738
Decrypt and show phrase in a pop-up, with copy button

* Mini-Addresses #739
If not enough room to show the full address, always show as `prefix123...123`, never any other format. 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/41812729/104268805-e4a38680-54e8-11eb-91f3-f326d306dba8.png">

* Show thorAddress #741

* Hide "add device" if no support yet for that chain #742

# Create Wallet #744

* Remove "keystore option"
<img width="876" alt="image" src="https://user-images.githubusercontent.com/41812729/104269013-609dce80-54e9-11eb-909f-4dc6d1a732b2.png">

* Dark Mode -> Hover over changes text colour #779 
<img width="229" alt="image" src="https://user-images.githubusercontent.com/41812729/104268960-3f3ce280-54e9-11eb-8c99-c2086908ec2f.png">

# Import Wallet #743 

* Add "keystore option" for import, user should be able to import (via file-picker) an existing keystore)

<img width="893" alt="image" src="https://user-images.githubusercontent.com/41812729/104269130-a35fa680-54e9-11eb-82d4-b3059d0253d9.png">

**Comment by sarawut11** [comment]
confirmed all issues are resolved
