### ISSUE TITLE
Deposit Page

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#736]
# Need to support all the Deposit Functions

Put on the Assets page, under RUNE - `deposit` button

<img width="841" alt="image" src="https://user-images.githubusercontent.com/41812729/104271520-3818d300-54ef-11eb-8fe2-d409eba1ca08.png">

Screen should show the 6 deposit functions
* ~~swap~~
* ~~add~~
* ~~withdraw~~
* bond (see https://docs.thorchain.org/thornodes/joining#2-send-bond)
* unbond (see https://docs.thorchain.org/thornodes/leaving#unbonding)
* leave (see https://docs.thorchain.org/thornodes/leaving#leaving)
* ~~upgrade~~

click one to fill the placeholder with the correct memo format, user needs to add the string themselves

Also add optional amount, but only for the ones with an amount (~~swap~~, ~~add~~, bond, ~~upgrade~~). Hide for the rest.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/41812729/104271495-30592e80-54ef-11eb-808b-dd06546be898.png">

**Comment by thorchain-admin** [comment]
https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020?node-id=3291%3A8041

**Comment by thatStrangeGuyThorchain** [comment]
as discussed with @thorchain-admin we need only 
bond
unbond
leave
