### ISSUE TITLE
Could not connect latest master build

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/asgardex-electron#737]
It seems that node, http://18.159.190.87:8080/v2/health is not running Midgardv2, but is running v1 http://18.159.190.87:8080/v1/health

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/41812729/104271829-e0c73280-54ef-11eb-8c57-8a4980652473.png">

**Comment by veado** [comment]
`.env` has to point to correct Midgard as follow:

```bash
REACT_APP_MIDGARD_TESTNET_URL = https://testnet.midgard.thorchain.info
```
