### ISSUE TITLE
[Wallet] Update "Create wallet" section

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#744]
* Remove "keystore option"
<img width="876" alt="image" src="https://user-images.githubusercontent.com/41812729/104269013-609dce80-54e9-11eb-909f-4dc6d1a732b2.png">

* Dark Mode -> Hover over changes text colour
<img width="229" alt="image" src="https://user-images.githubusercontent.com/41812729/104268960-3f3ce280-54e9-11eb-8c99-c2086908ec2f.png">

Part of #732

**Comment by junkai121** [comment]
Fixed by #762
