### ISSUE TITLE
Release 0.0.4 is broken for macOS

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#890]
Release of 0.0.4 is broken for macOS. Releases for Linux and Windows are working well.

![image](https://user-images.githubusercontent.com/61792675/107667389-d1bed600-6c8f-11eb-964c-85b16c7d0394.png)

**Comment by sarawut11** [comment]
I tried following approaches but it didn't resolve the issue.
- Tried to install electron-usb
- Tried to install latest usb npm module(1.6.5)
- Tried to install latest node-hid module
- Tried to use native build modules(https://www.electronjs.org/docs/tutorial/using-native-node-modules)

**Comment by sarawut11** [comment]
Also tried following approaches but couldn't resolve the issue.
- optionalDependency(https://github.com/thorchain/asgardex-electron/commit/675097ab13b847146c598c6ec53eac664926c6a2)
- webpack-node-externals(https://github.com/thorchain/asgardex-electron/commit/f879603b876eb1a5d99b1d8d8565f6b4e4917868)
- electron browser nodeIntegration -> true(https://github.com/thorchain/asgardex-electron/commit/0e1238f9661c01c32cd8d0262b685f849e29bc94)
- electron-rebuild try(https://github.com/thorchain/asgardex-electron/commit/e7eda5f07e4251b415ba1cb48bffa66e748b9cab)

**Comment by veado** [comment]
Fixed by  #1655
