### ISSUE TITLE
Release V0.0.4 - please add settings tab

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#892]
When pressing the settings button on the left -> the user is taken to the wallet section. 

This makes the navigation back a confusing since a tab is already selects. The user has no visual clue where they are in the program after they have selected settings button. 
![image](https://user-images.githubusercontent.com/40199525/107733696-296a4980-6d43-11eb-8cca-d1afbd140e1b.png)
Yes, they are looking at their wallet but there are then 2 wallet pages.

**Comment by veado** [comment]
> When pressing the settings button on the left

@GrassRootsCrypto Where do you see a settings button on the **left**? Or do you mean the settings icon (which is on the right hand side)?

Currently settings includes mostly wallet related content (keystore management, accounts), that's why we have added it to wallet section. I don't think adding another tab will be the solution here, since the goal is to keep the main navigation as simple as possible and we already have a settings icon in the header.

However, there are also "common" things (such as network) in settings... We have to re-think about that. Maybe we can hide wallet related content (keystore / accounts) with an info and button to unlock the wallet to get all information. _Just a first idea ..._

**Comment by GrassRootsCrypto** [comment]
@veado - Thanks for the reply. 
This is a small issue, you do get use to it after a bit of use. 
Correct, the settings icon.
![image](https://user-images.githubusercontent.com/40199525/108475204-f04c4f00-72d7-11eb-8d2e-40b314cf75a6.png)

The issue is, if the user selects wallet, they are taken to the wallet section and that is shown by underline of the wallet at the top. 
![image](https://user-images.githubusercontent.com/40199525/108475359-238ede00-72d8-11eb-99fb-767cddd0e26e.png)
When the user presses the settings icon, the settings is shown, however the Wallet is still underlined - so there us no difference shown to the user that they are in a different location. I understand that the settings are to do with the wallet and not general settings of the app - so it is related to wallets (well except for the client section).  

I found the this issue as I was in the settings and looked up and though how do I get to the wallet - oh i'm already here but that is not the wallet screen I remember. 

Would it be possible to add an underline to the settings cog so the user knows they are in the settings section . i can see the cog is highlighted which is good. This could be in addition or instead of the underline of the wallet.

**Comment by warrenshen** [comment]
I am a fan of the idea of treating the Settings page as its own tab, so there will be three tabs in total: Pools, Wallet, and Settings (gear icon). When user is on the Settings page / tab, the gear icon would have a highlight color underline under it and the "Wallet" tab would not (as @GrassRootsCrypto suggested above).

This would set us up nicely for future functionality in the Settings page / tab that is not specifically wallet related, such as #1339 
 (ex. a toggle in the Settings page that user toggles on to hide all private information before creating a Youtube tutorial and then toggles off afterwards).

I can take this on if this sounds like a reasonable approach. Thoughts?

**Comment by warrenshen** [comment]
@veado thoughts on this one?

**Comment by veado** [comment]
Settings will split into `App` and `Wallet` settings. It has been done by #1575. Changes will be release with a next release (v0.3.13 or 0.4.0). _Closing this issue here ..._
