### ISSUE TITLE
Release V0.0.4 - Please add copy function for address

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#893]
![image](https://user-images.githubusercontent.com/40199525/107733791-65051380-6d43-11eb-8500-ec96cf052c26.png)

Please add the a copy icon that copied to the clip board. I see that being used more than the need to go to a block explorer - happy to have both. 
BEPSwap has a copy function - good to keep it the same
![image](https://user-images.githubusercontent.com/40199525/107733999-e8266980-6d43-11eb-8c84-13645bc2c50a.png)

**Comment by veado** [comment]
# TODO (ASGDX team)

- Add copy button to addresses in Settings (_we already have it for small screens there, but we do need it for large screens too_)
