### ISSUE TITLE
Release V0.0.4 - UI issue Hide amount button does not work

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#894]
- [ ] Using yarn dev
- [ ] Using node 14.15.1
- [ ] Using https://github.com/thorchain/asgardex-electron/releases/tag/v0.0.4 
- [ ] None

## Expected Behavior
When the the show amounts button is selected, vaules are hidden or star-ed. 
![image](https://user-images.githubusercontent.com/40199525/107734485-0e003e00-6d45-11eb-9add-719d0d97bbdc.png)

## Current Behavior
Nothing happens or it is taken to the wallet of the chain (send, receive / transaction page).

## Possible Solution
Enable the hide values feature where the highlight is in the image. 

## Steps to Reproduce (for bugs)

Load a wallet. 
Go to wallet section
Expand and press the hide values feature 
![image](https://user-images.githubusercontent.com/40199525/107734587-4d2e8f00-6d45-11eb-9b5a-d5ada9dcd48d.png)

Hide values when showing a friend - like other wallets. 

No

**Comment by veado** [comment]
Good find! This button has not a callback, because we have not added a feature to hide asset yet. We have postponed this feature to move forward by introducing more chains. However, we should hide the "show/hide" icon at the meantime.
