### ISSUE TITLE
French Traduction

### ISSUE THREAD

**Issue by Weyland2093** [thorchain/asgardex-electron#932]
I proposed to do a french traduction of the App, and Leena said : "do you mind putting as an issue on Github?" so... et voila !  ;-)

**Comment by Weyland2093** [comment]
Edit							Edition	

View						Affichage

Help						Aide

Undo						Annuler

Redo						Rétablir

Cut							Couper

Copy						Copier

Paste						Coller

Select all						Sélectionner tout

Toggle Fullscreen				Passer en plein écran

Learn more ...					En savoir davantage...

Documentation				Documentation

Telegram						Telegram

Report issues					Communiquer les problèmes

POOLS						POOLS

WALLET						WALLET

POOL						POOL

ASSET						ACTIF

PRICE						PRIX

DEPTH						PROFONDEUR

24H VOLUME					VOLUME SUR 24H

AVG FEE						FRAIS MOYEN

TRADES						TRANSACTIONS

REFRESH						RAFRAÎCHIR

MANAGE						GÉRER

SWAP						SWAP (or ÉCHANGER)

IMPORT						IMPORTER

IMPORT AN EXISTING WALLET WITH FUNDS ON IT		IMPORTER UN WALLET EXISTANT AVEC DES FONDS

CREATE						CRÉER

CREATE A NEW WALLET, AND FUNDS ON IT			CRÉER UN NOUVEAU WALLET, ET L'ALIMENTER EN FONDS

KEYSTORE					CLÉ PRIVÉE

PHRASE						PHRASE

ENTER PHRASE				ENTRER LA PHRASE

PASSWORD					MOT DE PASSE

REPEAT PASSWORD			RÉPÉTER LE MOT DE PASSE

SELECT KEYSTORE FILE			SELECTIONNER LE FICHER CLÉ PRIVÉE

CHOOSE FILE TO UPLOAD		CHOISIR LE FICHIER À UPLODER

PASSWORD					MOT DE PASSE

PLEASE CONNECT YOUR WALLET	CONNECTER VOTRE WALLET SVP

CONNECT					CONNECTER

**Comment by veado** [comment]
@Weyland2093 Thanks for your translations ^ - highly appreciated! To see all texts ASGARDEX is using (currently `EN`, `DE`, `RU), go to folder `i18n` located `src/renderer/i18n` and check all folders and files there. To add French translation, just copy folder "en" (or any other), rename it to `fr` and add translation into files of newly created `fr` folder. 

Just a friendly note: Current texts might be changed, removed, added etc. before we go live to main-net. Every change means another work for any translation. If you don't worry about such work over time, please feel free to open a PR right now. In other case, we would love to wait for your contribution just before main-net. Thanks again!

**Comment by Weyland2093** [comment]
Ok thanks !!! I will do it very soon. ;-)

**Comment by Weyland2093** [comment]
Done ! Merci à la team ! ;-)
