### ISSUE TITLE
[ETH] Same tx appears twice in tx history

### ISSUE THREAD

**Issue by veado** [thorchain/asgardex-electron#960]
```
Encountered two children with the same key, `0xdacb4283671c2e1cf0057149a9685a8ecc63f429876a662e7b0b277d80334f71`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

That's because a row of the table uses a key based on transaction hash. Currently we have two entries with same tx hash in the table, which might be wrong. 

https://user-images.githubusercontent.com/61792675/108746002-0d815780-753c-11eb-808e-10e3634113d7.mp4

**Comment by sarawut11** [comment]
It is handled by https://github.com/xchainjs/xchainjs-lib/pull/249
